In [23]:

import numpy as np
from math import sqrt
import warnings

import pandas as pd
from pandas.core.common import SettingWithCopyWarning

warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

In [24]:
data = pd.read_csv("data/symbol_pins.csv")
data.head()

   Symbol Name Pin Name  Pin CenterY  Pin CenterX  Pin Width  Pin Height
0  90980-12A87        8      -5759.0      10368.0        0.0         0.0
1  90980-12A87       10     -13439.0      10368.0        0.0         0.0
2  90980-12A87       23     -17279.0       5760.0        0.0         0.0
3  90980-12A87        6       1920.0      10368.0        0.0         0.0
4  90980-12A87       15      13440.0       5760.0        0.0         0.0

In [25]:
len(data)

7341

In [26]:
data.isnull().sum()

Symbol Name    0
Pin Name       0
Pin CenterY    0
Pin CenterX    0
Pin Width      0
Pin Height     0
dtype: int64

In [27]:
def cal_distance_center(row):
    xs= 0-float(row["Pin CenterX"])
    ys= 0-float(row["Pin CenterY"])
    return sqrt((xs*xs)+(ys*ys))

In [28]:
data["distance_to_center"]=data.apply(lambda row: cal_distance_center(row), axis=1)

In [29]:
cols=['Symbol Name', 'Pin Name', 'Pin CenterY', 'Pin CenterX', 'Pin Width',
       'Pin Height', 'distance_to_center', 'neighbors']

dataout=pd.DataFrame([],columns=cols)

In [30]:
list_pn=list(data['Symbol Name'].unique())
#list_pn

In [31]:
def get_neighbors(row, distances):
    pin_row=row["Pin Name"]
    distances_sorted=sorted(distances[pin_row], key=distances[pin_row].get, reverse=False)
    ts=distances[pin_row][distances_sorted[0]]*1.9
    return [x for x in  distances_sorted if distances[pin_row][x] < ts]

In [32]:
for pn in list_pn:
    data1 = data[data['Symbol Name']==pn]
    if len(data1) > 1:
        
        data_json= data1.to_json(orient="records")
        dicc_json1=eval(data_json)
        dicc_json2=eval(data_json)
        distances={}
        for ele in dicc_json1:
            pin=ele['Pin Name']
            distances[pin]={}
            x1=ele['Pin CenterX']
            y1=ele['Pin CenterY']
            for ele2 in dicc_json2:
                pin2=ele2['Pin Name']
                if ele2 != ele:

                    x2=ele2['Pin CenterX']
                    y2=ele2['Pin CenterY'] 
                    distance=sqrt(((x1-x2)*(x1-x2))+((y1-y2)*(y1-y2)))
                    distances[pin][pin2]=distance
        #  get neighbors
        data1['neighbors']= data1.apply(lambda row: get_neighbors(row, distances), axis=1)
        
        dataout= pd.concat([dataout, data1])
    else:
        #print(pn)
        data1['neighbors']=""
        
        dataout= pd.concat([dataout, data1])

In [33]:
dataout.isnull().sum()

Symbol Name           0
Pin Name              0
Pin CenterY           0
Pin CenterX           0
Pin Width             0
Pin Height            0
distance_to_center    0
neighbors             0
dtype: int64

In [34]:
dataout["internal_pin"]=""

In [35]:
cols=['Symbol Name', 'Pin Name', 'Pin CenterY', 'Pin CenterX', 'Pin Width',
       'Pin Height', 'distance_to_center', 'neighbors','internal_pin']

dataout2=pd.DataFrame([],columns=cols)

In [36]:
# def internal_external_pin(row, ndistances, xg,xy, distance_to_center):

#     nave= np.mean(ndistances)
#     xg=0-(np.sum(xs)/len(xs))
#     yg=0-(np.sum(ys)/len(ys))
#     centroide_distance=sqrt((xg*xg)+(yg*yg))
#     print(f"{centroide_distance} {distance_to_center}")
#     return (centroide_distance*1.1> distance_to_center>centroide_distance*0.90) and (distance_to_center>centroide_distance)

In [37]:
for pn in list_pn:
    data1 = dataout[dataout['Symbol Name']==pn]
    if len(data1) > 4:
        for i, row in data1.iterrows():
            data_json= data1.to_json(orient="records",force_ascii=False)
            #dicc_json1=eval(data_json)
            dicc_json2=eval(data_json)
            ndistances=[]
            xs=[]
            ys=[]

            pin=data1.at[i,'Pin Name']

            distance_to_center=data1.at[i,'distance_to_center']
            neighbors=data1.at[i,"neighbors"]

            for ele2 in dicc_json2:
                pin2=ele2['Pin Name']

                if pin2 in neighbors:
                    ndistances.append(ele2['distance_to_center'])
                    xs.append(ele2['Pin CenterX'])
                    ys.append(ele2['Pin CenterY'])


                ndistances=sorted(ndistances)
            nave= np.mean(ndistances)
            xg=0-(np.sum(xs)/len(xs))
            yg=0-(np.sum(ys)/len(ys))
            centroide_distance=sqrt((xg*xg)+(yg*yg))
            print(f"{centroide_distance} {distance_to_center}")
            data1.at[i,'internal_pin']= str((centroide_distance*1.1> distance_to_center>centroide_distance*0.90) 
                                            and (distance_to_center>centroide_distance))

        dataout2 = pd.concat([dataout2, data1])
    else:
        #print(pn)
        data1['internal_pin']=str(False)
        dataout2 = pd.concat([dataout2, data1])

9538.067479316762 11860.080311701098
15440.705011106196 16973.571957605152
19267.4870193287 18213.77064201699
7841.975924472096 10544.279207228914
15915.584030754258 14622.284363258705
10287.77410521829 8145.1630431809035
8738.429561425783 6071.573107523288
15914.739584422989 14621.365223535044
12837.9521747045 11194.570157000224
10288.333929261822 8145.870119269028
12246.16879844468 14129.947770604107
20554.26534809746 21891.36816190345
19942.54788135157 23527.63957561404
8738.209850993508 6071.256953877014
7841.7310971494035 10544.09716381635
18877.83068151635 20150.912262227732
9538.671303698435 11860.565922417025
20553.36237699321 21890.403399663515
18878.74599225277 20151.769748585357
15441.57538076993 16974.363728870663
19268.383820133953 18214.719322569865
12838.699896796405 11195.427638102978
19941.617211249442 23526.741912130543
12245.3848955433 14129.268381625427
8164.547774439875 13223.891144440051
8525.067012053336 7625.961513147047
10037.362215741743 12341.635588527155
8674.564210956076 7760.431753452896
9198.475831625585 9598.800133350001
9598.600650326298 13573.791953614142
9128.671274616037 4378.27363238069
23456.707086886687 20783.057715360366
19137.827739845503 22421.712356552966
27531.76744998403 25295.225794604008
44105.47358321867 46207.548571634914
27828.23917102913 25613.83626089618
32451.5444217991 30573.852357856376
26751.286492428735 29183.607727626822
42191.021426365114 40764.18192482219
16982.18518919164 20747.35802457749
36475.460006969064 38302.43605829791
20217.011201461013 17040.473232865337
23707.974072029014 21064.94642765559
16912.68540238362 20676.35867361562
31790.49240512012 33868.82176870049
22533.169173465147 25383.113776682323
37391.66541623949 35774.39710183807
27054.455591639613 29468.71642946126
19329.293070363434 22584.675888752532
22794.751733677644 25613.83626089618
36819.41491387391 38628.2814528423
43296.03253186139 48449.85993787804
18124.74152974326 14668.850261693995
31462.095777617862 33553.135173929724
39277.702580471785 41123.381974249154
38365.81645307592 43629.65010173701
18189.574935110497 14769.031383269521
37053.02296331569 35422.308902724
32127.911752866854 30234.3613790667
41684.691271976575 43290.35883427163
20398.161238699926 17255.449226258934
21615.869748867382 25380.80662626781
21616.84676357771 25381.7900077989
7376.3991215226415 7376.3991215226415
14208.0 14208.0
10647.744596861816 10647.744596861816
21616.84676357771 21616.84676357771
14207.054057755957 14207.054057755957
10648.646111126052 10648.646111126052
17882.883017008193 17882.883017008193
10647.744596861816 7375.618279168195
21615.869748867382 21615.869748867382
7376.3991215226415 4992.0
17883.84925009155 17883.84925009155
6540.32510235114 8217.958870668555
6534.628303316112 6540.862634240227
6540.32510235114 8456.087097470083
6533.349532292843 11143.074306491902
6533.349532292843 1960.6144445045793
24710.3742950203 28009.906033401825
24991.37920520044 24972.252000971
15540.804361522765 15543.14073795898
20286.475237348543 21129.843208126273
26947.908132543424 29989.69991513753
17293.99187940714 17306.208741373717
22558.43289278147 22539.74538454239
17303.896918396735 17301.082740684178
13281.788977393067 9919.738555022506
23516.220911532535 26966.214955013616
26198.84931900636 28233.665897293606
15537.12878327669 15545.042585982195
15300.610461024095 12484.604038574871
27568.682812205592 32780.61097661238
20374.767425052978 20368.319911077593
24715.919606601732 28020.842671126076
22551.283989567535 22541.176233728354
21837.868765060382 24261.618680541495
18710.360270181864 16515.15092271336
24980.622882108546 24974.40453744593
13285.309571101458 9935.98374596094
23514.75799152524 26962.426838101943
20276.962719083724 21076.3486875692
20360.746175238764 20375.57667895562
18697.858000316504 16466.25427958648
21234.423315986238 21220.190880385595
21236.622393947797 21219.68418709383
15309.777603871324 12523.294215181562
27559.291300757355 32758.792957006215
26954.290773826717 30016.10674288056
21854.567046729615 24253.086401528362
26212.53003126558 28231.000159399242
17924.2189375158 15968.461697984561
13642.968282598915 12057.04843649556
14629.11911437254 15292.953933102655
19398.820081529586 21299.703119996768
19401.6231422929 21305.378499336734
16347.265765258728 18929.819861794775
9647.930360963433 12057.844583506623
17921.58025733222 15968.461697984561
11195.59915770478 13224.32667473093
13643.238414687328 12057.844583506623
18491.921936047882 23608.422225976898
18489.863364076606 23600.73882318094
14628.553243571287 15293.581562210991
11195.341944308802 13223.891144440051
16345.100013289746 18929.059379694492
10794.816545453656 7544.402958485184
9647.830857244544 12057.685391483723
10794.727613515775 7544.148527169915
31056.475814232366 31056.475814232366
15754.812915423654 15754.812915423654
35562.198863399884 32695.54936073104
24280.0537478812 24280.0537478812
22682.992086583286 22682.992086583286
58425.415462793244 62144.45793471852
45040.31869336628 45040.31869336628
41406.55467435077 41406.55467435077
23611.01543771466 24963.93017936078
55611.30737538904 58866.253048754515
43555.21263867277 43555.21263867277
15015.268562366775 15015.268562366775
51820.779500119446 55299.28957952353
38593.96494272129 39436.17489057477
34649.28149327198 34649.28149327198
46386.52808736606 46386.52808736606
39006.85952496048 39006.85952496048
57463.434390923765 57463.434390923765
40888.80418892194 40888.80418892194
30467.657113732916 30467.657113732916
64112.25820387237 64112.25820387237
43627.03991792246 40396.30344474603
53801.836883139964 53801.836883139964
46949.622916483575 46949.622916483575
38598.34488679534 38598.34488679534
31231.562048671214 31231.562048671214
40040.895719251836 40040.895719251836
30356.92293365716 30356.92293365716
48070.02446431664 45158.27689361054
54723.08372158864 54723.08372158864
41406.55467435077 43072.30444264621
40173.060276757606 40173.060276757606
22213.258428245055 22213.258428245055
58885.38742336676 58885.38742336676
49186.95640106226 49186.95640106226
50345.87144940487 50345.87144940487
45310.11617729533 45310.11617729533
68086.37963645886 68086.37963645886
51710.8317473235 51710.8317473235
48950.318364643965 52618.93107998299
60852.05840396856 64431.184157983625
23179.171037808923 23179.171037808923
38331.29335151633 38331.29335151633
38033.30395850458 38033.30395850458
31568.11128338216 31568.11128338216
27972.999302899214 27972.999302899214
16383.534722397362 18279.441184018728
38593.96494272129 38593.96494272129
22830.976545036352 22830.976545036352
53255.05320624513 53255.05320624513
68086.37963645886 71303.29285523917
51104.55686139935 51104.55686139935
43758.69344484591 43758.69344484591
38147.426492490944 38147.426492490944
34489.32197072016 36472.37269495913
64112.25820387237 67518.78354946866
47384.205511963584 47384.205511963584
64937.21438435745 64937.21438435745
34489.32197072016 34489.32197072016
25908.67132834102 25908.67132834102
41705.76444569743 41705.76444569743
23611.01543771466 23611.01543771466
19549.920971707277 19549.920971707277
16383.534722397362 16383.534722397362
46842.22923815646 46842.22923815646
41767.040450575376 41767.040450575376
55611.30737538904 55611.30737538904
49354.37800236166 49354.37800236166
46842.22923815646 44704.8476118642
53255.05320624513 50642.308517681144
56009.36682377332 56009.36682377332
31231.562048671214 27923.814710744664
57306.71629050124 57306.71629050124
60124.18515040349 60124.18515040349
48950.318364643965 48950.318364643965
17333.815794567567 17333.815794567567
51820.779500119446 51820.779500119446
54241.27037597847 54241.27037597847
51041.09924364874 51041.09924364874
15237.901758444305 15237.901758444305
60852.05840396856 60852.05840396856
60124.18515040349 63146.938801496945
52435.58398644951 52435.58398644951
57199.56818018822 57199.56818018822
31056.475814232366 32097.078527492187
61866.143665174415 61866.143665174415
22213.258428245055 25182.324952235846
27972.999302899214 30384.359957056855
43627.03991792246 43627.03991792246
48070.02446431664 48070.02446431664
58425.415462793244 58425.415462793244
30729.442071082252 30729.442071082252
40888.80418892194 38421.65103167744
35562.198863399884 35562.198863399884
60757.45527916718 60757.45527916718
54388.92129836737 54388.92129836737
32837.23328783958 32837.23328783958
40173.060276757606 36639.01598023615
38121.74668086445 38121.74668086445
48396.96424363826 48396.96424363826
9786.621318923095 11703.472347982884
7179.965752007456 9630.272322213947
10383.91667146843 8764.962977674235
6067.200013185653 8832.0
11554.01648778467 12269.04792557271
10650.88170059174 14515.219082053154
10651.722865339672 14516.012675662694
7180.28661266387 9630.67100466006
10383.17708796301 8764.08677501541
11554.791906391045 12269.986797058911
9787.405981157623 11704.128502370435
7973.9775394717535 5707.897774137165
6988.800011446887 4224.0
7974.266451530198 5708.570398970306
9971.89578966808 7878.290233293008
7470.003012047586 10166.750562495374
9972.473346166436 7879.021259014346
12586.239535302035 11001.916969328573
16971.08320055028 18096.000027630416
9235.499371447111 11526.398223209191
12011.529820967851 13850.64099599726
15712.394650084372 14474.394529651317
8364.242990253213 5708.570398970306
12010.730603922477 13849.947906039213
12587.002210216695 11002.789464494901
9234.8757241232 11525.898533303163
16261.14095013016 19956.054144043606
7470.2600222482215 10166.939362463021
15713.249970645793 14475.323001577546
8364.013450491337 5708.2341402573875
15255.280057737386 16741.773412634637
16262.046119723065 19956.92000284613
15256.161005967391 16742.576145862382
16971.95050664478 18096.954881968402
7300.5860209985885 7300.579703009892
24506.68684257421 28780.779089524312
12516.98611665142 10528.654662396331
21264.505027287974 21219.059569170353
18854.38317739406 17089.596367380946
24358.631116893434 26720.53809338427
15671.792305365076 13558.046503829377
21206.371330988663 23528.98986357043
23639.502892404485 28592.819797984248
12649.648216452504 10662.738109885284
16209.347334177277 16632.468487870345
18122.86559791249 19357.132664731107
22112.429768797458 22420.22015948996
22252.123211055616 23691.169325299248
14993.464778445974 16502.457059480566
24875.395369275597 27947.166224860794
18604.501960547077 16919.33125155956
8291.599604418921 8291.599604418921
14591.553721245726 13715.995917176411
8205.714853076483 8205.486518177944
24430.672274372184 26439.991546897287
22161.043192954614 20002.124687142612
11139.396098731944 12390.091565440507
9387.951427228412 13153.051052892633
22950.76981521777 22103.36155429757
25332.474671851545 28872.229425522375
10428.594589450253 14124.661057880292
23617.642448231363 23618.170653122143
25082.968010185716 27296.143042561893
9045.683230752176 5168.9040424445875
23068.281764265746 19955.861795472527
8191.249965664581 4206.8292097493095
25552.263863610122 27586.271386325483
7187.874264651855 7992.82878585548
24237.69814153151 23766.49616582133
10171.974046368778 11269.271493756816
26414.506776054368 29924.609287340747
24251.56286922556 25422.26553633645
8422.411255691568 10183.24270554326
9893.11329966457 8681.6109680174
24021.38609424712 23081.504305395694
24717.202216080706 24716.092935575398
21951.339592127148 18815.12691958255
26187.23578005132 28407.897511079555
23115.125342511124 22621.715098550772
9416.739669333543 11016.44452625256
8951.297783003312 7595.535530823353
23252.432407814886 21090.14428589809
8154.1391397934285 8527.827449004817
25324.248083605562 26443.883697369416
8374.995895521382 8298.173413468774
4926.269836296018 4912.915631272331
4927.366461914518 4919.942377711349
8385.778705642071 8281.827394965438
8298.173413468774 12193.863743703223
8281.827394965438 12204.897418659446
3072.0032958966694 3072.031900876031
12268.150634875657 12301.492592364555
10391.085410100333 9376.60066335343
14233.261362035055 12300.665388506428
9844.883391894493 9375.924967703186
9843.73939516889 7041.454395222623
9384.460346764752 13147.444466511353
9343.041060061762 7348.521551985814
18408.985632022206 19125.26122697413
8208.888855990193 11787.087214405432
8939.366536841411 11598.135022493918
17359.759452538507 21249.638491042617
18265.193155288558 19146.194634965977
17473.0 21248.798201310117
17467.22605020296 15627.667772255718
17008.19570089667 18141.957584560714
17583.66517538366 15626.770907644355
22244.378346899244 20486.673839352254
32843.79629228157 34398.901624906575
33789.85104311093 33780.1199080169
21344.83822445429 20870.656913475435
43866.06055262143 43849.337155765534
45066.37887778704 45072.43029835423
31702.45618307831 30494.442198538407
18128.889883277465 15928.989735698871
35331.55470547893 35319.78210578315
15410.628102059954 15383.560316129684
49897.00106419222 52609.396242496456
27139.21718570978 27630.130600487577
20383.416299231536 21158.270723289275
38740.36334209517 43213.74394796174
40492.178498600195 40498.288914471435
35800.99670836693 36167.31586667719
14159.192387368003 10594.146685788337
14898.563270329123 12119.746697023003
33087.0201424403 33084.86060118736
37607.19978026149 37596.18024480678
41173.83966063889 44009.011315865755
22422.774961032923 21980.7685033986
32501.112916041046 32907.863892996764
46956.96897373168 49830.05347177544
44491.35118199941 47517.11375914998
27425.2276978292 27858.781685493715
39121.429781372884 38706.55144804301
42583.48119635125 45733.604461052484
17290.111667348705 18712.31693297225
26543.19620919832 24157.650651501688
31640.33481990393 31345.935781214124
39578.587166073776 39908.902590775404
35860.40861996172 35606.36276004613
41311.742021851365 44551.59045421387
37653.3924936386 40155.76235112465
24688.445238233413 24298.30220406356
40787.45473334908 44167.284408258565
38552.01126258687 38545.5603798933
32686.755453279544 32664.552423077836
40737.1897670912 44023.790295702616
45330.42004173356 47608.67771740778
39155.229181625604 39154.19953210639
50678.65369166785 55783.28040730484
38315.31205993238 45847.1319277444
30137.69778393913 30807.06336215771
23619.771682056962 23594.961008656064
13222.26433860706 9987.764714889914
27851.310618005482 27509.073285009075
15436.844295566227 15783.302189339212
27992.589200090082 28467.881428023407
49456.95529366926 51582.39820907904

16875.15846684854 16847.265416084592
33509.26845250762 35695.808073217784
27990.031516818624 27966.01998855039
32400.644275144354 33279.4906962231
29836.291170003857 30284.706982237753
48120.30038254385 48129.20618501826
40491.84161076463 40476.77539033958
26836.862447014926 25397.9939759029
19789.125510065496 19766.87375383371
42493.07227452641 42498.542186762126
34628.97596233536 37566.933571959264
10227.249202498197 10226.967683531615
8452.00013310459 8452.000059157595
10247.670271822763 10228.657047726256
10226.967683531615 14286.379107387567
10228.657047726256 14316.055497238058
12519.608320550607 14264.509385183916
12188.005677714464 14166.425660695078
12556.384623469448 14263.634634972952
12371.115400399432 17514.125270763598
9600.000013020834 11904.0
10732.790902766157 12507.723094152669
12216.317942817304 14165.883558747757
12370.475263707534 17649.385768348995
10733.126291998991 12508.03006072499
11774.476827549493 8244.363953635235
11774.782545762788 8244.829652576213
12923.04255506419 10592.386747093406
12893.523167854471 10593.111724134698
6732.149790371573 9418.199615637799
10600.952504374312 10841.804739064433
9452.856436019749 7374.993559319221
9358.455101612066 13855.35943236407
8752.121765606327 10869.749261137536
10603.555483369193 10834.755373334463
9357.159778004814 13859.069521436135
7619.786605935891 4988.232252010726
7620.953693600296 4991.694301537304
9453.643022665918 7376.712004680676
8752.870020741768 10872.398263492742
6730.572950351256 9417.1805228529
8176.664417719489 10696.643258518066
9001.01242305553 6606.585805088737
8176.946168344268 10697.002196877404
8140.800009827044 5376.0
9000.756468208658 6606.004617013222
9878.416067366266 9374.634712883484
9877.897802670364 9373.815498504331
7219.20001108156 9984.0
8601.752379602658 12596.136550545965
8601.157189587922 12595.526864724636
39314.56305755222 40099.29388405736
66456.3935959346 65335.484730734184
77513.08326633075 77528.59813642963
95426.4577194862 99999.35168289843
53732.599877192806 53621.79897205986
25884.770788588758 24559.522633797264
68390.19200006354 67324.30789841065
81147.26040941324 80786.09982540313
89999.78354350387 90633.76397899406
95221.74261732453 98384.63461841996
69167.87138018363 69159.05714365978
39785.42448573603 40096.65045861063
12064.745386869961 9854.008575194159
67282.20756692013 67994.97632178424
69288.42919910944 68803.99974565432
91702.78708695622 91702.66495582339
80061.40807205428 79644.87359522897
36529.50207873083 39332.676046768036
44309.07282409834 44297.72695071385
34630.112340193824 35021.1662427167
28199.991095964906 28198.771693107486
24521.25768147405 24502.091543376457
24377.282439006834 25345.900516651604
34366.04063606979 37204.298810755725
26645.50140736706 30120.020451520282
51440.94775626223 51442.10412687257
93119.89748185535 93131.0626268164
46445.31333797308 46445.540151881105
13346.267830371156 14548.456034919995
23528.741369222305 23877.01932821599
75201.50981170525 76610.90849872491
49520.935633641355 49510.55759128552
83432.57457324446 84660.20993359276
24836.774318160762 26105.378602885652
37846.48599222919 40418.771938296195
79914.21981690395 80421.1233010333
21148.717912940047 20205.706248483373
87177.66974376595 87251.94702698616
74517.22239868865 74510.40583703728
23292.398575500978 21816.113356874546
34186.95907213743 33197.47576247327
34290.66652576543 34787.129487786144
93777.0880215418 94904.75428027828
86385.42714495093 86386.52300561703
11363.209203389684 7904.049405209965
64980.58697304228 63826.53036159807
21107.68364451047 20963.200375896806
32019.32085788204 35158.04210987865
17137.233451387274 17200.557258414625
70555.1366965271 70555.97749305157
78308.65248234068 79610.02819368927
36162.75935808307 36208.353083232054
63663.548295413915 62846.3657024016
93833.78091071466 97033.54762658119
89994.47371922345 95549.60405988086
24179.462824471517 22758.784897265494
82686.22093918142 82696.97230854344
33237.29842330751 32218.287508804686
81085.95862117944 81084.13884354942
26051.58667643873 29855.296431286693
57516.68093801136 58594.53275690489
53783.39309192011 53765.98897072386
25333.8081977424 29207.033844606678
87312.40943366018 90496.69046434792
53920.378306379906 53944.710296747355
75807.23440782218 75806.99285026416
45962.237439445875 48061.996400482574
29643.60267461788 29444.982951260135
55059.36647692198 56878.10554158779
31932.420995361437 34526.929678151224
29409.09572687032 30079.17515491407
28413.002765635312 31911.149728582328
19536.554972665985 17748.641779020727
87969.82786205734 89176.43520572013
29723.390959919932 30011.39631873199
41737.659496430795 44091.76255265829
58753.65864754486 59055.268841992416
79512.05660451752 79091.62844448203
68741.38626388035 68255.67144933819
44071.12951127983 45258.60335891951
32506.344603063644 32543.021817280583
36843.03675242616 36841.92347041614
41563.804111871184 41563.36277299997
28177.28574934073 26968.29295672976
15429.794607835842 13093.871925446652
74121.79751355198 73670.82794430913
74670.09803716613 74221.66450572232
88605.69798382044 89716.66583751315
72381.2984052381 72401.53885795522
43718.67228808136 45796.11932249282
58563.01888461694 57991.380264656575
44584.640174090506 44624.5447483781
55176.771534028405 55543.08991224741
12296.774475446804 13670.47449798287
38404.398854818704 37526.04229065463
89077.1779133129 89944.81355253342
40223.15836077054 40263.6833138748
75178.04167645046 75056.06419870416
53607.451888706666 52596.31053600623
22490.35910013722 23584.17785295896
32351.97454971837 32349.574216672467
43975.98155811874 43861.65976111711
55420.99086186669 56520.851019778536
81558.53154072847 82860.89705645239
85255.47009585734 85250.00570674468
92214.1868711778 96024.00625885175
43640.71546709564 42870.490141821334
39162.0489921764 39148.60837884279
50416.77457116827 52370.09116852863
49168.7994556126 49203.91314722844
53642.71947519481 54768.61270837522
64283.627527198216 64369.752042399545
48923.57883965563 48238.78939194059
85512.6342325442 85797.87746791875
57736.14198325959 58807.63040626616
73241.11025510194 74571.50555674735
68815.32009752624 69687.98566467538
84910.16690243872 84516.18478137781
68942.08991842356 70447.34916943291
69471.75207967918 69704.1854769138
41621.15529487379 44153.59252654307
59752.99933528442 61512.92373152165
79880.85241519475 79874.24727657845
87893.99168103017 87900.33120529182
29103.02987456804 27934.693304205077
12405.55769161548 9339.587624729478
85460.21474581024 85069.77189342875
18768.9384689172 16848.171325102317
88594.42249832943 91182.45981547108
73198.4525183294 74361.93223014045
63918.5376994812 63394.03506640037
89531.73522723661 93756.02647296866
46999.57234712354 49281.96542346906
29200.942247746905 29184.757836925768
14389.106824261191 14883.251425679808
61412.80266882977 61804.770382228584
62760.05997256535 64441.98591756775
21768.9890142635 22733.945478073092
34109.517917703335 34095.31071863109
39369.23202959388 38512.08779071838
11864.451131004755 9001.120874646667
10372.00009448515 6916.000072296125
11863.285993349398 8999.201075651104
11705.835296979025 17127.326119391782
11707.803252532049 17128.671168540775
13216.814156385964 13437.42895795174
9220.000106290672 12676.00003944462
10870.490815046025 13922.483255511568
13215.264658719476 13434.856902847905
10871.762352075215 13923.724250357733
17785.64637565922 21656.938310850866
11376.06346677092 8663.43488461707
14073.009572937837 16204.935575311616
17786.47396197459 21657.73616978469
16927.563245783487 18737.468772488988
10468.845858068596 13196.4213330736
14760.341623417798 12787.083522054589
14073.691677736868 16205.52794573506
11793.001248198017 14269.730796339501
17503.156396490318 15874.58043540049
14760.991966666737 12787.834218506276
11793.48962097309 14270.134407215652
11375.894698879732 8663.213318394048
12605.275278231727 10224.225398532644
10468.662464708661 13196.275876170519
16926.76928536571 18736.751506064225
18691.9447891331 19234.528951861546
18691.157294292934 19233.630572515423
17502.388546709844 15873.733807771881
12605.732181829026 10224.788701973259
18183.859657399473 19799.445472032796
10450.612998288667 13060.65086433291
15078.099085760115 16991.596776053746
19906.318594858265 20740.003085824264
11304.78486305688 8753.397511823623
19925.534798343557 20761.283799418572
18692.48927350234 17269.51142910534
9715.206688485841 12480.004847755468
12390.988339918653 14659.53208666634
13126.042634396705 11005.447060433302
18164.42168195839 19781.595082298092
12376.725537879558 14647.47841780284
19125.016732018823 22908.795712564202
15670.851228953708 13942.827833692849
15687.749208857209 13961.817396026923
18673.580755709387 17249.043103894197
15060.517090724343 16975.99670122494
10442.306143759626 13053.887696774475
10636.80610897839 7872.007685463728
11312.45840832133 8763.480187687994
13112.579389273491 10989.38615210149
19104.99536770423 22889.511659273117
5220.800245173148 8444.010007099707
5184.200441941093 10014.956864610052
5181.777740848748 10011.19473389665
6890.002749555974 6193.5505164646875
6891.824980043788 6199.62974700909
6295.2023160498975 3072.005859369412
7004.325212324168 10025.95132643282
7707.624421455824 12914.440444711494
7693.343912471062 12913.771912187392
6998.898684793201 10025.664317141283
9172.477703555469 9623.798886094824
7993.164342111327 5130.291707105942
7992.228169916072 5109.579336892617
9165.071673357377 9607.383462733233
11306.904494599748 11313.093520341818
11313.093520341818 16150.022569643672
7841.863458387936 7854.989560782369
7850.5604895446795 7831.221616069871
11311.072506619343 11319.037856637817
11319.037856637817 16139.67688648072
10029.974149518033 11996.54350219262
32907.40245834599 34865.846669771265
17037.386622366706 16035.35297397597
19550.06538352238 22372.858221514747
17487.599296040862 17913.0272706765
9997.119585160517 5998.27175109631
29472.9136878253 28416.0
31591.572111561654 31062.688631218
31990.899232351134 32072.62159537321
30425.897748099032 27272.111469411386
17037.653473410006 16036.310797686605
9996.479430279442 5997.631615896395
18326.368622531005 19745.21876303223
29471.71256582318 28415.054055904944
31568.573598244468 35599.86719076351
18326.508308397915 19745.21876303223
33179.808336547096 35761.26509227547
33178.59673889931 35766.73226617159
27524.477200101166 28721.640360536512
19550.438029335528 22373.630550270558
27525.097235169862 28722.50936112651
31591.183530219314 31065.655441339073
13676.688455909201 12406.491244505838
17488.197023675395 17912.684220964762
31990.613979381167 32072.62159537321
30424.607591735854 27271.125847679996
8871.073046706357 9983.615427288854
31568.573420500896 35598.950335648944
18676.976217391293 21296.390703591067
13202.726133643762 14752.017387462638
18677.31032563308 21296.390703591067
10646.153288394828 8956.342110482381
13203.34735739388 14752.798243045283
13677.301628610814 12407.419715637898
10029.208465277805 11995.903342391519
8871.79440699569 9984.0
10645.431923599906 8955.48463233565
32908.04968055351 34864.85544212108
13931.891481417733 12879.751550398789
14228.75961252811 17432.791199346135
14976.000008346688 8448.0
14228.705648949395 17432.923334885632
13931.92248264754 12879.572702539475
18313.239932901004 19405.361759060303
15147.608604661002 14087.189109258099
19432.294795005557 22891.404172745715
8365.225450637898 10543.732972718914
18314.183460913566 19406.252188405673
6363.569140034545 9038.074186462512
9056.540478571274 7142.812891291497
14745.088566705865 16081.385046071126
19433.24985688189 22892.32674937172
18639.788771335367 17788.77668643912
6363.870834641445 9038.286563281781
8365.913927360238 10544.279207228914
9055.90450700536 7142.006510778326
11874.482112496527 10488.192217918206
15148.495814436495 14088.1430997843
11873.673670772665 10487.276910618886
19941.617211249442 21537.27784563314
11355.69094507243 13043.965079683401
11356.53626067385 13044.700993123606
14745.9999945748 16082.220742173638
7247.845307399987 4639.889653860316
7247.580410040306 4639.4759402329055
19942.54788135157 21538.258425415923
18638.861725974577 17787.80528901753
6878.043282794896 4292.8033963833
11651.788877249706 10338.587959678052
8091.034744703547 10224.225398532644
11652.612713035647 10339.516429698248
8091.746550652708 10224.788701973259
5998.891430922883 8663.43488461707
12889.080068026577 13976.849466170837
11155.248237488935 12787.083522054589
8763.61700669307 6922.658448890859
12134.82661598426 15873.733807771881
12135.723134613776 15874.58043540049
6878.322411751285 4293.250516799596
11156.108740954436 12787.834218506276
8762.959776239988 6921.826420822758
12889.924127007109 13977.810987418596
5998.5713799203895 8663.213318394048

7142.812891291497 10488.192217918206
7142.812891291497 7142.812891291497
4639.6827747163925 4639.4759402329055
4640.096577658702 4639.889653860316
7142.006510778326 10487.276910618886
7142.006510778326 7142.006510778326
12598.088267669822 17996.60823599825
12883.776503805086 9913.714994894699
11863.285993349398 14978.923459314425
12599.9168648051 17998.52841206747
11864.548242558585 14980.076935716987
14170.329036405612 14065.065410441573
11524.000085039916 8068.000061973227
14168.703116375895 14062.608150695232
10372.00009448515 13828.000036158519
12882.614119812795 9911.971953148375
5856.120606302056 10623.238912873983
5854.998586203455 10614.933348825136
7008.600824701034 3781.000132240146
5933.000569694899 9159.001364777712
7579.498502906084 6574.194399316162
7582.11598287561 6573.376681736716
11882.980745587362 10497.05492030979
9076.58360838482 7147.667171882026
9081.77443454747 7169.054679663142
8376.723087222115 10593.234916681495
11355.34651871091 13090.477034852473
7278.073690201275 4679.62391651295
13103.759765807674 14091.060180128392
12321.512447747638 16061.355173210011
6394.002768219608 9060.25965411588
11889.914976987851 10482.226147150232
13105.967042195365 14085.972099929773
8396.452774832953 10550.891763258687
6392.206936575192 9088.187167966998
12327.995263716735 16048.049102616804
11362.198808329309 13087.189499659582
7281.044609120315 4644.142655001028
9714.899608333582 12437.095480858865
11130.056373621834 13570.594128482364
14188.156109939022 12293.217682933951
19730.42671206074 21167.773619348824
20722.168226322265 24436.321899991413
21450.319927684064 22472.08403775671
17008.751366282006 15479.534876733216
10619.696012598477 7916.120325007699
16473.08629856591 18216.576187637456
16458.891646766497 18210.67115731872
20193.10206580455 18908.893172261563
9714.701982047623 12436.941143223281
11924.284250218123 9600.0
13522.821409750259 15598.35273354209
10619.876797778776 7916.362801185908
11928.145860945866 9599.400033335416
20709.032919101857 24434.59318261714
21436.76497152601 22473.02382858168
17023.90887193655 15478.66664154248
11125.917763492593 13571.01853215152
13522.25344533965 15571.288963987536
14181.525266345649 12293.99853587107
19731.652850179584 21205.246237664865
20183.859801336315 18909.80697944852
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
6988.8004120879 4224.000473484822
8832.000319328856 8832.000226449272
11115.769443115487 15447.799196001999
10675.20026978417 13440.000148809522
11114.191271748026 15446.084196326265
7560.665203042653 5709.915936333914
9620.917565176327 9629.475219346068
9622.422501424388 9631.4686315224
9342.504601134657 10441.167798670798
9340.931389439826 10438.630274130797
11393.08871641049 13976.987121694003
7558.989238813613 5706.55281233776
11394.200739850075 13978.360561954323
19304.472150255755 21145.54969727673
17674.836102493286 17664.31207265089
19303.758630121753 19304.472150255755
26515.074674607273 26514.780783555423
12663.851704753968 12667.888853317272
33931.26894178878 35013.34791190354
34937.92496700398 36372.99274186824
25613.387734737473 25616.283122264245
33879.40083590618 33879.40083590618
25650.42972349586 25650.27563204731
33931.26894178878 33931.26894178878
33024.198495194396 33024.19676540219
33259.866085118265 33259.866085118265
12667.888853317272 15323.107778776472
33233.47598807564 33233.419941378284
18099.927099300705 18100.685208024584
9986.703072085402 9984.770002358591
10651.996174426651 10652.768701140563
27789.21204352509 27786.47636891011
26514.780783555423 27886.704574043884
21027.298744727057 21019.885822715594
21019.885822715594 23318.542943331602
19221.688752552414 19235.216791084003
25344.25414665028 25344.256390748575
27786.47636891011 29575.80702195631
12520.7357311781 12521.15849272742
15152.097049583599 15152.849566995641
15152.849566995641 18217.25890467608
18064.082207518873 18071.08502553181
26446.08678046716 26443.21215359435
34937.92496700398 34937.92496700398
10741.785698849144 10741.436030624584
43487.47019544825 46653.86827477439
34918.63640038797 35321.73857555712
38723.1205354114 39086.97501726118
31884.53167463984 31574.515293191755
42533.92960993024 42865.478138007515
43265.13607975826 44241.733058278805
21701.888582851494 21290.367399366314
40627.85330287585 40409.50066506638
43265.09170348667 44241.733058278805
34405.58094263197 32750.49532449853
21701.9460878512 21290.367399366314
17167.671947911607 17004.311953148826
17167.753959094356 17003.837713880945
17986.48026296418 17487.817016426034
19838.106362818504 20539.513528805885
17065.93519998245 13706.164452537405
17066.267085979875 13706.164452537405
23574.59785447039 24167.60674953149
23574.544917399784 24167.60674953149
34405.58094263197 32750.413264568127
36819.9398161173 36578.89752302549
42533.95895046686 42865.478138007515
43487.47019544825 46654.02464954122
26864.757583123657 27852.576469691274
36819.97370993086 36578.89752302549
38723.1205354114 39086.97501726118
24370.473938764506 25104.321221654252
31884.591890127747 31574.515293191755
17986.378847964366 17487.817016426034
24370.473938764506 25104.321221654252
19838.28541135801 20539.15833231732
26864.757583123657 27852.576469691274
34918.672139701994 35321.73857555712
40627.85330287585 40409.50066506638
29557.01247166229 33532.21831313879
28332.539707022384 27041.92685442367
32115.312333060065 34663.37873029691
8136.814118560163 4687.317356441742
31664.533922916908 30848.333909629546
16589.61161557303 15615.097438056542
17135.10417972415 19390.217971956892
11824.574791509418 11809.967993182709
28324.675006961686 27025.01110083028
25786.621835362617 26116.22149163236
8127.376206378046 8136.814118560163
18201.255212553337 18919.875528131786
18184.766414845697 18937.184083173506
16587.348820377803 15583.576097930796
32107.417433515264 34664.375719173135
25786.174981179352 26117.17718284271
8142.147444010087 8135.209708421781
8135.209708421781 4686.498159607022
31669.486421826015 30865.269284423877
17137.655513517595 19394.17935876638
11839.442522771078 11841.650433955565
29549.0838140542 33533.19167630782
11254.723452844144 7258.006337831347
22952.001764552042 19493.427841198172
25568.699496845747 26997.53590607854
9334.824315433045 10869.341884401281
23354.54458986516 21320.425159925868
11223.644071334407 13253.56404896434
26143.06537038073 28272.65875364395
10094.36436829977 11269.271493756816
27205.119518208332 29348.37917159992
11867.33967829353 10066.734127809277
25791.682380178303 25791.682380178303
26560.03134410801 30267.612806430574
24393.069179584596 22329.030431256975
24018.7659966119 20597.76143176729
25310.118767007 24806.66749081787
24027.270794661636 23189.738441819478
10404.8670938172 12567.737783706341
12176.982918605085 12366.359569412496
26586.253241854145 27964.19196043397
12997.673638001534 13397.418258754184
24300.616309056855 23897.629694176783
26416.188975702004 28053.69023854081
24741.072662995535 24740.286841506102
11096.162581721665 9144.955385347705
10578.825690973455 6620.027870031969
12006.952652525952 15931.37282220211
25107.522200328727 24308.29191860259
11113.339057187088 15074.636745208822
25332.474671851545 26926.937776137856
27595.57993592452 31274.790359009603
10050.969704461357 15344.8952423925
9650.461263587353 12977.613224318253
11751.390579652927 11074.125563673188
10746.569649892936 7489.924498951908
10750.022863231501 7496.538467853013
9649.639771514789 12955.898463634237
11772.01068448188 11072.254061391475
10044.801447072567 15300.984445453174
7857.011024556348 10563.689932973231
11489.812685834158 11344.743496439221
10386.148508470307 8150.828730871481
9646.782263532228 11876.208696381182
9641.265531038962 11874.754481672453
8753.138760467584 6081.382161976009
10147.930911164984 14692.308361860638
11485.030455142709 11338.584832332472
7855.105420043706 10562.054440306583
10143.458346255591 14684.834149557155
10390.58664753824 8157.185789229028
8754.848898753193 6084.222218163962
5232.443505667309 8456.157342433973
8213.540257404233 10564.800613357547
10141.119344310842 15715.58525795333
9805.690592711968 15389.922546913613
8936.446336212175 7044.563080844688
6307.6682759954965 3080.8028174487245
10807.946896201476 13224.472352422988
9212.24041588147 7390.588203925314
11114.20087095784 13600.93662215952
8513.357034683791 10798.846095764122
13209.606201548931 18440.997803806604
9802.23465134354 6785.50926607576
13209.405945932785 18440.373125292233
12745.156105752492 10601.808147669906
14357.388821710507 15655.948901296273
11976.783943947557 14399.200012500694
11976.922449444182 14400.0
8779.985970376036 11874.544201778863
12744.862048684561 10601.808147669906
14357.840506148548 15655.948901296273
9802.043478785432 6785.50926607576
8780.174904863798 11874.544201778863
9731.961316327763 9800.555137337884
9214.679985761848 8700.91604372781
10154.148533700127 14015.00866928023
9784.125101407892 4354.772095069959
10707.24139601326 13040.32177517104
9402.8333466272 8448.588343622856
8770.900688577478 14260.264548738218
9713.064204976718 8756.54726476138
10752.000011625743 4224.0
10013.443785453856 13257.73555325343
10013.520465406315 13257.561804494822
9713.108671403816 8756.28420050423
6705.105757720919 11747.838311791664
8158.952397349934 8554.619921422576
6956.3802288898 12017.731607920025
8369.227396971732 8914.462911471448
6221.89551181953 9196.251899551251
6051.102210341517 9079.261699059016
7040.862021088043 4195.570283048539
7191.091294094381 4428.636923478826
26879.593779999315 27824.32777265248
7668.2576899840815 8244.829652576213
32760.16123281447 35321.73857555712
31106.78454042533 34879.23760634685
17607.671087089035 19386.256601004745
18793.415070178173 21207.438718525158
9418.886762245313 8136.814118560163
8917.072021689632 10593.111724134698
31199.198528808396 30836.37957024138
16299.160341563611 15593.42630726166
12744.254656903242 11828.470103948355
8609.576121970233 4686.498159607022
12378.098480784518 13634.675867067761
17921.10052598612 20538.57874829707
31581.89526365453 31574.515293191755
29997.20521982006 27013.070632566007
16298.084143849546 15592.441277747368
29998.18661186039 27014.065669572952
31105.8072623818 34878.30180785756
32514.267637454177 34664.375719173135
7667.4231003642935 8244.363953635235
17608.725110012932 19387.246942255624
31580.91242260813 31573.542357486593
31200.183137924047 30837.375763835676
17922.124985614846 20539.513528805885
32513.283454612825 34663.37873029691
12379.102287322776 13636.055734705693
8610.319390127175 4687.317356441742
18794.468453362664 21208.25348773444
32759.17955321836 35320.760141876905
12745.329648149553 11829.443942975511
16726.135468016644 17003.40865826614
9417.955604057603 8135.870266910602
26878.64138638294 27823.43071944939
28998.764197806773 27851.611389648537
16727.130908928895 17004.74098597212
8916.109128986702 10592.386747093406
28999.740757461954 27852.576469691274
13356.425869221152 12502.134217804574
13845.316897781719 17052.36734298203
13845.316897781719 17052.36734298203
13356.425869221152 12502.134217804574
14592.0 7296.0

42173.340856991636 41447.103638251974
41911.43742750897 42749.140634637326
38231.718078579725 39148.240126473116
34586.863795955825 35597.35362354904
26856.55646206341 23198.537906514714
29573.609857438776 30743.990632317073
14496.247238509697 13576.450198781713
45617.58550427675 46388.40959765704
42172.3848038026 41446.13083268449
27853.90385637173 26741.572148996776
45857.448250420566 45190.45564054428
21780.790068314785 20442.365420860668
49566.039583973215 48949.60675020791
37825.94918835481 36979.81806337073
12512.888371595105 9789.921399071598
46598.4276884961 45942.1939397761
13640.174487153747 11194.913175188096
12811.105582267286 15331.172949256035
11603.056605912083 14337.008927945884
49344.207636155224 50057.6793808902
21780.790068314785 22969.492114541845
38517.60272966115 37721.047718747155
53086.99226025147 53750.80636604441
13174.676314809409 17147.22321543637
13640.596725950078 11195.427638102978
12810.656003499587 15330.797272157766
54609.59389154986 56500.540183258425
30989.17919597097 32113.076230719475
52620.61162700411 54988.478211348964
50840.55588051728 51533.315049587094
12513.041804453464 9790.117466098147
52271.97796142786 55977.13819051488
11603.222069752866 14337.142811592552
14936.118211904994 17146.663378045305
31341.197807997065 30356.91685596546
34902.61594837842 34021.52731727369
41912.399433103325 42750.083789391574
54273.73818892522 57463.190870330196
29573.609857438776 28904.769433434336
15568.016476096112 19556.94211782609
37825.94918835481 38434.54446198107
25810.513653160797 24605.98171177082
16701.26417370853 16515.650789478444
25381.90619791981 26742.505492193508
27457.212299139184 28719.661296749306
46362.398667886024 47121.04039598447
51055.88678144764 50457.658447454734
53293.247227392705 52720.41275445404
26166.878625468496 25453.475695865192
15653.404742738878 13575.743110415724
13920.530219786888 10870.706922735062
11518.20056258789 14972.000133582687
13530.268585656384 18897.4413612002
12874.564680796007 16038.68314419859
13527.375059485857 18862.74436554766
12880.646257078874 16046.006387883559
12670.20045618853 9212.00005427703
15135.987905944194 14750.779301447094
13912.436688085952 10871.86833069643
15150.183900607353 14752.803801311804
7258.252709846908 4660.210832140538
18639.502287346626 17803.30511450051
11884.649490834805 10494.732869396914
11887.92577365791 10491.308640965626
19968.377547735043 21499.623554843933
8380.464438203888 10556.770576269999
19447.544500813234 22890.783822315916
6376.016424069186 9047.885112002694
9067.956340874167 7163.299588876624
19439.498224548446 22880.78617530438
18643.482638176803 17810.6940066916
11363.959961210703 13073.367316800977
8380.073340967847 10551.820506433949
14757.931250686865 16086.532503930111
18314.647874310882 19416.665264663756
15160.181373585212 14091.041267415265
18309.751330916537 19463.766387829462
11363.814628899929 13063.171016257882
6375.7653219045005 9052.29296918742
15171.970721036869 14080.404006987868
7262.10224659499 4640.338780735734
19946.726952337598 21533.552795579275
9069.510233744708 7160.50787304923
14768.220488603221 16087.187697046367
7584.0 6450.719107200374
6784.000008189203 5184.0
9984.0 13824.0
7584.0 6451.3142847019935
7344.000004255175 9984.0
8859.706273347892 8859.246581961695
8873.95886850959 14029.730040168271
8861.49267900166 8873.95886850959
8859.246581961695 14015.200676408454
4422.355848413829 4401.536663484697
4410.86797013921 4418.357273919799
11345.187176177395 10663.979041614813
12288.000010172525 6528.0
11677.629002118158 14425.577284809091
11677.70023496826 14425.404292427995
11345.145933393716 10664.213051135092
9272.599120227535 14392.409805171614
8774.815968440593 11884.492122089188
9272.247725815401 14388.226089410744
10844.491653471923 10587.370967336508
8783.769418649375 11864.384518381052
9803.955220215972 6786.895976807071
9800.585241708783 6776.201000560713
10845.626916975443 10592.369564927387
10898.420628696618 9384.270349899347
6128.737090135291 9071.813490146278
10307.134232171424 12277.805219174965
5941.209132828098 8947.671261283574
15204.53444288907 14952.76459388029
11474.412098229695 16564.705430523056
6922.1511858670065 4123.120420264245
13093.422969663052 23272.808726064846
12359.665120418467 14528.720797097038
10575.774524827957 9002.235833391615
7080.833239103997 4402.6794114493505
14664.88817720749 16905.464353279385
9960.391809562514 12013.194620915787
14745.088566705865 16081.385046071126
8365.913927360238 10544.279207228914
9055.90450700536 7142.006510778326
11355.69094507243 13043.965079683401
15805.902726513283 19405.361759060303
16428.938371057335 17788.77668643912
8365.225450637898 10543.732972718914
6363.569140034545 9038.074186462512
11356.53626067385 13044.700993123606
14745.9999945748 16082.220742173638
7247.580410040306 4639.4759402329055
15806.83396509244 19406.252188405673
15148.495814436495 14088.1430997843
6363.870834641445 9038.286563281781
7247.845307399987 4639.889653860316
15147.608604661002 14087.189109258099
16428.04239707215 17787.80528901753
11874.482112496527 10488.192217918206
11873.673670772665 10487.276910618886
9056.540478571274 7142.812891291497
7142.006510778326 10487.276910618886
7142.812891291497 7142.812891291497
4639.6827747163925 4639.4759402329055
7142.812891291497 10488.192217918206
7142.006510778326 7142.006510778326
4640.096577658702 4639.889653860316
7622.2203991028755 9294.416603531392
22508.480201915012 23195.6246305203
22508.480201915012 23196.270044987836
5349.5787684639245 7544.912192994694
19837.569245310777 19386.256601004745
7623.504906701379 9298.13486673537
22302.018124924132 22590.82149900707
18756.21115790713 18756.21115790713
15209.849736272874 15289.137058709362
4992.750306694698 2688.0016741066215
6297.443652983327 4689.038387558797
17607.78012697796 15592.441277747368
18777.092942199546 18753.447469732066
8609.99745128366 8137.805662462087
21465.35816146565 22589.971602461123
23484.0759664927 25933.507591531077
22343.606185240355 22344.708903899376
16143.073315279838 15291.773507347014
18837.742566454188 19432.03790136279
8612.7973259434 8135.870266910602
23483.1493841861 25932.61916968666
5348.573232648124 7543.640036481062
6299.287896262561 4688.955960552413
22343.926988110215 22343.763716079706
10652.283657090207 12061.02947513188
10650.581439527139 12056.252319854624
23557.61893740537 26003.524703393578
17605.260201933335 15590.47122443706
19836.654633846403 19384.275921478213
23558.26003761738 26004.484536325654
6071.573107523288 6071.573107523288
6071.573107523288 6071.573107523288
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
8145.870119269028 11195.427638102978
8145.870119269028 8145.870119269028
14318.137931181083 13824.0
25042.389986780414 22286.891573299315
24779.661350389757 26615.989649081246
29384.561695918223 27686.639666091658
16190.545420090084 19967.615405951707
31939.308461518074 34061.74723938864
25593.198963069568 26039.067283602923
31239.92216699651 31002.21000186922
34483.0432531701 35817.13779742876
16412.865350084365 19968.0
15715.98118335459 14347.424019662903
38199.12712353517 43880.2486889033
20078.821006613536 17123.558508674534
36513.51225231558 38854.36687169153
33642.690415023455 33689.391876375565
13614.572516700626 9235.978345578773
15903.382952269327 12493.285236478034
17928.598135691234 17990.718162430316
21091.36925379668 18126.60544613911
24839.207736962948 23352.14390586012
15113.848502468045 15810.397211961501
31109.805026711434 32584.897115074647
27859.841919149505 29505.75308308534
20604.5835920069 21477.528372696892
38548.36214581626 38798.25480611209
14448.184695663327 8993.03202485124
15686.310309027776 14347.156408152801
20210.707681820546 25697.272715212406
32114.990023097835 38140.89585995588
38993.15223215482 42593.83150175621
16130.78262825459 18827.547503591646
38277.36830360729 37225.04647411471
22149.579624961283 23984.893016230028
17654.432219700524 15813.602277786045
16130.346520766378 18827.75143239362
27218.22093370392 26865.93936567266
21687.99052102338 20665.882923311066
37943.827325139464 39169.58935194496
30824.861892995115 30223.30984521715
15667.20000510621 18432.0
39246.92285469652 40810.126194365046
29451.303825128016 28782.401307048724
23599.194649869918 23660.836777257056
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
8145.870119269028 8145.870119269028
6071.573107523288 6071.573107523288
18756.016667992168 18756.21115790713
7620.129546963096 9290.947206824501
18837.27374117603 19432.03790136279
23557.30920542497 26003.524703393578
15213.888757024322 15295.038443887612
6299.775492031442 4688.955960552413
8608.857621981882 8132.094994526318
22344.981017992483 22344.708903899376
8613.119998648057 8135.870266910602
22509.446905688288 23196.270044987836
16143.180390647934 15290.342376807655
18779.313649864842 18759.077829147147
22343.763716079706 22343.763716079706
22508.480201915012 23195.27678213821
7623.479672203501 9299.37481769608
23558.26003761738 26004.484536325654
17609.81576028299 15593.42630726166
6294.623424995335 4683.222074597787
4991.500225383146 2688.000744047516
5347.496096305261 7538.600665906107
10652.303793598412 12060.807808766376
22303.90250108213 22590.82149900707
10650.14066678099 12060.870656797542
5347.9992988032445 7548.01702435812
23484.0759664927 25933.507591531077
23483.1493841861 25932.61916968666
19838.6628975468 19387.246942255624
17607.45302421676 15592.441277747368
21465.35816146565 22589.971602461123
19837.380497434635 19386.256601004745

8145.870119269028 8145.870119269028
6071.415012169733 6071.256953877014
8145.1630431809035 11194.570157000224
6071.731239934785 6071.573107523288
8145.1630431809035 8145.1630431809035
8145.870119269028 11195.427638102978
16586.165503816726 14300.895076882425
18227.69761775865 19271.81413359936
11332.003573949312 8452.015144330966
13430.439168173169 10237.112874243401
12227.208716628666 15334.128863420967
16967.30880251786 22372.085910795176
15752.733635785251 18293.31211126077
12242.067393316376 15335.255622258144
18208.20565020068 19221.01644034467
16562.807974495146 14274.28852867981
15780.385962326776 18295.201146748837
16995.004576508814 22402.377039055475
13420.920592958591 10218.529884479469
28593.872862031123 32955.087634536794
16264.413795495708 14963.857925013857
30743.507717529206 29730.312628695985
27949.773790140054 28597.475692794986
31268.71541972903 33521.57706612265
20532.525187187766 21435.500390707002
8413.869457627685 8421.047975163186
34232.33524388893 36590.125238922046
27524.04014675171 25973.727668550004
8421.047975163186 6203.33853662687
25049.133415749136 25651.7122430453
31618.411408544864 35829.82802079854
33741.10008250735 32773.128276073985
16941.998059556023 18575.607661662107
14276.586741935202 14272.929937472543
19569.676606934514 21527.840602345605
30520.476671408655 28993.90722203546
18980.924883799642 17851.352021625702
10881.216889668178 7907.5771890004335
17637.791324667043 19094.163113370538
11518.738787297852 11515.051454509441
10881.553565553037 10881.216889668178
19028.219175740014 19087.64587370585
43836.16690270971 51742.041716577056
33350.94302348219 34150.98803841552
38108.41435903625 36787.57447834798
30553.621018015197 33355.76779209257
38032.98826334844 36697.329957368835
42794.66066321825 44210.38730886668
18166.184425790594 18240.1421047096
29602.269659950198 29362.144063402455
22624.929841051442 26785.83076927053
42933.21545656696 44295.728417083286
26585.767668058787 30236.664581266235
16969.629341856587 13775.435528505079
24065.681176729653 28014.963323195694
41255.50875918987 46077.86293872579
22602.67175579029 26767.011506703544
33377.60690905216 38958.5515259487
44005.42475776267 52015.22427136117
23441.46056968294 21277.375049568498
19703.046217273106 17033.052104658167
30660.386920666868 33430.02366137362
32893.26306829409 31367.42440813399
27988.416578291813 26173.461062687144
21549.7394027522 21611.850082767094
42312.66397297381 56689.06014391137
19594.591548690165 16969.896905992093
42803.192518929005 42158.3105211772
19080.5080367053 19149.669031082496
29692.237579020206 29442.522718000917
38645.34330000848 39060.51656084441
42935.45607362288 42251.20537925516
32968.89519774662 31429.955711072835
41140.008322381575 56184.1777104551
21474.675228828804 21419.338014980764
23985.60706444596 27960.94320655153
33464.33816458034 39132.345086897105
28064.92505887019 26243.357178531867
26694.476193587318 30307.603171481576
25116.877527564888 25175.176344963307
38750.32751092669 39141.70440846949
23555.627061065472 21352.76740846488
41414.37883003379 46218.772333327935
15936.198798960811 12480.207690579513
33254.01227295738 34097.610972031456
16905.206394480963 13725.478825891649
25019.060572666902 25075.45511052591
10671.55621266177 9872.609381516115
11904.0 4608.0
11162.45134367895 14393.598577145327
11162.45134367895 14393.598577145327
10671.55621266177 9872.609381516115
15391.900124560465 19423.675887946647
13454.937151841326 13755.969794965384
11566.731911439423 8194.118134369312
15396.077653451579 19413.74080387394
13457.804589159408 13741.937709071453
11561.170764435774 8217.628915934329
32201.67441686845 31734.198367061363
28944.825731726214 28050.482723119043
21917.68792368392 20726.283217209977
31952.19211572189 31657.10902783133
32262.760667507806 36708.10805530571
31331.152530349085 33206.85027219534
31967.12428982487 36055.74302382354
44908.765976761766 44192.8781705831
19327.993724960146 22710.50331894914
52943.13119281858 54810.43785630616
13813.791410783102 18236.14874363554
15236.631987450102 20106.29903786373
53778.34650674935 55704.70780822748
18906.348669164017 19812.982738598446
28866.924609317146 27958.929825728308
44134.96384953771 43404.79260404316
28933.416856990953 31855.27227948303
38071.35313624931 41146.263220370325
15401.17033144316 19705.62795244039
13054.37504119019 18126.66138592543
11318.491408310561 8750.16371275418
13120.92816229096 10983.027815679972
26138.56185830445 26253.31491450175
35254.239313875434 37736.243440491
19851.667402338302 19772.516278916046
15717.178979702432 13997.951743022977
50631.12209896202 51756.337244824426
25885.011394588168 26166.168099284238
45919.98375193286 47168.54622521241
14106.532955351155 14699.296751885786
28096.859769487586 31223.730478595924
51444.89032504157 52545.38841801438
25421.661674249382 24371.516427994382
35617.03556558294 38502.177860479525
53796.861181671185 58074.015712709246
12088.145147293724 12496.096070373338
15662.19428943467 13930.038370370701
25339.05738815081 24310.689521278495
23647.21518044193 27289.22104055006
22226.995524711736 22869.02818223809
18727.021111751863 17300.836627169218
18662.994427475995 17229.72779819809
29834.552386829084 29594.808750860346
13168.218822604673 11027.054910537083
20226.553835938663 23254.41914991643
12797.501907060789 13110.55014101239
22335.975780368866 22959.861497840095
21989.650383760083 20792.58069600789
49741.08326569139 49090.95594913589
45135.80190811822 46410.38630522267
11724.672709243909 13110.396637783313
23430.811073509598 26684.733800433536
10668.469108545985 7871.091728597756
11339.174659559663 8801.436530476147
38639.916039796204 41902.18544419849
52950.867927258754 57188.128715669656
16786.92860410098 17033.82355785101
31119.24347268905 33123.82177527225
29021.456959080773 29673.748566704544
16573.828305309475 16976.987070737847
13532.621600742736 14644.457825402755
50567.957312687424 49871.63667857713
5968.283940966616 8937.100256794705
6929.584137594405 4207.332290181036
6835.803334080218 12090.05248127567
8212.446279208705 9164.631198253424
8207.598918075859 9163.22634228796
5965.856709643636 8934.846165435642
6831.77705855349 12082.952826192777
6931.541894845619 4210.392024503181
22678.726595644654 28222.811217169703
32316.748495478318 31597.659359515856
16531.9426396295 18287.119209979464
26455.371154455574 27598.154376697003
15692.589662640134 17555.500391615158
20972.851306391316 22400.22040070142
17066.86015645526 15642.256390943092
12378.395104374396 10334.365824761575
11607.799489998093 14123.585451293875
34272.254294756334 37303.414347751066
9025.796474550043 5934.124788037407
7611.113584752234 10946.089073271787
32037.489984703858 32988.92876405659
7966.551379361084 11184.119142784559
11701.68820982682 9539.094401461807
21397.376356927503 20293.687737816406
26792.874644576685 25919.119988919378
8711.979178120206 5474.414123904036
16255.460239562583 14774.386823147686
20609.455029791545 23206.957168056306
33832.4543366934 38488.986294783084
21146.908311263847 21184.615762387573
24075.673903109935 36420.42048082367
10906.788627272466 13448.110127449136
5697.184085142414 5711.485708640091
20946.854383415186 21517.27420004681
16879.283526263785 17724.222634575544
20169.345404736257 20541.171144800872
4229.523170524072 4220.026658683568
17411.63420317002 15936.925926915768
14076.122264316973 12275.655135266712
10675.055727150924 8798.565905873525
23498.16647693555 27530.533757993144
17232.842496814043 15931.640530717481
10646.495850226445 8749.859484586024
13587.516039548951 14497.284745772224
5728.191184833132 5719.217428984493
22824.713888921175 27528.143162952347
14764.682764116538 14540.456285825421
20119.51305256224 22200.324164299946
23656.041276783588 27262.124733776713
12901.966056036232 12301.190592784098
21091.182650576993 22215.59744863955
23318.836336985412 26259.674978948235
15409.448144726015 17697.968301474608
11297.789720117824 14000.345210029644
13096.416297598362 15472.716148110518
6996.2370514441545 4182.231461791659
14407.691452831714 14554.52798959829
9623.740261717374 9405.283249323224
14383.815049121946 14531.178135306167
14889.993270649924 20804.81453894747
15429.479092389996 17713.475661202123
7909.868077281694 5736.085947752178
12850.965941321298 12303.22904769313
11668.065624011977 11703.275652568387
10332.225001421524 8711.563407333955
9643.686789326217 9667.928113096415
10671.94491177686 13408.03583676595
10414.791673384541 8754.763332038165
14081.373371506694 17387.985651017774
12819.961215327447 12291.060369227709
15677.466157673567 20806.32716266857
14098.50634326598 17444.15412108022
7990.169525110215 5726.945870182466
13168.133878420284 15538.915438343824
11730.786637758996 11707.849717176934
8828.589207264375 8857.001411312973
11365.884182059923 13967.388875520006
6878.322411751285 4293.250516799596
6878.043282794896 4292.8033963833
5998.891430922883 8663.43488461707
5998.5713799203895 8663.213318394048
7616.386610460369 6921.826420822758
6255.795472999417 10224.225398532644
6256.3068978431675 10224.788701973259
7616.806679967662 6922.658448890859
37549.32086956601 37546.383740648045
26004.947294937938 26497.685653656623
39727.68525247853 43005.68376389335
18015.277878172677 19012.146222875523
40596.841298307925 43806.66073783757
32769.77499350583 33153.8947485812
22145.52372125999 23382.370110833504
12108.985339821003 8893.38591313792
42389.757454263054 42394.55961559219
32109.42585154124 32104.74108289927
28400.082757636905 28087.69128995831
15057.89385804004 12615.223581054757
13995.301835973385 11331.906326827804
15913.383575233143 15898.301921903483
33133.713455649835 34347.51359268965
29755.27255903565 30179.637671781282
37657.303890231575 37643.61526208661
32714.247157440823 32719.454595087613
20766.10226125741 24430.75897306508
38860.36036580206 40799.3631445394
22109.18532286129 21689.679619579445
12527.375019532223 9456.997885164192
38465.47870899958 38464.53021941123
24546.82625233861 24522.737408372665
25087.059969013684 26923.51947647261
39597.433121352704 42885.044537694026
38069.00468331324 38057.178521272435
18864.947865287093 16979.23464117273
26358.310211392538 29144.30649372189
37414.17229076604 37405.566764854666
29997.159306841037 32207.37525785049
34120.668038595024 36701.195430121894
31687.9025497113 31114.06108176816
39891.54156904822 45342.125931632276
39537.789932193 39459.254136387324
23333.774376212696 21837.393479992064
24859.21560288307 24493.847901054665
35066.79471603086 35056.81721149255
41699.008717234516 49249.48431202098
31950.561527000194 31950.026744902734
40214.16724339819 43456.2618847963
37243.06120906581 39197.28357935024
33176.28613487539 33170.257309825014
28486.190090794677 29334.779988948274
17357.356201694427 15399.808440367042
14649.097393802971 14624.534214804928
40106.81142469755 40109.051846185546
41276.973027494394 44692.07197031706
27500.310854208994 27962.53810010815
44336.28647191823 47290.19492452955
43460.50988564216 45225.50652010434
20468.89061058574 20007.973935408852
20214.373358609217 19735.918220341307
14287.685231192105 14264.252521600984
21396.89527310271 20938.006877446573
32041.399404173622 34157.61349977484
16868.341421506146 16841.307847076485
44866.738292414346 49841.05171442513
42156.92182927971 45254.186723440296
26936.339502264407 27415.227830532433
20342.84376168927 20316.631142982344
26201.17591886383 26690.44297122099
10671.55621266177 9872.609381516115
11904.0 4608.0
11162.45134367895 14393.598577145327
11162.45134367895 14393.598577145327
10671.55621266177 9872.609381516115

11417.140797940612 13845.316897781719
9232.625004840173 10332.38326815261
11995.77529799554 17411.102693396533
5762.949266651582 3257.641017669074
9079.883699695718 7285.887729027946
11996.54350219262 17411.76429888712
11416.4008776847 13844.484858599832
4096.000030517578 7680.0
9079.122479623236 7284.93905259337
9232.0660309597 10331.714330158378
5763.324046286136 3258.348047707611
9216.0 13056.0
6576.000004752129 9216.0
6816.0 5851.408121127768
6816.0 5852.0642511852175
6016.000009234634 4416.0
5998.27175109631 5998.27175109631
8956.342110482381 12631.20706821007
5997.951671195759 5997.631615896395
9026.042322081146 8956.342110482381
8955.48463233565 12630.26464489165
9025.170192301084 8955.48463233565
4608.000027126736 4608.0
9713.108671403816 8756.28420050423
10013.520465406315 13257.561804494822
10013.443785453856 13257.73555325343
10752.000011625743 4224.0
9713.064204976718 8756.54726476138
7705.9562028342725 11703.472347982884
7180.28661266387 9630.67100466006
7706.620530427069 11704.128502370435
8912.675075419276 8764.08677501541
8913.249463579486 8764.962977674235
6988.800011446887 4224.0
7974.266451530198 5708.570398970306
7973.9775394717535 5707.897774137165
7179.965752007456 9630.272322213947
6067.200013185653 8832.0
7142.812891291497 10488.192217918206
7142.812891291497 10488.192217918206
4639.889653860316 4639.889653860316
7142.812891291497 7142.812891291497
7142.812891291497 7142.812891291497
4639.889653860316 4639.889653860316
21552.426162021475 22153.779474392173
50913.65921287179 51930.025929128904
22973.64736667047 26087.41974592351
29576.379469959138 29325.06767255619
50096.82447465552 49553.93172090384
30907.314139415284 32885.20719107605
10574.121782551127 11926.721678650843
30709.73855310396 32570.763116635753
36982.1064646472 38166.277222176126
15059.997463479202 13511.497474373446
21861.23348405676 22447.282463585652
12115.624564998703 10093.871903288647
19347.852714796787 19237.39899258733
21270.55565329688 20200.638925538966
18205.190250035837 16924.542091294523
50547.357861492404 51573.38942710669
10315.117744359488 7833.438580853239
28344.94292814858 27536.099142761672
49717.133149001624 49127.09098857778
25071.393414008726 24186.536626809553
22869.10784723346 26402.829715770997
31808.150437427197 31602.871657493404
11994.252809441283 16988.86061512072
19316.739538707094 22181.622348241348
28663.53291972223 27877.065717180492
9507.45278400056 6732.022355874941
17920.091216285702 16623.35639995726
12634.306076364068 17063.615355486658
10193.245812791918 7670.971841950666
15924.849124329343 16280.980437307822
13006.446502109826 13618.60583907178
10922.645613773324 11362.212680635757
28237.566085783306 31097.50552697113
35109.43211617072 37722.84396754836
18066.38419905261 18949.44392323954
31671.500936370223 31268.061804339584
24769.503491995958 23832.33610034904
14163.350454998672 18947.74300543471
28413.182223319433 29024.890352936734
12325.199178917961 10343.681549622455
15811.405772093634 16049.910280123064
52929.66762128778 54925.23012241278
44472.7599323451 43852.275151923415
18769.18533851709 21970.844544532192
44957.80334812733 46171.715075357555
53267.107416303355 57447.537849763416
21576.268009088133 20486.62834631409
37846.54227353537 40795.50948327524
45375.42521992371 46535.569277704126
25556.771462605302 25824.85835391939
38066.37660882632 41244.024876338146
27786.50820598461 30723.771594646383
25451.185979743852 25542.717651025312
14804.054668907434 13209.521755158285
11801.778145167578 12035.830050312275
31672.582796920397 35644.47571503893
14528.0688431911 18818.31071058186
12738.061208877554 13793.810387271531
53294.520961352115 55254.22544023217
31615.54834869844 36032.79940554161
44060.20982070381 43410.74507538427
52917.95734200253 57143.234498932594
19511.854280012558 22836.501417686555
17849.03112527711 17850.192716046513
24586.35727898706 26423.553281116452
26113.686332819594 26115.647187079245
17001.651638721585 16844.23892611358
28521.055302277222 31514.622955066432
28305.988257787434 30146.49724263169
18606.889963666687 19435.29883999729
11521.551165099256 9594.40003335279
23393.936203213005 26553.915812926727
19454.412921622694 22498.768788535963
19954.255066275964 18902.699595560418
19957.901449050198 18912.75233803901
19579.40150547253 21843.81514296438
10165.589730187816 7913.697050051891
27048.566772464015 27052.419041557077
12873.131407012912 12874.32425411136
26007.516528880646 26113.50011009631
17851.58373615318 17849.913305111597
17004.54155430902 17004.628105312975
24168.072832653506 24169.00502710031
14487.768423359372 14486.779214166274
16840.28728311301 16843.554969186283
20795.36902774269 22473.280245660622
22388.71160317181 24388.976936312847
19668.15918912822 19670.39765739371
17004.240481747816 17004.74098597212
11526.16558097271 9599.802133377541
13846.413055372861 12288.376296321658
19580.43107288499 21844.342448332016
16739.376638632635 15472.340870081684
20676.990351596145 22831.052976155086
14490.948826384312 14491.125042590724
20254.06001823393 19671.178536122334
21587.984880998556 21588.299145602
23677.042197500563 31152.7957814383
16743.79207348204 15481.892681452096
19200.000006510418 21504.000023251487
21607.30193337428 22796.34499212538
27153.60751355149 28828.146246333636
23360.035685974453 22468.581174609135
10163.823812916082 7911.028504562476
13851.279110609245 12295.405686678256
19430.187100946245 19431.840365750228
27250.763846582762 29559.011959130163
22795.300587816095 22796.580883983457
12286.33358768098 12288.000040690104
12871.59022054212 12870.924286934485
4374.4128875897295 8955.827655778108
6085.050533890413 5151.900620159516
6084.966401806268 5151.006212382198
4374.529917602576 8956.342110482381
4454.40001795977 7680.0
5529.600014467593 2304.0
4135.806571879299 8307.190138669032
5591.124394967438 5151.900620159516
4193.411983397291 6912.0
5310.511845622793 2304.0
5151.900620159516 6515.9890270011965
7205.615587859235 5760.0
7205.54453952726 5759.2000312543405
6681.60001197318 3456.0
5606.400014269406 8832.0
5468.16239700322 9961.821520183947
5468.068773443793 9961.35899363134
16516.418316329968 18726.19395392454
6569.955802743272 4288.0672802557565
10145.098789289557 10146.145080768361
14205.865212807154 14207.0273104545
13786.523517349993 13785.11225924548
25521.302210114594 27344.192381564317
18208.625846620667 18208.64698433137
13615.699863678612 13616.244893508636
17042.569084501316 19191.298262493863
20092.095209034047 20094.92366245764
10978.286650373899 10975.29156788101
12580.946387295353 11556.079092841135
21204.377201417636 22967.636556685582
24069.052707205206 24071.732903968506
13461.098041104307 13461.867961022348
16772.7125746288 20095.821854305934
8905.327096431913 8907.072470795329
13910.342060855297 12990.246687418989
25475.408519241108 28361.313386371938
20992.884196529285 20991.646552855258
23947.438636522278 25518.776714411684
16438.427029372368 17213.785405889084
16727.02645089344 16728.51078249346
15871.782711606294 15872.984123976184
10670.514233156713 9437.101302836587
7214.706512568616 5223.263730657299
9228.763310975095 9228.617935530758
17397.015038505888 16668.560495735677
23120.276911067576 30399.12446107618
23608.09840158434 23607.006947090944
23680.29918401464 24191.135773253805
18849.58251527073 20812.581026869302
21014.13171683522 20404.57431557934
19353.96950383966 18725.66068260343
24805.88029300938 27203.976492417427
7983.915236273491 6243.204385569961
9508.92906693493 8103.525405649075
15616.509333963777 15447.799196001999
19555.243753274975 18914.76259433356
15785.737494650037 18084.8560956398
22636.53812754945 25407.19520135979
15114.140902552886 15112.406161826117
15988.03603479802 15195.723214115214
20853.769401237754 22185.764084204988
15971.436662445241 18246.63062047347
12491.985079330754 12491.748476494393
17734.57282576888 20812.027772420446
20463.49679307034 22670.605638138564
7142.812891291497 10488.192217918206
4639.889653860316 4639.889653860316
7142.812891291497 10488.192217918206
7142.812891291497 7142.812891291497
7142.812891291497 7142.812891291497
4639.889653860316 4639.889653860316
6893.995430807885 9973.274738018601
9002.847827215564 9139.725871162658
7506.718242866038 12597.485820591346
6903.677698154803 9979.532854798364
7904.517252811837 4969.417370275916
7491.833487204584 12581.958869746793
7912.825275462615 4983.05970263251
9014.902606240403 9162.869692405322
12472.102194898822 9961.821520183947
25897.764074577943 32301.248087341766
15150.427327306646 17210.817092747224
13854.984167439528 15874.048286432797
16551.798614081526 15508.420454707823
23242.92855902629 28553.82790450345
14582.938723470657 11212.975564050785
24818.109519842335 24591.744956387294
21633.174170241407 22811.668593068767
13626.89798018977 15112.328245508697
11541.168939929785 13747.34330698117
18079.48318951623 19838.348318345455
26066.05609432505 30092.593108603985
18638.46779324953 17056.690417545837
22102.4908071466 20438.75847501506
11620.750187487896 14208.0
20461.135585407876 23731.23106794083
15813.551759171625 13912.32910047775
12390.75395456225 8864.332180147583
24204.272019624965 26047.68550178691
16378.533596686175 19426.18768569891
20600.132297984022 20647.812474933027
24703.06453548718 27231.3537122193
11260.020839789773 13424.504944317314
14576.794188023647 12221.821795460774
8857.138194699233 12787.083522054589
6878.043282794896 4292.8033963833
8091.034744703547 10224.225398532644
8857.93294171953 12787.834218506276
5998.5713799203895 8663.213318394048
8091.746550652708 10224.788701973259
5998.891430922883 8663.43488461707
8763.61700669307 6922.658448890859
6878.322411751285 4293.250516799596
9865.255445248238 10338.587959678052
9865.968984342086 10339.516429698248
8762.959776239988 6921.826420822758
64010.85131743458 64956.171562061754
23530.213982837577 23005.878227096655
57075.37837320437 60263.7683853242
49200.37926890484 49554.77616738875
43506.389533952366 46652.00768455737
47993.75603430096 50862.44568441435
27599.282072014572 27153.02119470318
42086.76553851373 43394.40923667471
37898.33080123714 37292.579771316436
41157.04369394138 41485.47583191014
63361.03771326699 63294.444068970224
22164.739341575845 23551.008492206867
63243.44630868878 66221.79600403481
43725.90627169722 43714.184757353076
55225.84839728585 54798.962946391606
59760.909197588764 59401.495982845416
28035.316861605334 28659.224727825418
39143.567185426524 38558.64235161814
50035.45746008524 52796.17993756745
55915.140398894866 55715.79009580677
31928.001268479053 31333.573367874913
23157.054207109773 24168.874632468927
30995.27451936608 32111.857311591306
60594.156382278314 62892.77851232207
48591.63766616638 48128.16390638646
17781.449702305632 17091.81187001542
10839.248008459299 10787.00560860149
8075.332876265845 5368.011270479972
36103.05510791296 36008.816531510725
18554.11965204763 18544.545828895352
58647.02240523384 59158.487336983184
43231.43949488612 42704.806158089516
45331.573322354474 48360.4050437959
50600.036053761614 51308.599522887
65099.74892856731 68385.0310594358
54368.679853673566 54355.64368122228
67532.68317044718 70916.84302054062
44933.67421701262 44945.41370373622
53968.72694588969 53548.92271558785
30450.650964859084 31255.733761983578
22676.96863077713 22156.460118890835
67982.0649591575 74061.15195566432
20129.484882644785 19518.60594407295
16878.777582942566 16207.014931812706

23211.719789324638 23201.745559332383
33034.93305036315 34216.7243464362
49834.322365614644 49375.01324556785
34615.72095515126 35085.176641995124
47473.120234679394 48496.80019341482
27388.346476558236 26547.58484307
33256.604557638246 33244.41855409717
61206.3924911261 64403.76327513789
38459.23250826776 38443.761483496906
50242.2141799416 50253.28260919877
22278.454282108534 21239.93187371372
15231.91333370682 14451.582335509147
61867.405613295276 65077.697592954224
17376.370066271033 16021.960554189365
10203.539029180023 7657.541707362749
37795.43415863879 41379.505748619085
35006.041234049866 39172.01640201842
36023.63748693521 37426.67584758229
45824.372246277766 46169.79689147441
34683.49990240316 38556.49181396046
63711.28539026661 65891.47942640232
12811.674317297486 11029.563545308582
40615.9656494909 40327.52955488348
57101.93560560141 56859.91039387945
39259.10797769202 40297.06234950632
26624.356085230025 26184.513361909172
52662.09939078481 53327.43580934677
34451.758143861465 34464.93506449708
66266.47354190503 68374.84558666294
41747.978110659744 41448.41615791851
12085.15152793398 12090.570292587525
24289.685969974995 25432.835960623815
57967.47935185869 58269.09668941162
31817.784984604612 32078.310444909657
33848.22976818729 33171.24159569551
36830.85968251522 36494.21600747165
52987.65034317548 53576.72838089314
48048.59553764943 48288.11730643472
55660.73166243443 56637.06577851646
62330.469539508726 62354.335374535105
59721.12172553568 59708.52502783836
32608.193444593035 31906.191781533566
49034.18320560285 49024.390266478586
64462.435321045705 68254.56658715225
50743.96155224407 50524.47463358723
23461.574532839863 22471.824781267766
65394.87822027383 71500.13609077958
28154.75939617048 28141.793688391648
39664.93224361571 39677.06365143469
59356.54816412424 58973.264798550874
24330.110524628224 24341.206625802264
55591.98831118226 55591.607460119376
46782.09801051707 46512.71225159849
36641.43086289071 40326.20861177009
51904.87228409415 51656.315209275235
44138.36316699142 44834.080128848414
31029.818494675408 30653.348870881953
15334.341754090718 15342.342357019674
33331.832157251476 32846.82365161052
25046.21190552229 25943.544958235758
19589.264129236708 19596.981655346826
29321.450751220513 29336.216746540445
34601.45105374471 35449.82528870911
61481.89749739349 64473.950654508524
28607.4096932945 27804.912030071235
32083.848770886652 31701.425866985857
38030.97651103264 39047.71482430182
61133.38041796908 60950.535165821144
58185.19978998095 60509.68072135235
55158.67264537826 57673.221420343776
39203.899082429365 39300.477007283254
33980.01306179855 37911.27564458891
41189.61873919203 44500.98578683398
13904.661556470908 12159.092235853794
44084.09650443395 43799.760284732154
35725.88307625334 35400.824510172075
19984.45641687003 18853.18673328199
57733.39111328903 60984.1823754324
39655.11369647047 43083.0368126482
52897.30365604659 55568.72988471124
54414.43283669118 54411.06352572057
59208.767162304604 62138.386026674365
45635.58944302681 45383.668703620686
18495.58315490485 17219.109878271873
26903.35668458416 27966.905173794257
44475.550491927585 43961.22988497933
14285.916636892784 11145.185911414846
14629.403836964786 17701.52535800234
13441.899941145886 13241.106638042003
19123.5340324138 23119.861591281206
14636.700059268824 17698.517452035354
18531.98957478662 20776.850579430946
17565.82240416582 17112.2642569591
19072.34389272855 19933.60057791868
18944.821365283442 19911.99919646443
18527.776834795914 20761.597361474862
15021.946049098993 14801.561674363958
14203.180671948097 13245.449784737399
15693.646903285418 11726.155380174698
12482.740884917863 12676.000355001574
17222.088477301466 16572.169441566784
12082.676078770373 7892.72886902876
16414.530666455255 18902.395747629453
12507.93062483259 8168.466196294136
17691.721631253917 15889.94553168764
16420.559020934703 18920.468202452073
17423.599674942405 17125.981198167887
19126.54471902567 23117.121144294764
16113.581966948119 14814.312842653215
8609.823872246812 4691.824058934862
32762.875496703582 35319.00986720891
29004.2639979452 27859.511715031906
31201.797095039256 30837.812000853755
17609.79127897003 19384.414615871174
12741.91401163891 11833.699210306133
16727.898687521993 16997.085897294277
17612.045250023886 19390.815067964522
30000.924611677478 27025.608540789603
18794.000744918576 21189.780201785954
12380.325722694051 13629.833197805467
31105.079249840994 34875.36128845119
31581.6699742289 31570.21046809793
12376.23123410354 13635.662396818132
9418.650404383847 8119.876969511299
12745.386380961543 11828.989644090487
17921.609381205137 20540.000024342746
32513.99862965011 34675.42014165077
16300.710636042835 15597.76217923584
7671.390609849617 8237.657191216444
8604.86996479965 4689.544327543988
32513.03474164033 34657.55197644519
8915.177299414745 10598.041753078725
31583.615478511078 31574.698129990094
29995.569569151005 27010.18506045451
28996.62894415487 27842.925780169007
17917.745819438336 20552.05889929279
32759.029408889695 35317.52160047474
31107.222334835504 34878.521255924825
26875.460139213326 27810.0969613556
7664.617827683546 8239.427164554585
9417.976863424543 8136.53126338245
16296.345535119215 15600.493902437833
16726.23807741066 17000.698838577195
26882.584280740404 27828.813143934112
18794.195005077734 21202.005801338702
31198.305980934285 30842.880231910898
8913.477871179128 10594.525473092224
6067.200013185653 8832.0
6988.800011446887 4224.0
7183.09767440204 9630.272322213947
7706.620530427069 11704.128502370435
7974.266451530198 5708.570398970306
8917.807011193328 8764.08677501541
8913.249463579486 8764.962977674235
7705.9562028342725 11718.17362049223
7180.28661266387 9630.67100466006
7977.1674195794585 5707.897774137165
8176.946168344268 10697.002196877404
8601.157189587922 12595.526864724636
8601.752379602658 12596.136550545965
9000.756468208658 6606.004617013222
9878.416067366266 9374.634712883484
9877.897802670364 9373.815498504331
7219.20001108156 9984.0
8176.664417719489 10696.643258518066
8140.800009827044 5376.0
9001.01242305553 6606.585805088737
35545.3517776938 37221.33067207566
16041.862335903572 15812.632829481623
19992.319375200066 23998.0817983438
16127.135715929224 18824.977981394826
30032.6046988935 28782.401307048724
24706.675248125284 23352.14390586012
18654.417434386058 17994.175085288018
19446.28310911882 21731.44277308803
29855.73178172363 29498.726752183728
32075.963447901468 35826.40258245307
33792.38544859067 33686.19801936692
19907.03011552472 17123.558508674534
31611.556383702464 32591.705463200295
16628.064335070692 12493.285236478034
17447.870839732852 19967.615405951707
15272.638123454637 13822.000325567931
17445.061271316878 19962.00202885472
17277.69431955549 15813.602277786045
19446.041161120687 21735.362545860604
27211.780996472833 26868.168843447445
18445.208481846323 17994.81694822151
30049.793382426622 30228.089006749997
28867.91996178457 26869.886583311065
28397.712998682757 24814.839431275796
31110.410299447998 32595.14703142172
20299.207496845782 18126.60544613911
14482.9606653009 9235.978345578773
22924.51057274724 23658.076358825117
21722.033077039545 20664.023252987303
17026.80100194984 14347.156408152801
16130.291296811722 18827.547503591646
15666.000103408656 18430.000244167117
17824.057258751873 13348.416572762479
21939.91879747963 23992.44683228453
34483.59199445441 35824.51095269829
34054.34246905965 34320.34127161325
28851.535146548096 28416.0
15713.30580184266 14344.426792312059
31381.337654727213 30225.545768438988
19919.703778545503 20661.867727773304
23599.61222139042 26614.661842676116
35494.58551666719 39167.117649885855
31613.23143183088 33682.597420626575
18673.580755709387 17249.043103894197
10450.612998288667 13060.65086433291
19906.318594858265 20740.003085824264
12390.988339918653 14659.53208666634
15078.099085760115 16991.596776053746
10442.306143759626 13053.887696774475
18183.859657399473 19799.445472032796
11304.78486305688 8753.397511823623
18692.48927350234 17269.51142910534
12376.725537879558 14647.47841780284
15060.517090724343 16975.99670122494
19125.016732018823 22908.795712564202
19104.99536770423 22889.511659273117
10636.80610897839 7872.007685463728
11312.45840832133 8763.480187687994
18164.42168195839 19781.595082298092
15687.749208857209 13961.817396026923
13126.042634396705 11005.447060433302
15670.851228953708 13942.827833692849
19925.534798343557 20761.283799418572
9715.206688485841 12480.004847755468
13112.579389273491 10989.38615210149
6300.65253069077 8235.934251801675
17985.909577013335 17466.605451546675
7303.642234453225 6365.941328664599
4990.752504632944 7306.005543386892
21741.661862782144 24153.470144060044
9096.088567193166 10590.586622090394
20655.828835679506 21277.09270553663
16986.7463829893 16995.48943102257
7290.460921261731 6356.7778787684565
20557.045453512474 20996.80928141226
20547.70110147497 20995.98592588593
16987.61695471145 16986.427081643746
20652.15420025502 21277.09270553663
13448.91934526918 13637.186696676115
13457.95745605138 13627.862084714536
9097.493018531106 10605.074492901971
17979.54711783642 17485.37986433237
21718.498111568908 24246.164892617555
6302.976479410343 8253.214949339439
5351.409277003582 3292.149753580478
15794.17503033599 13714.402137898684
20532.106050984858 20554.283738432725
20535.151272337338 20535.591055530884
15799.451653635186 13714.402137898684
5353.294155237502 3303.180437093923
21721.989033133123 24247.035798216657
21735.06862704193 24164.89124742754
13862.14528999088 13875.087963685131
36708.88548877676 36747.82367705603
35816.18890337859 39002.841499049784
41796.495273647044 44442.73984578359
28118.800704555306 28153.54231708685
36033.802797685676 36039.2823041747
22435.952704422918 22960.211954596587
26597.974907875974 24585.91371090365
38566.09773414988 41443.00912096032
26974.126739525786 30610.52580404329
18242.960913117997 17962.005344615616
30074.515729434446 28892.856729648593
41565.1865122725 43922.68309199701
32404.13206772402 32387.10360621956
35171.14590569946 34182.537193719254
23169.341414895676 21635.253754000667
12973.948743539879 9982.4141368709
25648.876147135787 26280.249998810894
21866.717093636278 22840.534078694396
43223.09422345883 46273.523196316055
43212.72721827014 42980.22504594409
40365.469540189915 39511.5382135396
35985.1565354043 36012.46169036491
46011.71530647868 52115.87322495902
18510.20760452189 16702.36884396941
11865.911040139312 9380.16503053118
45359.25805433771 48793.928075120166
30700.07568195152 31046.47846374851
15119.212150135876 15089.02395783107
42223.54107077657 44849.09030292588
32234.259129699647 32279.99264250226
25408.6387836893 29196.74737021232
42696.394452251145 47919.6277635793
11526.013881650499 8007.02753835654
26753.029844112985 29383.349877098764
36302.47884119795 37416.059439764635
34172.83873780462 37173.16684115035
31514.850942155033 32343.74012077144
27336.487844202846 27906.559264803676
40088.886781828325 40077.077787683076
24060.70706989146 24592.48179830576
20981.856633238578 20172.52031849268
44379.53741309163 46693.305440930184
28031.04447286972 26777.997404585727
20436.28273439179 18686.260460562997
37673.09057775855 40245.46230322122
20865.633502111657 21850.106269764456
41414.92373676968 41094.73078145178
24419.690958322957 24408.739828184494
29072.731292075914 29065.655471707498
25123.860382512874 23717.98764650998
31091.46136481848 29366.526335268187
13993.920298472476 14708.933136023155
16227.07386314612 13957.668358289646
39052.11776280513 41640.88285567442
30050.2615662493 33347.60100816849
32868.40436582761 34373.0083059368
33612.58701858029 33960.03901646758
34217.31807725439 37023.31542420263
32128.395073517135 32040.172487051314

22022.88355741985 23181.192398148978
15959.708648969754 13850.64099599726
34130.43917743287 37866.34327473409
35473.943127315295 40700.41966614104
29249.905496097115 28912.42058354852
33662.29722701646 35751.24769850697
12892.627257467733 10166.939362463021
33074.529994655204 32283.94077556208
20305.56708830802 23839.986598150594
34958.9144139231 38118.694639244924
21474.894648402817 19956.92000284613
33159.42377424554 34616.902489968685
23079.653398610648 27218.68771634665
16545.976237139956 19286.606881460513
13989.621204307141 11526.398223209191
18013.946623226253 21498.56183562054
31916.156175203807 30729.842189637096
23847.76139514986 25825.90637325242
32789.8575104491 34132.82666290619
18525.827921040396 16742.576145862382
12777.351176202366 10166.750562495374
26709.897510099134 25280.443053870713
27433.22319519803 27860.992103656325
14873.794857714953 15687.704229746301
21784.20127064566 20005.839172601583
15826.282456567675 16084.118906548782
29883.97840315108 31495.82958107311
16457.15325663889 20036.193375988365
33268.96580746025 32885.517800393536
13908.33010487321 14717.64332357596
13337.252916590849 11025.642883750588
21336.39186929224 23438.143804491003
15927.312924658698 15090.447342607176
34825.025498913856 35846.15127178928
25606.744210883833 25670.6225869183
18388.93505767954 19101.195800263395
26761.550771956394 28536.665537515066
22615.62750379978 22619.49636928285
33835.77280039574 36275.347014191335
16920.127037927105 17466.724478275828
24229.859285600483 23360.96436365588
14716.022393232657 14717.773744693863
32653.115134700394 30481.47398010798
16878.123367246728 19299.64188786932
19743.767463507596 19841.290683823972
26912.24790355169 29210.356793438863
17728.904764222996 17721.214518198238
28117.315679132673 31797.273924033172
19505.68074305534 21787.087299591014
19240.810669569568 19239.799791058118
20662.047551005202 22964.058286809846
23709.457569712555 22836.434332005512
24583.764561189564 26483.040327726725
18450.619549971154 21504.471162993057
26578.394419113418 26769.79320054602
24827.231843280475 26648.73402246343
25780.056420182205 25774.614643094086
20539.017383080914 22703.577603540813
11334.202938451384 9367.91737794479
16431.01142656775 15140.128004742892
10242.744886625851 8015.763032924564
26912.765972907728 28665.377252009086
17107.225896938664 17106.305299508716
14118.802233192446 12597.662362517896
14284.614606087363 14286.325349788167
12990.394921718978 12989.035876461347
22588.110423406382 24575.984720861135
13581.654685641217 11989.373461528337
19622.433309862463 19622.433309862463
16578.062485639803 16578.9810302081
16963.34572034001 16959.337369130906
19368.111125134415 19367.94599331586
26746.77290515624 27346.017790530306
14695.56320420857 14694.35309906496
10097.129406420421 7826.996614283157
20290.77629121173 19264.333287191643
19971.070813665563 19970.019554321923
21828.199398942645 21828.199398942645
24643.80312573528 26451.397335490616
21363.271491172778 21349.444957656393
22209.477730520815 24211.896993007384
24441.601604641215 24441.601604641215
12758.900567621195 12760.900908634938
12289.433502222777 12289.969283932323
23119.78440883719 23118.583023187213
30447.491969782997 34127.291366295096
23012.83405515279 22114.40806352275
11720.85086501829 9835.200913046972
29736.011543245 31236.532586060188
27424.037581107565 29083.022968735557
29004.384831818483 29844.3365649163
19622.120094424048 18555.089544381077
16083.787987908818 17048.53920428375
23929.45651052044 23893.138178146462
17052.45815124611 15816.517220930782
22475.028930892266 22469.16224517505
25659.677256132607 25748.64850822272
24745.30954908425 26284.209955789047
17253.23054850888 17975.00178025026
5150.126988725618 9488.726468815506
5155.034917437514 5146.545248999566
2292.000872600183 2311.0008654260605
5146.545248999566 9503.275487956771
5150.119149107135 5150.126988725618
7584.0 6450.719107200374
7584.0 6451.3142847019935
7344.000004255175 9984.0
6784.000008189203 5184.0
9984.0 13824.0
18673.580755709387 17249.043103894197
15687.749208857209 13961.817396026923
18183.859657399473 19799.445472032796
19104.99536770423 22889.511659273117
19906.318594858265 20740.003085824264
10442.306143759626 13053.887696774475
13126.042634396705 11005.447060433302
19125.016732018823 22908.795712564202
13112.579389273491 10989.38615210149
10450.612998288667 13060.65086433291
12390.988339918653 14659.53208666634
10636.80610897839 7872.007685463728
18692.48927350234 17269.51142910534
18164.42168195839 19781.595082298092
15060.517090724343 16975.99670122494
12376.725537879558 14647.47841780284
19925.534798343557 20761.283799418572
15078.099085760115 16991.596776053746
11304.78486305688 8753.397511823623
11312.45840832133 8763.480187687994
15670.851228953708 13942.827833692849
9715.206688485841 12480.004847755468
10207.343539089885 15520.56471266429
9060.150833457465 5705.836047416715
10096.311051072069 11704.784705410006
10323.349035681202 13079.247570101272
8106.481083830394 9632.143686635909
9066.588005556445 5711.064436687788
10673.84835005632 8775.885881208802
10330.65562416055 13043.148584601802
8108.335637632424 9650.487915126365
6539.757645547731 8841.004580928573
10205.075627475771 15513.341355104645
10674.632818041096 8748.31966722753
10088.862106303168 11718.892652465078
9097.938435589558 10596.737280880376
21738.90751624837 24167.60674953149
15807.117767357562 13705.18387326489
13456.84672491211 13637.887006424418
17986.005297522293 17486.828900632612
5346.708239655499 3303.2929025443686
20537.95556470453 20533.904937931315
15802.609759853663 13706.164452537405
9092.450995804767 10593.800498404715
13452.359813636993 13633.211837274443
21715.212824193088 24243.75416473282
20658.255516862988 21289.375401828962
20657.295176280946 21290.367399366314
20554.078616609837 20982.58937786278
20538.8747913425 20538.57874829707
6296.742515976019 8239.712191575625
21716.12638110213 24242.883017496082
16984.92785265807 17005.98371162339
16983.700690956608 16995.708752505732
20549.449606038386 20983.41287779469
5349.758522587726 3302.711764595875
7295.135380664447 6356.33101718279
21739.8495164985 24166.653409191767
4992.001408503407 7296.006853066957
17982.776203912454 17487.817016426034
7298.96492661802 6355.424848112044
6300.050361901879 8247.159571634345
5352.468174823649 3302.711764595875
15810.559003400227 13705.18387326489
16987.3332621692 17003.837713880945
21717.03994562795 24243.75416473282
13454.501584558562 13647.885257430911
13451.107381096093 13617.247776257873
20659.215861208286 21290.367399366314
7298.330410290958 6356.33101718279
17987.681168302377 17487.817016426034
21739.8495164985 24166.653409191767
15801.381486720991 13706.164452537405
6298.9524922799665 8269.37022995101
5360.169796750845 3303.2929025443686
20555.483888463656 20983.41287779469
20540.174118189832 20539.513528805885
4999.508100803518 7312.008274065341
9105.072700911778 10598.345531261
7303.554690088321 6355.424848112044
20658.255516862988 21289.375401828962
21716.12638110213 24242.883017496082
9094.362802185637 10576.799374101789
17985.658314334785 17486.828900632612
6301.214768796569 8252.968496244246
16981.436336187817 17008.39971896239
20538.57874829707 20538.57874829707
20553.36237699321 20982.58937786278
21740.791521929463 24167.60674953149
19440.7929907993 20544.71379698437
9971.455786393479 9971.531978587844
24371.560493511464 24168.281300084207
28114.18252808042 28918.173611070255
17158.493993095988 17012.60218191209
19431.88031446148 20532.25961748974
28273.506171856367 31585.036093061535
9963.077850242866 9948.72906455895
3307.827837116073 3306.9419408269023
28275.51232073435 31579.100319673453
26857.01517501733 25100.13011918464
3310.965493628709 3302.711764595875
14708.093350261277 13700.088795332678
18791.740107025747 17514.892092159746
27338.683181985925 27840.460664292175
17176.354952213944 16999.75073346665
26858.842973756127 25101.33847028879
17001.83756081808 17476.97599700818
6355.1616226497335 6366.178209883855
14692.356656136248 13694.403236359005
28117.544088265524 28906.688637753028
6346.152948834436 6354.579215022817
27334.891042630847 27855.197647835852
24362.447014935824 24165.652691371695
14592.0 7296.0
13356.425869221152 12502.134217804574
13356.425869221152 12502.134217804574
13845.316897781719 17052.36734298203
13845.316897781719 17052.36734298203
23265.09753342977 21091.584672565503
9900.60771670103 8720.796809925112
24016.959526319915 23127.964458637514
25331.918143717423 26429.783351363287
23616.575747369687 23619.108133035
8202.45341346112 4256.593238729771
25333.88234712117 28860.276921748344
25080.104338698435 27296.35537942749
11149.684963162761 12411.897719527018
26181.48961079182 28410.535299427218
9397.016606940264 13118.125628305288
7210.067228843601 7996.772661517895
8963.32436989759 7589.035577726593
24722.844548678557 24719.569090095403
24243.704497456656 23773.88163510536
8175.778481452257 8502.435533422173
21955.51786883855 18820.63752905305
8429.438522226732 10203.548010373646
23118.362472285968 22615.919791155964
24246.611086912744 25424.13548186054
23074.613236195313 19969.967876789386
10166.532944475768 11276.218204699659
24431.68398253019 26430.37390957608
22954.234179727664 22081.3343120383
9433.161126578938 11011.460620644293
26411.204499437565 29903.543552562463
25557.01927499023 27588.03111858474
9051.911928181557 5199.832689616081
22162.09105657677 20011.2341698357
10447.918117979294 14121.413137501502
11362.407007320237 11377.791174037253
11365.971889812152 11373.671350975463
7927.532481800375 7932.247222571924
11373.671350975463 16176.128646867272
11377.791174037253 16180.489145881838
7933.872730262315 7921.84101077521

7148.500157375672 10042.000049790879
6184.000143740116 11415.119272263431
8622.106619759466 5046.324801278649
8621.890171244355 5047.9382920158605
6184.000143740116 11416.546106419402
9786.977899229158 11733.181367387107
18161.656709795076 19677.159347832705
7993.501005191655 5688.815781865326
7189.959404614187 9662.463712739107
17623.464522555652 21153.678285347916
7984.431253383049 5710.130383800356
16535.85195023226 17689.732219567373
17605.250359543945 21141.08161849814
9793.023627052065 11730.81041531232
13473.960797033662 12260.49003914607
13017.859301743893 14518.208326098644
18177.748635198044 19693.056085838987
10393.885144641536 8776.084149550983
10388.35936998716 8772.236031936212
7001.606581349741 4222.02321168418
13028.716203832211 14539.224532278191
13487.559120908423 12265.636958592897
16514.23534530134 17711.005759131807
16877.370529795215 15912.551680984418
16885.299685821392 15957.679279895307
7191.559613880706 9626.48482053548
6072.014785884501 8870.001409244533
14482.014084331486 13977.810987418596
17451.709830271648 21411.228456116198
16759.79121476458 17701.52535800234
33385.777151355935 33103.06307579406
23753.823875208902 24869.744510147266
24788.4153587921 28515.71692944086
13413.321338435348 8364.680029744115
30922.033702846908 32386.9147187564
31389.698937708847 30053.65029409905
24733.346600515353 23212.81027794782
16121.310420479764 13103.135540778016
35332.80648192114 38998.150276647735
34315.21022811896 35636.825223355685
35391.573096572014 37078.149373991146
23634.24482976914 23432.736438580963
16700.49869598044 15479.534876733216
27648.770015318947 29269.652286967812
15282.800047111785 18048.0
15247.183146040088 15475.318058120809
13940.306690767353 13440.0
21667.52341547137 23695.7537546287
18330.643718617437 17700.984435900733
24538.9089284752 26354.158400525714
14597.8709968269 13974.514982638932
35004.016375267565 34225.688612502745
21453.644334937595 20410.351540333646
28790.310595059582 27561.58834319967
40350.445648096626 42681.90661158426
29423.868663077614 29805.17861043614
20052.413427456184 17946.7479226739
27240.705163515053 26669.5334979823
24546.979040199632 22130.64899635797
35805.812265608496 37672.1418557533
14374.30596585449 10887.874769669239
14872.030367438065 18451.781079342993
19198.595829187612 21406.334249469244
41947.716028408504 47860.79013137999
17104.344542834726 19614.094524091597
35160.813276288136 34993.547290893504
36077.640096868636 41728.98158354694
15758.22966706603 18451.989161063368
13327.98056838507 9362.358730576392
34512.622416379134 33532.849207903586
7705.9562028342725 11703.472347982884
7179.965752007456 9630.272322213947
8912.675075419276 8764.08677501541
7180.28661266387 9630.67100466006
7706.620530427069 11704.128502370435
7973.9775394717535 5707.897774137165
6988.800011446887 4224.0
6067.200013185653 8832.0
8913.249463579486 8764.962977674235
7974.266451530198 5708.570398970306
10473.710815656503 11751.283589463748
8837.359210335404 7277.995946687522
5978.379158359823 8580.688667001035
8474.465286310924 13843.930547355401
8476.070007838407 13836.444196396702
5123.555046303299 3268.2487665414947
5124.5334970609765 3257.641017669074
5976.197694930188 8580.243819379493
10480.868201155856 11740.88467705905
8838.975746657528 7285.89047406012
47341.181533628835 49386.18313860669
32253.373926345335 32340.460850148687
38421.22263801609 40914.52022204342
26622.076937091973 30376.281075865754
24063.355687019215 24623.36557012465
36472.40044540529 36480.0
31268.16983771196 29766.745690451284
41291.657268751034 42651.666696625114
15619.543129041898 12342.095000444617
26554.76028135069 23734.345261666687
45766.750693052265 46071.53964216955
32746.178479327937 32435.510617223215
36428.27754643362 35147.97446510965
34888.119041874415 32785.329051269255
18400.643124375434 17841.819105685383
18107.091566565847 15369.693197978937
26072.335319261296 26603.720886372266
23980.546569621336 25486.1468252853
42863.846362639924 42626.9805287684
27508.86217657866 28615.086370654204
27248.15648002631 30663.759146588665
38200.060469585645 40988.25715982567
36463.657921278274 36845.48337313544
26357.782247374304 24557.95978903785
44983.69513901676 47948.835533305704
48723.584894791966 54046.52111838467
15569.323827464199 11609.463208951567
43660.74151276458 49237.42576536674
18027.063535695437 17343.09188120734
28746.45489447351 32002.59809765451
42448.69263334267 44972.44357381529
31250.824453124435 34269.835788926684
34497.82077990579 37366.57415391462
40974.61786276963 41314.77465749995
40902.14804586215 40908.167204117075
28810.102898115445 29291.8644848702
47724.2380301666 51035.4594865178
42726.00272667688 44981.317510717716
32351.701485393314 32781.45641975048
42737.091940842205 45540.84584194721
43676.72823140488 46185.36163114889
25694.589367759465 19855.577176199135
24410.444719230843 24977.14565357699
28095.31001786597 27732.590737253526
41745.605337568166 40633.191715640554
34543.08308475085 37296.54414285591
23931.900990101058 23505.021357148347
20554.331052116486 20055.689192845006
21866.003864446746 19659.16653879304
39494.654532987115 37665.29139672226
37704.55098525906 37435.054547843254
30531.22693898822 28110.44462472979
22312.77367090181 22590.09079220356
17604.31524118763 15591.580099528079
23519.453076124028 26004.366594862488
8132.649541354896 8136.53126338245
7621.943112651787 9289.453428485445
18107.485976799762 19433.263158821268
22331.416122310242 22344.348390588613
22513.23885085297 23191.14011858839
18783.788382538813 18778.12677026119
6293.668986568963 4683.3066310033555
21440.538064610224 22618.538524847267
19832.546717769255 19384.573583135636
4968.725654028405 2681.002983959548
5301.5891780201155 7546.388871506689
23484.085119265106 25937.520332522152
8608.339554692815 8124.263412765492
22349.03585417302 22347.940621005775
17620.981388989407 15599.386558451586
10654.006758023012 12069.819551260905
10641.69799003482 12067.048230615472
7663.640310746584 9295.12479744086
5344.643492554017 7541.418964624629
15226.202036110135 15296.569876936463
19762.464000406097 18754.900932822864
22508.290719446268 23178.87402355861
6323.898505866457 4684.126599484689
16143.745315523904 15286.729669880344
23558.370527031126 26000.925848900075
19844.924984111178 19402.753850935696
23497.034994985122 25833.63576812215
9904.762490842473 9127.575800835619
10396.405532682918 13636.055734705693
10396.405532682918 13636.055734705693
11136.0 3840.0
9904.762490842473 9127.575800835619
21012.53578224199 20002.124687142612
22114.22141971089 21078.003724261936
9045.895478060755 5168.9040424445875
10428.729596647907 14125.17755640615
24210.102631844507 28341.274512625576
8955.43655217321 7595.535530823353
23065.7717191513 19956.8526827253
25552.663755467842 27586.271386325483
24432.665347849383 26440.98636586767
10171.974046368778 11269.271493756816
25820.83633424758 28407.897511079555
24236.362203103006 23767.489749655935
9416.83590384796 11017.1067436056
8154.31180419292 8527.827449004817
20388.37510347502 20741.63040843222
23104.735022164707 27308.80942113735
8191.249965664581 4228.361384744686
9387.951427228412 13153.051052892633
24633.691023564545 24716.388105870163
21465.485234673826 21679.31366533544
23116.32158973395 22624.24893781007
24705.541483642897 27297.106659864156
8426.06607142384 10183.24270554326
23516.91230677285 23619.121744891363
11139.740795907237 12390.091565440507
21953.119504981518 18816.979566338483
7194.522360796442 7992.82878585548
9893.333757637009 8681.6109680174
10779.393674970777 14014.684869807099
10288.13685756561 9499.63536142309
10288.13685756561 9499.63536142309
10779.393674970777 14014.684869807099
11520.0 4224.0
16834.28768608756 16899.021066322155
40234.49334355094 44778.454294448355
42066.049966213846 43388.44078784118
32115.924331672068 37415.617127076766
40393.353108992516 44924.40007390193
20319.116425487107 24471.249171221316
14756.032562989281 11663.233213821972
29003.61241509409 31607.702162605874
19627.49217764902 19686.920785130416
32245.44619873565 32943.248079082914
41346.34936825297 55630.55356546437
37713.58989888425 38088.44436308734
43041.36961110787 51401.30358269136
21850.237355690213 25755.625502014118
17876.1338661356 15408.91592552831
15839.116913257403 15913.158391720985
13609.136710313407 10153.099723729694
31832.881451731635 30539.91028146612
20298.590308196282 24454.023902008437
24689.76344180924 28196.815511685003
22051.351024370368 20103.248742429667
16875.857341788836 16947.68804291606
26811.24020555558 25242.855028700695
42120.11635786397 41622.30933045402
42872.79092138613 51126.78598347445
19555.57000145055 19603.067948665586
23493.63641586411 23543.16822349957
37184.8209085374 36063.68580719392
37612.548471086026 38005.36604217883
14803.5410169324 11708.286381875017
24766.941726826102 28285.024871829264
21910.03551457642 25804.81420200502
21973.95823423718 20002.353986468694
26745.694580623625 25147.032150931846
41992.31180004859 41528.548349298224
41930.004303362526 43301.83007679929
40148.0366006935 55117.7801167645
37112.675270855914 35996.86747482342
28903.058635722275 31513.86623377081
17799.879156893174 15340.58046489767
32155.29747136888 32887.95627581623
28332.372566823735 28059.613147725326
32201.37342818093 37596.255478438274
28237.464841473808 28010.444480586164
23406.83299372041 23470.358028798793
31903.588985567127 30579.689893784078
16995.39265690852 20984.773241567324
5358.971782207852 3306.803290188275
5004.751055247403 7321.001092746811
7312.920073404331 6365.0945790302285
9102.043903553873 10619.035031489444

6314.382491582213 8263.711635820795
17014.920684178604 17494.2970421792
15814.163233563064 13723.816524567792
6311.948213507459 8252.002181289095
15821.722795644671 13710.090006998495
16991.158345445434 17015.444895741046
18176.216159830652 20554.01364697416
7309.550411771043 6360.566326986929
9115.486919401386 10603.833363458707
13472.227935852168 13640.111619777897
13461.093900571379 13673.088349016107
17013.88856199546 17483.407276615162
16998.965410871333 17013.676998227045
17004.60799496713 20994.651223585497
18175.08734504459 20539.776240261235
5365.733547242166 3320.737869811467
18331.915039078704 19414.429298848834
8374.367952269591 10511.946061505452
11888.377251753074 10493.66632783795
23149.711666070965 26465.202209694147
14747.89324751166 16089.834927680271
9050.828315684703 7183.641486043133
6367.799233644227 9054.395010159431
6366.570056160538 9014.64253312354
23542.30306160475 25268.385346119765
22228.75098695381 21556.89395529885
15168.597119048287 14093.000035478606
14770.154317406437 16069.094871833946
7247.2202257141325 4628.688151085576
22263.236941648895 21542.965301926288
21964.040015443425 22873.307259773344
18652.39458836318 17819.723033762337
7249.928785857141 4666.646440432358
23576.83503403759 25310.281231151897
8361.906780154872 10546.173998185313
18643.509980687653 17795.73460130264
23111.710706431444 26433.309762494744
21979.234609057705 22953.92711498405
15150.329298071378 14093.405301771463
11342.104615987282 13058.624812743492
18316.342111895596 19421.074249381778
11357.496942548563 13109.857703270467
11872.462061426011 10445.4020985312
9060.51774458833 7096.648363840497
10442.306143759626 13053.887696774475
19125.016732018823 22916.11921770351
18693.769152313827 17269.51142910534
12390.988339918653 14659.53208666634
13112.579389273491 10989.38615210149
15078.099085760115 16991.596776053746
10450.612998288667 13060.65086433291
19906.318594858265 20740.003085824264
11312.45840832133 8763.480187687994
19927.916421163776 20761.283799418572
11304.78486305688 8753.397511823623
12376.725537879558 14647.47841780284
18185.39831843119 19799.445472032796
9715.206688485841 12480.004847755468
18164.42168195839 19781.595082298092
19104.99536770423 22889.511659273117
15670.851228953708 13942.827833692849
13126.042634396705 11005.447060433302
15060.517090724343 16975.99670122494
18673.580755709387 17249.043103894197
10636.80610897839 7872.007685463728
15687.749208857209 13961.817396026923
13131.019800457236 13240.171637860289
11359.754858270491 13526.918976618437
13131.702098357242 13241.0416508672
12054.447146178045 16022.51216257925
12055.643153312061 10079.542846776336
12053.703870595129 16021.79318927816
9209.667844173318 11779.151794590305
11360.430865068456 13527.486684524956
12055.006131893919 10078.78092826707
9209.917993120243 11779.47774733668
10054.706569562335 7573.1568714770465
9292.800008608814 6528.0
10054.935695468172 7573.663842553352
8371.200009556576 11136.0
9474.35535772458 12470.643327431028
9452.435041946717 12532.553211536746
10148.53591657437 2744.2494420150656
8843.568938075849 8350.011377237757
8860.567490290901 8284.304255639094
8145.870119269028 11195.427638102978
8145.870119269028 8145.870119269028
8145.870119269028 8145.870119269028
6071.573107523288 6071.573107523288
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
7637.214151770265 6606.585805088737
5990.400013354701 9216.0
7065.600011322464 3840.0
5910.117887525125 10668.89314783872
5910.21894687498 10669.39698389745
7637.135945133126 6605.772097188942
9000.756468208658 6606.004617013222
8601.752379602658 12596.136550545965
8601.157189587922 12595.526864724636
9001.01242305553 6606.585805088737
9877.897802670364 9373.815498504331
8176.946168344268 10697.002196877404
9878.416067366266 9374.634712883484
7219.20001108156 9984.0
8176.664417719489 10696.643258518066
8140.800009827044 5376.0
7217.259313617601 10915.330869927855
6439.965236707416 8756.54726476138
7216.78051488335 10914.697659578116
8756.371876778901 6250.32999128846
8756.634976468478 6251.067108902287
6439.786351269738 8756.28420050423
10406.701452002508 13877.230847687157
8906.891195024222 9484.100379055464
7613.674722351736 4241.328211775174
10593.953500831396 13445.45607259196
7350.892946514125 5457.6654349639275
9038.371543591245 8840.300503942159
9127.575800835619 8832.0
7732.090014995945 4224.0
10446.713550203242 13977.810987418596
10679.37376441147 13440.0
8964.570262985282 9630.67100466006
7407.429783669907 5708.570398970306
8562.165717724562 13161.260122039987
9816.400002037406 6559.000076231132
10338.190869027543 8515.646892632409
8562.377168624245 13160.847427122617
10338.015740191368 8516.284694630634
8730.600002290794 11988.000041708376
7616.806679967662 6922.658448890859
7616.386610460369 6921.826420822758
6256.3068978431675 10224.788701973259
6878.322411751285 4293.250516799596
6878.043282794896 4292.8033963833
5998.891430922883 8663.43488461707
6255.795472999417 10224.225398532644
5998.5713799203895 8663.213318394048
18236.298967718205 19847.616708310346
19854.558469026702 20682.656018993304
12429.566365726521 14692.15467519996
15625.37776311344 13891.698960170423
9715.477270829262 12480.213499776355
10473.618287869767 13079.066059929508
18622.655832077227 17193.899499531803
13076.419626182083 10946.214870904007
11283.939170342952 8726.46205515156
19977.37482753928 20818.66741652789
18112.065233981462 19733.529740013568
15125.566436996665 17033.73267959786
10419.735121393443 13035.841207992678
10637.05324796299 7872.338470873823
15013.195097646603 16934.028345317012
13162.466457317183 11048.863878245582
12338.409420991022 14615.11669471031
19179.02064757218 22960.812899372704
15733.3773627915 14013.066509511757
18743.505628350318 17324.718554712512
19051.058238323665 22837.562829689163
11333.714450258572 8790.901717116396
11162.45134367895 14393.598577145327
11904.0 4608.0
11162.45134367895 14393.598577145327
10671.55621266177 9872.609381516115
10671.55621266177 9872.609381516115
8452.000340747745 11908.000167954315
8293.775256178576 13228.798433720274
10171.24515484707 8426.06361238746
9604.000299875048 6148.000325309035
10170.427200685546 8422.64524956382
8292.772120614702 13226.621375090466
9235.499371447111 11526.398223209191
12587.002210216695 11002.789464494901
15713.249970645793 14475.323001577546
12011.529820967851 13850.64099599726
8364.013450491337 5708.2341402573875
15255.280057737386 16741.773412634637
16971.95050664478 18096.954881968402
15712.394650084372 14474.394529651317
12586.239535302035 11001.916969328573
12010.730603922477 13849.947906039213
15256.161005967391 16742.576145862382
8364.242990253213 5708.570398970306
9971.89578966808 7878.290233293008
16262.046119723065 19956.92000284613
7470.2600222482215 10166.939362463021
9234.8757241232 11525.898533303163
16261.14095013016 19956.054144043606
9972.473346166436 7879.021259014346
16971.08320055028 18096.000027630416
7470.003012047586 10166.750562495374
14594.245441268966 12596.136550545965
19385.877845483294 21186.223448269397
20237.754840890826 24114.8930124104
21149.83349816258 21639.821094454546
9984.000012520031 9984.0
19756.524415999895 21185.49846003157
17514.14696752314 15244.364729302431
21150.620227312484 21640.70830633785
20428.037228280155 18318.819203212854
17219.895499102193 15243.609054288949
16726.054406225037 18591.311519094073
20238.57702507763 24115.689167013246
10697.002196877404 10697.002196877404
10696.82271751757 10696.643258518066
12595.526864724636 12595.526864724636
19961.50048067529 18319.6576387224
7436.143691457287 12117.257528005253
7575.000168976896 10833.000738484236
9203.341675717576 7660.820452144796
7437.1172506556595 12119.498545731998
8661.000279413458 5403.00009254118
9202.358013031226 7659.4027182281
7142.812891291497 10488.192217918206
7142.812891291497 7142.812891291497
4640.096577658702 4639.889653860316
7142.006510778326 10487.276910618886
7142.006510778326 7142.006510778326
4639.6827747163925 4639.4759402329055
13301.51963123011 12262.476095797292
6988.803917695788 4224.005800185411
10822.48622082745 11698.880630214157
21298.12200641174 22406.499615067052
16517.375442848057 18734.66370127844
11553.952743541926 8757.954098989101
12662.561845850942 14509.664641196914
12675.182878365109 14521.568544754386
7577.215385614955 9633.464226331045
7569.86395188183 9627.483991157815
11565.163595902999 8771.097137758765
20279.114896858788 23923.085607839137
13313.578219246696 12276.559167779871
10834.45397793539 11708.722944881734
21287.773603643946 22397.63282134967
16528.79255723176 18746.965861173376
7296.003685427919 8832.002774003187
20268.378943566255 23914.78111963394
39200.95204360476 39809.816879759695
42750.96519158954 44448.23534179957
27713.033055064745 28809.66507962215
35032.83731015802 33056.69676480092
27658.48654170683 28811.317932368176
22565.88943793264 21811.567802429974
19029.236034652047 18135.99760145551
37402.15371138405 37017.87526317522
41160.41403536291 40815.47805673725
20785.61844912246 21817.008044184244
39279.42366637398 39774.09489856432
43044.84921059081 43492.85625249278
25246.73402200328 25532.430299522995
37333.83353106134 36840.0782979624
35529.721392800144 36079.78364680143
43987.974518611336 47231.024390754006
36465.82236121928 36116.18252252029
40064.13238097139 40638.41666453062
19107.09227616803 18295.696761807132
43807.86793995395 44619.346880025034
42967.893275095536 43493.827424129966
20863.793286756365 21818.697417582014
8206.550447660698 8206.906603587006
22646.75407895136 21974.87383353998
43903.95387946284 47232.0
25300.139165185985 25700.24824782827
18220.65435158683 18529.78243261372
18115.524588349934 18531.73019445297
11268.747800887195 11269.258893112714
32606.682304228518 32420.532814869035
24450.8077333347 25264.830931553846
35077.74645143429 33229.03363024571
24370.038328344912 25261.68482108824
6099.314387699654 6098.985571388082
11120.229156811472 11118.68706277859
6044.603419580147 6044.928121987887
32563.226925134088 32423.387253647637
15908.077532429172 14700.58638286242
8083.878802901489 8084.575251675255
15807.021621910799 14540.522721002846
10570.448696247478 13439.200013393654
8572.146058018378 5005.903814497438
11457.94222537363 9102.8470820947
15077.794588068906 17210.97327288611
7343.816013490534 11081.937781814153
11457.94222537363 9102.8470820947
16521.532162605257 21670.852705881232
16521.532162605257 21670.852705881232
15712.731908869317 14087.8433054886
15077.794588068906 17210.97327288611
7343.816013490534 11081.937781814153
17479.829776059032 19284.075943638058
10570.448696247478 13439.200013393654
8572.146058018378 5005.903814497438
15712.731908869317 14087.8433054886
17479.829776059032 19284.075943638058
10752.000006539482 10752.0
17743.58881399138 17211.597950219497
21383.11163137863 23119.861591281206
18419.355662997554 20409.879960450526
14659.300972420206 26969.479657568478
22259.12271406939 26114.823376772052
22590.82149900707 23699.36505478575
12595.200006351626 15360.0
12354.452265389096 15832.48309646974
9304.41845457188 7244.7675601084675
16494.40923464675 18113.24377354868
13481.42188346615 15832.725602371816
10861.103597701294 11416.804500384509
21728.353458097095 20352.0
15360.76798080096 14414.073123166818
22005.578928989802 21995.52536312784
12293.99853587107 11397.751357175677
11131.033375208252 11417.140797940612
11881.230322458556 18193.751922019823
9091.66123433996 7245.297509419472
8908.800008979884 6144.0

10682.319390469469 9160.525148701901
12467.466413741718 14699.624212883811
11609.82581934611 16674.92863552945
6942.782741811817 4238.073618992478
10094.595276681479 12112.379204764025
6944.217513874403 4221.276228819906
10089.001221131854 12064.337735657105
5983.704287479454 8949.29103337242
5982.379570037327 8943.595026609824
11630.727501847088 16684.31457986812
10704.541176528774 9138.938450389081
12480.148988604975 14722.73785679824
8610.071628299294 4686.498159607022
7667.979489046932 8244.363953635235
22502.357812262944 19387.246942255624
8916.55526534771 10593.111724134698
8610.319390127175 4687.317356441742
24992.798962901295 27014.065669572952
10651.722865339672 11828.470103948355
23676.068001253923 23175.411646829492
8917.072021689632 10593.111724134698
23657.16918352189 27822.56034228338
23653.327668169182 27821.66323209308
9905.744595940278 13636.055734705693
9418.397538859781 8136.814118560163
23676.457248498984 23196.270044987836
21557.659224739593 20538.57874829707
9418.886762245313 8136.814118560163
24075.222569641548 24167.60674953149
24071.341420406505 24167.60674953149
10651.722865339672 11829.443942975511
7668.2576899840815 8244.829652576213
25257.454227663166 27852.576469691274
20926.132776029117 21205.93464103858
20925.75843117759 21205.119782731716
25263.025966815614 27852.576469691274
9905.44308841244 13636.055734705693
21562.923758154877 20539.513528805885
22509.446905688288 19387.246942255624
24985.987452970516 27013.070632566007
42533.95895046686 42865.478138007515
21701.888582851494 21290.367399366314
26864.757583123657 27852.576469691274
38723.1205354114 39086.97501726118
17986.48026296418 17487.817016426034
21701.9460878512 21290.367399366314
43265.13607975826 44241.733058278805
34918.672139701994 35321.73857555712
19838.28541135801 20539.15833231732
36819.9398161173 36578.89752302549
34918.63640038797 35321.73857555712
31884.53167463984 31574.515293191755
17065.93519998245 13706.164452537405
43487.47019544825 46653.86827477439
17986.378847964366 17487.817016426034
34405.58094263197 32750.49532449853
17167.671947911607 17004.311953148826
24370.473938764506 25104.321221654252
23574.544917399784 24167.60674953149
36819.97370993086 36578.89752302549
34405.58094263197 32750.413264568127
40627.85330287585 40409.50066506638
17167.753959094356 17003.837713880945
40627.85330287585 40409.50066506638
26864.757583123657 27852.576469691274
38723.1205354114 39086.97501726118
17066.267085979875 13706.164452537405
31884.591890127747 31574.515293191755
19838.106362818504 20539.513528805885
43487.47019544825 46654.02464954122
42533.92960993024 42865.478138007515
24370.473938764506 25104.321221654252
23574.59785447039 24167.60674953149
43265.09170348667 44241.733058278805
25360.425557242615 28893.44742324806
25106.692657536558 27342.50354301888
8942.178475069708 7608.144320397714
24019.083158559108 23075.85794721401
25310.46419882496 26451.45050843148
11120.150938224217 12394.97660344706
22180.250412472804 20001.685553972697
24467.897864117567 26460.701899231623
24709.656693411383 24705.149341787026
25541.253397417895 27562.48323355499
21972.761162655708 18821.523052080564
26406.288655461518 29900.601365189967
8174.52466168183 4232.085183452715
23636.82268199345 23649.199500194503
8413.543372444215 10178.08945726063
26178.26382707608 28383.410031213658
23252.866979364073 21085.755665851768
9880.834177335435 8703.843346476315
7197.540629347715 7958.334750436174
9046.956824135825 5169.572999774739
9385.105374415829 13151.461819889073
24273.031376406205 25429.855465574317
9413.746520912915 10992.89775264011
24227.129574095234 23769.27598813224
10426.330583884459 14075.995169081296
8151.340128401518 8538.994905725147
10173.673132158316 11245.447656718696
22963.411053722448 22112.63080232653
23136.33678610337 22651.81321660586
23065.552778981906 19961.760092737313
5420.3503807410825 10212.809701546386
6252.713233291431 4268.224923782719
7247.894625337761 6915.172449042757
6242.683646566684 4305.773333560419
5432.70158392673 10217.315205082008
7227.54401577742 6924.332819846256
6816.0 5852.0642511852175
6816.0 5851.408121127768
9216.0 13056.0
6576.000004752129 9216.0
6016.000009234634 4416.0
5151.006212382198 9498.665222019355
2304.0000542534717 2304.0
5151.900620159516 5151.900620159516
5151.900620159516 9499.63536142309
5151.453411417015 5151.006212382198
14034.6678706694 10661.391747797283
25987.528480022873 30688.31772841255
22068.202849978014 23260.30621036619
21292.475844575634 21981.59944135094
17406.855233642866 20952.35807731435
23672.39809229306 25622.40396606064
15967.992249497116 13119.392554535443
14038.382563529174 10677.012035209102
17256.512796300674 16971.933449079985
25287.096417936165 27730.345111447856
26948.20733369847 30704.07876813763
26942.222412043146 28746.68031269002
14408.180839755973 16301.80812057362
15958.192650798523 13081.232701851917
17248.13451104528 16922.76836099815
25992.337279475272 28756.775984105032
15489.381775122924 16300.32432192685
17246.43621335215 17988.738365988873
16300.317646018777 17984.703639482083
18151.625548762844 20958.13016468788
12702.052407386767 9535.878564663039
32210.137845094672 34843.463260703575
39931.213744527115 41671.44635118872
34723.03766953577 34739.00775785054
45667.17004588745 47561.16453578487
12546.422442716932 8565.85016212635
39254.15720739015 39564.603018354675
23274.594303660804 23794.097839590388
26305.391462588046 26766.134797538474
25420.05257665688 26352.312156621098
44233.393946203134 44508.93721490101
36338.27541312328 38691.65558618551
24443.462775965276 21940.988514649925
21396.223104572102 21960.132331113127
43852.57020700155 46929.60366335944
40863.21989271037 42969.48559152181
46258.416576445845 49629.5110997479
36298.76337948719 38904.723016621
21884.56958173447 22901.416571906637
23565.319181184692 27307.638143933284
30142.74138266956 30545.83526440225
32482.40594922119 35052.863406574936
35276.37238946204 34264.31642394169
17949.076076500427 17477.368795101855
34518.96953940688 34871.55476889438
21004.879440739478 21556.62823820089
38111.55805001942 36551.739999622456
39349.28635947544 39365.9743941389
19887.613532045518 18030.849674932128
41678.00057584337 41477.03967257065
47123.81364023926 52384.2271299291
24221.805534683 27627.27442220821
25896.023246823053 29106.32185625659
28718.917016489322 26617.258780723456
24741.097488995914 23275.1717501719
14980.379498530736 14282.420978251552
41250.720046564034 44145.736838340345
40744.77502698966 39871.431627168844
15435.703908167745 14884.446244318262
21735.597806363643 21347.723532030293
33312.64249200294 31517.49839374946
42041.04662112969 47505.09666341076
31177.485017236395 30906.55089135635
42693.58570089891 45516.74351268992
30365.36559863516 30344.93540938916
36350.398210507956 36120.03792910522
15660.46908620556 13222.883951695258
23445.964807995802 17667.434477025803
26249.713332958516 25929.66216517292
29918.131241105282 28717.78020669425
40750.224099997286 43069.032772979706
28650.84466468659 31582.35032419215
7247.845307399987 4639.889653860316
6363.569140034545 9038.074186462512
10138.69893033618 10488.192217918206
7247.580410040306 4639.4759402329055
8365.225450637898 10543.732972718914
6363.870834641445 9038.286563281781
9095.335123017732 13043.965079683401
9096.109058273212 13044.700993123606
9055.90450700536 7142.006510778326
10138.004586702455 10487.276910618886
8365.913927360238 10544.279207228914
9056.540478571274 7142.812891291497
10850.815770663923 14625.310424055962
10705.90575920599 10548.617966349904
9631.569057012466 7137.243865807024
10851.459391252403 13573.340487882855
10684.091704752236 9036.970122778983
10849.806768786253 13583.521266593578
9639.5869335776 7145.23232652375
10698.511140574654 10544.686861163778
10681.387680342747 9051.80302481224
10858.151188034832 14635.285613885368
5256.465997015274 10562.402188896236
5229.769849620535 8456.11240464553
5412.504123683315 10798.846095764122
6949.6828384866285 7040.964493590349
6305.136207886392 3080.052759288386
7068.745959818081 7389.714202863329
5434.08899653127 10147.599223461675
7493.358244323955 6944.090149184412
7208.666766854712 5971.89166010235
5684.104830138163 8931.721726520593
6765.569539957446 3529.6470078465354
5806.146407998261 10748.84333312194
6588.717705289854 10543.732972718914
7247.845307399987 4639.889653860316
6363.569140034545 9038.074186462512
6363.870834641445 9038.286563281781
6589.2032902316805 10544.279207228914
7966.50594677491 7142.006510778326
7247.580410040306 4639.4759402329055
7966.907555632863 7142.812891291497
11969.634114708771 14398.200200025001
9800.896450835506 6781.887642832193
8776.923891660448 11873.816951595642
9799.941569213564 6779.765851414044
14351.789207079528 15642.422095059319
13205.006731455225 18438.499315291363
8778.227896335342 11874.059289055282
12739.506252598647 10592.15563518588
14354.937300068186 15648.860533597965
12742.375853819412 10596.230273073534
13201.342629529097 18433.970841899474
11973.09045651957 14399.600168060222
26471.467280828994 28937.926739834005
28076.76379143437 33091.14946628479
26388.686294698342 29816.008267372075
18484.462024309094 18485.885561692736
23781.039983632443 23764.79265636458
23337.279498690503 21152.624636200588
31262.14521941833 34212.549349617315
16257.65068513898 12962.890919852716
21567.262802972935 21580.74298998994
19693.837899200855 17055.333740504757
15738.302039292548 12296.205349619044
26571.828612802037 26552.874966752657
24940.192784160896 25725.190009016453
24635.36058855492 24617.224559239003
18028.852090555432 18035.08635964907
24938.03538397722 24953.249487792167

25616.205901977366 25605.53793615748
26856.074102519156 30234.902827692367
24123.986705727664 24110.251865129903
31976.4995113599 37220.65626772317
19710.573859958742 19368.01644464399
28642.297933650505 31834.298563027896
26075.099522724744 29541.17844636534
21495.94860898211 23410.656654609244
20398.665841789752 20395.88264822094
18404.412819756028 15578.091186021476
26497.146863011498 28067.519537714765
30693.303152968074 32810.947456603564
19136.197391984646 19146.67146007368
16996.2127275461 13861.386691092634
27759.834317228917 31033.979522452482
29377.358285389193 29358.22448650463
14116.613585102878 14977.859693561026
11694.20010945597 14510.020572004714
14356.401007525837 15314.13164368127
12996.634816580621 18604.444307745394
9833.525701395201 13057.4711180994
12732.536187962623 18325.2016905681
10908.146680348591 7684.424051287123
11910.435981944573 14685.752006621928
12812.428848582926 10207.103653828543
12610.910355719765 9956.539559505602
18214.64026717245 17622.211438976665
17306.64612222715 13876.981840443548
34542.45480564461 32822.34947410072
34542.39181225167 32822.34947410072
3953.5219741390083 3953.5219741390083
42630.91835745508 43002.8568353313
32032.17182944533 31760.769763971402
18214.561214863235 17622.211438976665
24563.33006739925 25198.125644579202
43582.30833721408 46780.27892178498
35036.67107563873 35488.33182892653
21891.36816190345 21400.8956821905
24563.24148216418 25197.988510990315
27039.829585261814 28063.54389595156
36931.89840859119 36643.24528477247
3953.5219741390083 3953.5219741390083
43582.242258172075 46780.27892178498
42630.88457987354 43002.8568353313
38829.55987469469 39237.58524680131
38829.59695902083 39237.58524680131
17372.574251132475 17348.13234904553
36931.89840859119 36643.339585796486
20045.31666156711 20824.699181500797
17372.574251132475 17348.13234904553
21891.30238388068 21400.734216376783
32032.17182944533 31760.769763971402
35036.629978495366 35488.33182892653
40729.31524175799 40467.84323385668
17306.64612222715 13876.981840443548
23748.967140698984 24410.442355680487
27039.7491133167 28063.54389595156
43374.06118868742 44294.95033296685
23749.088403557726 24410.442355680487
40729.31524175799 40467.84323385668
20045.388497108255 20824.699181500797
43374.06118868742 44295.02834404782
8230.286157844088 10937.834520598673
9770.866082390035 8433.457179591298
8334.771502566822 12211.773990702579
8334.771502566822 12211.773990702579
9128.989814869989 6452.2864164573475
9770.866082390035 8433.457179591298
9128.989814869989 6452.2864164573475
8230.286157844088 10937.834520598673
5538.126759112688 5538.126759112688
5538.126759112688 9714.516972037261
5537.710740910905 5537.294736601981
3072.000040690104 3072.0
5537.294736601981 9713.56829388665
9802.043478785432 6785.50926607576
14357.388821710507 15655.948901296273
13209.606201548931 18440.997803806604
8779.985970376036 11874.544201778863
11976.922449444182 14400.0
9802.23465134354 6785.50926607576
13209.405945932785 18440.373125292233
14357.840506148548 15655.948901296273
12745.156105752492 10601.808147669906
11976.783943947557 14399.200012500694
12744.862048684561 10601.808147669906
8780.174904863798 11874.544201778863
25267.586284111112 27842.56083768158
22512.91629265298 19408.412299825042
24997.788524409734 27022.2250009136
7677.61780907478 8284.474938099578
23680.907503725444 23200.643288495256
24088.72011555524 24183.81411192205
21565.399428250803 20545.410801441765
23660.22602503103 27803.84469817079
9910.392194279922 13654.220776009153
21579.936066286202 20515.845680838993
7687.147209610483 8260.662987920521
23671.83747092735 27821.585594642158
9426.939613681632 8156.501333292357
23693.429739064795 23208.93795502069
8626.994442510735 4705.507411533851
24073.928443327324 24188.599814788784
10661.07600364783 11831.554842876738
9918.370929184332 13622.678884859615
22520.80109340893 19383.128256295473
10655.23458211972 11840.212202490291
25276.388568434773 27896.50445844425
9436.091343347625 8141.580743320059
20932.484444040558 21219.865833694614
8934.163690015983 10596.19752552773
25018.187875135074 27040.736676355547
8929.448937084528 10590.0350329921
20923.889123200785 21199.506621617402
8620.966722022666 4720.015466076356
22775.570575509188 21891.36816190345
22445.953114982665 23526.741912130543
7840.373690073708 10544.09716381635
12839.231104704051 11195.427638102978
15441.772338692213 16974.363728870663
10288.996810185141 8145.870119269028
8738.81978301418 6071.573107523288
24077.36333156104 25615.02061291382
9536.951517125375 11853.96144754993
24078.29362724859 25615.99500312256
15915.798284723265 14622.284363258705
18878.74599225277 20151.769748585357
7842.363745708306 10544.279207228914
22774.643269214997 21890.403399663515
8736.84404805305 6071.256953877014
9538.990143615832 11862.314276733694
22446.89399983882 23527.63957561404
23558.26003761738 27027.708448923302
15440.015681339188 16973.571957605152
19267.4870193287 18213.77064201699
15913.989712199766 14621.365223535044
18877.83068151635 20150.912262227732
19268.383820133953 18214.719322569865
10285.454049287275 8145.1630431809035
12836.093058247903 11194.570157000224
12246.41714788452 14131.415357281096
23557.30920542497 27026.784954929433
12244.51568009123 14124.132610535771
6606.585805088737 9374.634712883484
6606.004617013222 9373.815498504331
6606.295198520877 6606.004617013222
5376.000023251488 5376.0
6606.585805088737 6606.585805088737
11976.783943947557 14399.200012500694
8780.174904863798 11874.544201778863
12744.862048684561 10601.808147669906
8779.985970376036 11874.544201778863
13209.405945932785 18440.373125292233
9802.23465134354 6785.50926607576
14357.840506148548 15655.948901296273
9802.043478785432 6785.50926607576
12745.156105752492 10601.808147669906
14357.388821710507 15655.948901296273
13209.606201548931 18440.997803806604
11976.922449444182 14400.0
5434.997015229683 10149.512007973586
5683.6991933071195 8931.46376581129
7492.40048315625 6940.629654433378
6765.029469263235 3529.9808781351776
5804.806322733296 10746.608069525937
7209.679681588574 5974.558477410695
7879.021259014346 7879.021259014346
7878.290233293008 7878.290233293008
5708.4022501922545 5708.2341402573875
11002.789464494901 11002.789464494901
11001.916969328573 14474.394529651317
5708.738586588109 5708.570398970306
11001.916969328573 11001.916969328573
11002.789464494901 14475.323001577546
19421.897035162256 20453.41304037055
18671.577568295852 22429.964600952895
17685.939185692117 19224.601582347554
7932.739769461747 7922.111397853479
19433.25438806149 20394.41308299898
18161.31579484262 16861.94368985972
7913.172325306709 7915.212820891173
18773.831741282866 16846.418076255854
12317.475544030025 10324.827214050607
6922.507222820356 6940.048702999136
15525.953324192367 13411.2210480627
15351.216864542765 13466.60896439783
18231.286107266267 19217.20999521002
18685.669461440822 22416.24683126058
14861.605334720742 16305.900097817354
10355.479829539527 10348.885205663459
10662.452074921603 10676.318653918119
25349.80083748194 25334.189546934394
35013.34791190354 35013.34791190354
33242.41389023968 33259.866085118265
21022.89554271723 23345.205631992194
34937.92496700398 36371.73545488309
12644.853903861444 12630.358348043812
21161.4716170686 23479.179393667062
18084.383940295007 18075.661343364452
15306.736107021641 15326.788345899477
15175.95898946752 15151.346639820502
33865.329353927744 33879.40083590618
35013.34791190354 36469.56610654972
9984.162709010707 9977.697780550381
18048.57958400051 18054.97341454703
34937.43534162174 34937.92496700398
26513.20008033734 26511.10418296454
33218.0906510293 33202.652454284434
33931.26894178878 33931.26894178878
19298.762253056542 19292.21120037825
17650.845886245792 17651.306382248313
21031.324025129754 21022.89554271723
27797.55660125544 27801.70543330031
21142.92706793456 21161.4716170686
12539.319409361897 12560.857454807772
25641.831998708672 25664.199383577117
25616.782155454264 25612.417066727616
33007.668601402314 32991.139674161
27801.70543330031 29574.260768445252
26450.835360154506 26459.577169713048
15326.788345899477 18413.344101493352
27867.99167503823 29692.282397956544
19216.565158737398 19216.047382331257
10725.283644267876 10717.232478583266
15151.346639820502 18218.73609776485
27885.148363420984 27867.99167503823
9737.465933830013 9806.658197367746
9786.599989781947 4377.659762932702
10699.019096393837 13061.616477297135
9405.333346623665 8454.724832896693
9222.181444755899 8694.6439260041
8776.99591261156 14254.62619643181
10163.930396805712 13987.069206949682
7142.006510778326 10487.276910618886
7142.812891291497 10488.192217918206
7142.006510778326 7142.006510778326
7142.812891291497 7142.812891291497
4639.6827747163925 4639.4759402329055
4640.096577658702 4639.889653860316
12124.981159206438 8956.342110482381
9859.590267855961 12124.917814154453
10383.987673336289 13765.208316622018
9859.473426608543 12124.72783199689
10383.65489603733 13764.706208270483
12124.791150549541 8955.827655778108
10568.09058439603 14724.210267447283
11948.386699467002 7836.9803495989445
13717.336950006003 10318.016330671318
11895.73704652217 15614.370624524065
12533.807014630469 16180.60780687796
13135.439922591097 9409.302843462952
14522.393680871699 14471.248805821839
15135.082824719233 14758.662270002658
12623.517241860747 19075.83104349585
13318.48006009361 19311.054580213895
5998.5713799203895 8663.213318394048
8762.959776239988 6921.826420822758
5995.480991546884 8663.43488461707
9861.766373221382 10332.844913188235
8857.138194699233 12787.083522054589
8850.655116995578 12787.834218506276
6878.043282794896 4292.8033963833
9865.255445248238 10338.587959678052
8760.904145121096 6912.690069719602
8091.034744703547 10224.225398532644
6874.865642323492 4293.250516799596
8086.6912887781245 10224.788701973259

8145.870119269028 8145.870119269028
8145.870119269028 8145.870119269028
6071.573107523288 6071.573107523288
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
8145.870119269028 11195.427638102978
18367.580449327015 21320.163320199965
18682.35684703619 17018.190561866442
10068.800794533576 7293.057657800327
12301.111027057677 14157.034046720379
18385.047805553837 21329.43292729556
16468.91647923445 13643.633423688867
16490.249211655355 13655.128889907997
18210.559046882663 19408.088726095622
15763.004791679155 16584.45853804097
10024.549057813025 12508.093060095132
18218.36930133979 19469.760989801594
10023.328551434399 12515.708210085437
15741.562204082542 16572.231503331106
18703.072386108117 17015.610303483092
11131.461589791343 8253.082454453002
18289.090233319424 23610.53097666378
12307.312351301563 14157.179556677242
18266.578813847435 23611.089597898696
9145.205250840465 11911.0
11129.76208191352 8257.967364914928
10843.13800520864 9340.665126210231
15126.301532843381 14907.382231632755
5880.69677844386 8872.866053311072
11458.470796751197 16535.496273169425
6057.621292223541 8991.438149706642
14556.151124610516 16859.735614771664
6854.670314464438 4088.0925870141446
9938.232537025886 11955.761456302145
10255.29979669049 12217.3039579115
12327.53219423904 14539.88122372394
7006.942528663982 4339.524052243518
10543.76279323468 8995.873554024645
14309.376723750836 22881.730900436705
8244.829652576213 10593.111724134698
8244.596791232425 8244.363953635235
7296.000017132676 7296.0
8244.829652576213 8244.829652576213
8244.363953635235 10592.386747093406
14354.92347593675 13224.445848503445
13292.163426453782 9293.223391267424
13809.257576441247 15968.461697984561
14373.462678182705 15292.628583732752
13291.434769136935 9303.270822673067
14358.841648266758 13224.010927097725
14168.846154856788 12055.074823492387
15179.759322256485 19654.49376096978
17684.482972368744 22779.016703975612
16044.613482585224 18916.502689450816
13524.042923623098 17909.501193500615
15178.53119994669 19639.64246110402
14368.707117281718 15290.74648275878
13522.037864168256 17905.13848033575
13810.125361487491 15951.851177841398
17678.8735815128 22779.62817958186
16038.226131478643 18913.571212227478
14165.16455534492 12054.660177707208
6816.98281459213 9630.67100466006
11076.253518225376 12027.233098264955
9093.238147106893 14515.219082053154
9538.362123551402 7727.850930239273
9539.318296529369 7726.956515989979
11075.42148182181 12026.275275412583
6251.389850465254 4153.040452487791
9091.604918824838 14516.012675662694
6817.301942688015 9633.863607089317
6250.744840616996 4153.595069334516
8210.3047717149 9165.573195387182
6835.101722400008 12085.052751229512
8212.835760090555 9164.631198253424
6836.271116462379 12090.05248127567
6932.8153732809005 4211.757946511171
5968.642592750885 8934.846165435642
6931.237765363413 4212.441097511039
5969.703272357849 8937.100256794705
9419.265889064225 15462.609385223439
9424.709139337463 15459.031017499125
9544.64861846679 11502.845082847982
9545.789140374933 11535.271995059327
9027.618887490642 7889.217008043321
8808.84485112044 10159.727014049147
8808.022424345761 10181.146497325339
8371.60536336968 5723.577377829359
9046.556680736478 7875.223488892236
8367.963816843378 5722.092362064772
13908.360255616044 17114.97172068946
13903.009982014686 17110.68730355388
14974.766008188575 11786.288516746907
15754.140506898848 14073.192814709817
14030.599527857357 18763.273062021988
14021.780200816158 18751.11303363083
15746.286546357525 14056.976204006323
14969.796877713472 11780.066213735812
8335.501004738708 10732.392883229722
8157.399600975791 8157.175981919233
8157.175981919233 10454.748203567602
7298.512742333194 7298.499640337047
8335.501004738708 8335.501004738708
4635.365142035738 4607.695844996716
7169.749577216767 7180.769039594576
4647.255883852319 4656.798256313022
10497.436984807291 10515.240082851176
10459.590969536046 10460.989293561102
10460.989293561102 14060.68664752899
7115.0748414897225 7115.142303566387
10515.240082851176 14072.317115528629
7142.006510778326 10487.276910618886
7142.812891291497 7142.812891291497
4640.096577658702 4639.889653860316
7142.812891291497 10488.192217918206
4639.6827747163925 4639.4759402329055
7142.006510778326 7142.006510778326
9538.671303698435 11860.565922417025
8738.209850993508 6071.256953877014
11294.504150249359 11195.427638102978
11293.880865318175 11194.570157000224
10138.69893033618 14129.947770604107
7841.975924472096 10544.279207228914
7841.7310971494035 10544.09716381635
10287.77410521829 8145.1630431809035
8738.429561425783 6071.573107523288
10138.004586702455 14129.268381625427
10288.333929261822 8145.870119269028
9538.067479316762 11860.080311701098
24369.099598102148 25103.21991299124
26863.383788263825 27848.716164304595
36820.46909329103 36577.90022677628
36820.22140159534 36575.90563472079
23573.270324935824 24168.560093642318
31884.32426060737 31574.746380612465
43264.144981728234 44240.734905740435
21701.9460878512 21289.249164777983
34917.682411637805 35323.695446541264
19839.75655250084 20543.252712265406
42534.455494927875 42865.478138007515
24372.0846507274 25104.642618448088
43265.13607975826 44241.733058278805
6354.367887524298 6353.31173483562
43487.47019544825 46654.02464954122
40627.60519723628 40409.50066506638
38722.87262152047 39088.9398679473
43486.47680601407 46653.036953664654
34404.59505647465 32749.498698453386
40627.60519723628 40408.50287996327
9967.717742793482 9966.909751773615
14693.598008807932 13688.32002109828
31883.608343473297 31570.62356051904
17167.59491665103 17003.837713880945
23575.94579359437 24171.42014859698
17986.138669820157 17486.9826442414
19837.864407491044 20540.448315457965
17983.502248588844 17488.432291088873
38722.87262152047 39088.9398679473
17163.564201852456 17004.74098597212
6346.2422345826035 6353.373985529263
3300.968115568522 3302.711764595875
34405.30812082474 32747.50544698023
21704.29503721556 21290.74637019567
14698.610641070052 13705.380038510424
42533.71067826672 42864.4927299974
3300.736357239093 3303.2929025443686
9959.667288619636 9949.036234731482
34917.718153718175 35323.695446541264
26866.345804535624 27852.838437042643
7142.812891291497 7142.812891291497
7142.006510778326 10487.276910618886
4639.6827747163925 4639.4759402329055
7142.006510778326 7142.006510778326
4640.096577658702 4639.889653860316
7142.812891291497 10488.192217918206
8836.000110909912 12292.000040676863
9988.00009811774 6532.000076546234
10548.394427589443 8709.543329015592
10547.969746722722 8707.559244702272
8667.040197078688 13573.791953614142
8667.557037597157 13575.06482489126
105006.6688406027 104254.9434271584
55524.95484014373 53929.9795382865
16648.404980845764 16619.539855242685
41633.40851287581 43917.877282491696
29653.845100857074 29635.190061816713
24555.06556700674 24611.123501376365
23485.12731240774 22110.12098564818
115403.82019500047 115131.6178380205
126425.29422353017 126756.01839754987
28144.403853441716 28192.861738390446
45408.23953659181 48216.16352427887
128370.31708288012 128137.05809796009
28349.268361646038 28397.75013975579
117063.43826182451 116794.29973247838
107128.77100320086 106927.23301385854
120830.67241491293 120571.10361110576
28437.676614660348 27313.75259827913
105200.18677963165 105207.5494106768
14542.1077220601 12363.264698290659
86672.14697128625 87250.38292179583
89963.97863167235 89615.04941135723
138779.70525635223 139499.8863081974
130040.93175688953 133387.6811403512
32471.07800893743 32465.492726893888
24379.67881793411 24436.679909513077
23730.860903894743 22372.65460333217
64130.61432576489 63639.8047530003
36044.193399388205 36049.49733352741
44634.2309143162 44631.13256461234
32615.674458619204 32657.927490886497
21484.99864003952 21548.197442013567
75314.20028491013 80081.47807077489
111033.36084010507 111884.0248873806
137122.85308146125 136894.579242569
120618.33027794739 121446.2567887541
29343.252316333306 31924.53478126189
34230.156347875476 36963.29337329129
50487.01305348238 52348.05765260063
84608.84699833556 85253.46103238272
94405.90913200297 95461.44440558187
20246.547650926812 20221.83535191601
109361.63285743725 110229.63335237943
90364.73681979162 90641.73670555966
74130.13714407926 73706.88484802489
10204.300135237105 7344.445111783462
109978.62053999404 109692.17806662424
101399.11561472803 101066.88985518452
63597.14249805857 63799.66941920624
48805.66187720032 49736.12354214992
17211.881180678007 16450.24796165699
118967.90438181214 119802.84888098446
48306.79673480511 49268.33998624269
29219.708876512184 29210.477880377104
36956.61670459026 36993.033398195395
52658.057896963874 52057.505760456865
63366.377869024516 62871.99098167641
18810.17414167131 17063.477986623948
13130.156134300578 13103.4811405214
73322.14668024934 76506.0792617162

27482.61672971662 30285.456377608047
25095.117965515226 25098.896748662082
127921.87336120434 127676.721895575
72955.46913796543 72954.87187295993
63120.04255923787 64660.4426987629
129765.03853118527 133119.13442101402
27029.53704180751 26576.735277305976
99798.57970982736 100346.97344713492
69307.49017933909 69141.83417439835
115144.7478973615 115643.8903271591
116808.50692689208 117297.35203319808
37825.78662552836 40321.965787892834
127214.97584419847 128000.2412810226
139852.18255014828 142749.16277512803
122491.11743812283 122235.07467580654
40844.35525395291 42012.5675006896
93771.57946077213 93786.53314842169
41734.15344943066 41767.34194319768
125556.73088703767 126352.30255123964
26691.283630206417 26681.08567881
120923.846335668 121058.46261207847
126259.68349667283 126010.49967760623
18901.044733029972 18969.38093349385
64566.16598558509 64558.3851486389
112360.02019010142 113301.74040146073
45643.96878041805 46689.17061803518
33545.47924057726 32597.361565010135
114036.09042333924 114911.45116131812
11795.94682422738 8745.403021016242
60186.225059715915 59230.869130884785
62802.28999731021 62803.17770622757
29407.160557103263 29390.498889947412
111600.77501558009 111858.2651081269
60265.821168075854 58228.30509297003
24884.693352854985 24864.7085846587
74188.82517097841 75266.48636013242
84929.69235926855 84560.98841073229
21933.939221621313 21419.307295055085
19038.017792827068 17315.047242211036
85162.43249813851 84881.93717157967
75033.59148612121 74499.4755015094
31003.610451042634 33942.65111920399
34370.7031882714 34358.04699047954
52267.096729497156 53179.44626451088
138259.8862412852 138359.1150304164
132088.3193100004 131721.02851101643
132162.7452463061 132918.78317228158
29048.712553226866 29063.662759535317
130463.56096555275 133560.7138832374
20457.779756809512 20434.559085040226
34037.99120335981 36752.272147446885
75753.3609984402 77027.8629912579
40202.18560153944 40200.255285259074
124767.22680695746 125091.68954011293
94707.03704120935 96154.42074600626
38299.73779365206 38198.943558690204
55626.55420890503 55883.69004459172
32392.06303078927 32433.587837302242
41843.01565900814 44085.99800390142
39018.61569658195 39450.914539462836
49669.221061829514 52864.698731762386
71218.88600831681 71237.89248005586
59372.200768225695 60467.293746289
74023.64554862617 75009.28081244347
56676.37263249809 55646.9126547017
120348.26528265045 120134.17382243906
74533.13161985413 74481.08394753664
44667.26061441331 44862.3654414254
111637.91445651428 111358.51628411721
129337.93977020045 134570.60246576887
87418.87560279101 87978.07750229599
131690.41194103693 131452.68816574273
126705.01549058502 126476.90055104924
95376.76050736889 95046.90657775244
28805.54925773852 32008.644098118246
106548.24202708602 106714.40548492035
24650.52256355329 24629.612136613116
79526.36927459974 79131.82718729551
60776.94679741345 60798.28988548938
140660.9482727882 145004.7477567545
73753.51366111312 75065.48294655807
86795.19920018618 89048.31771572106
122587.46133113389 122715.82548717993
31154.08672582138 34193.50072747744
37629.641095817 40151.87806317408
14869.463211562144 12586.829386306943
69381.04054249979 70833.65304712161
90338.47309690373 89992.78998897634
137192.53631079532 137324.0189114781
68109.29155490542 68528.37966857235
57917.27185356009 58477.2229590291
49232.440169059264 47915.82624770234
32271.231430834803 32287.0747049032
107470.90322054617 108399.29302352484
75011.49231124522 78107.33748502762
79618.38833704742 79871.45192745654
81352.61855775218 81480.89263747667
58003.59677468286 57459.527399727194
140915.25160890145 146093.63586412653
95635.75501402204 95664.38623646733
106068.76924128568 104818.19294855259
95180.22812013008 95424.78693190779
138964.42040121078 142336.09215163946
37193.15404601531 37229.443253962316
68707.61414865167 70111.59685102031
33805.25515714975 32864.43100070348
45927.39498164467 48008.1511516534
47769.648219999486 46668.85137862298
107167.86943570239 106474.33708645478
63728.19093274185 65239.15065357611
58840.53331793389 57828.66843530119
43725.10058124509 44627.985894503465
37697.61237880325 37929.06951139192
69509.91744981431 69059.50670255326
92804.09344607026 94566.9094345374
19484.707978309554 19554.503650054634
39570.18355596877 39711.39153945628
68743.01336921447 68286.92745321026
36247.451441446196 36250.74113725125
94954.2725258848 96038.84640081845
69912.27159738303 69904.94353048288
82176.67947538401 83341.65789687652
67849.67935915854 67850.00906411141
27325.073872910205 30696.465268822078
88635.71515997374 89767.31481446908
62246.55831707475 62170.54305698157
132488.9451352875 131899.84673986546
89879.39067132676 90269.69272685047
113263.43105986647 113523.86550853525
24636.11301411902 24645.758620906763
28692.16338793574 27578.805376593093
100926.09652136557 101914.12388869366
40416.71577164113 40417.91001523953
100794.32734137372 100482.61481967913
84771.01170801255 84185.40796361327
13971.997147195887 13937.087859377223
34624.909510035184 34609.69761497491
106214.8763158909 105921.89002278991
56931.640766800316 58738.87137152024
118695.25432934816 118472.56657977829
65979.11740574153 65999.40369427591
9159.8288193612 12555.097132240753
6298.068275272983 6298.068275272983
6297.763432362318 6297.458614393588
4992.000025040064 4992.0
9158.990391959149 9158.990391959149
9159.8288193612 9159.8288193612
9158.990391959149 12554.17958291182
8871.79440699569 13587.307017948773
8179.830961578607 10996.086576596239
10240.0 10303.801240319031
9088.092413702669 6515.9890270011965
6758.4000118371205 9984.0
7833.600010212419 4608.0
9088.396611064023 6516.696095415222
10239.400031251831 10302.90682283403
8179.492974506426 10995.667555905826
8871.101904498673 13586.62875771617
6590.411250024117 11284.138691100885
6591.408085952163 11292.0880708574
8330.2457813547 7043.531003694099
6701.000504402309 9927.001259192022
8327.801964237355 7044.294144909056
7776.600743255372 4549.0001099142655
8626.112341315757 5260.095531451877
7144.500004373994 10038.0
6180.0 11412.076279100136
6180.0 11412.552037121233
8626.067448437903 5260.095531451877
5421.414186149014 10138.975589279225
7487.310301807689 6951.206226260303
6754.814395673651 3522.276678513487
7196.022334904502 5968.73596333428
5673.879988156254 8920.731472250467
5802.483079586608 10746.733689824085
24322.06493655047 32696.893675087853
23144.98532295927 24049.562989792557
14928.19526867169 15852.321754241553
17814.014260196942 17564.65453688173
13660.76071099721 13246.176580432559
29345.195685367307 29269.87804894308
22308.67396148861 26048.72069795367
25396.785337518602 28790.485598544532
19880.14716019756 21456.898005070536
35158.908659470646 38621.74482076127
10969.560067751121 7667.5478479107
30183.17243230282 30450.874289583215
26273.265952532434 26510.111750047377
23297.825563773113 26832.666099364782
19460.486091211853 19838.167480893993
32841.758487565116 36342.308567288346
13045.91130452852 12684.618756588627
19206.128193992707 19616.791812118514
12197.139235082954 9316.45823261179
32095.705263477234 34836.60563258137
23851.94888926954 38501.00533752333
13963.935870663401 11578.50115515821
23680.257436311793 27791.895887110688
28459.397815835808 31440.452700303154
35432.797110339736 41472.329148481644
20376.105776129058 18785.537681950973
22696.05652442732 26365.970833633266
34081.88164118997 34723.097212086366
26499.1104169673 26339.501988458323
20579.636240255804 20866.484370875703
20962.693823231082 22067.232835133633
19887.572594540667 20250.841784972792
21934.355706644885 21668.346545133525
22375.134916071383 28432.668042236204
30927.69466820629 31196.133350144533
15853.478741273158 13832.272445263648
22934.32009872159 23297.583909066623
34204.26894526472 38486.30301808684
14652.782172359794 14262.440534494788
25226.061744156577 24015.24453342085
18145.516414806167 16352.370623246037
10209.379422864055 6611.673388787441
12972.804787805142 12124.72783199689
13461.886957051915 16671.96928979897
13461.943994502099 16671.831123185
12972.77149455736 12124.917814154453
14208.00000879786 6912.0
11215.656772565751 7850.603862124238
17535.652447513894 15597.799235789644
25319.57373039461 37356.01457596889
34184.84096951617 39029.291320750366
21765.353669536365 23534.69908454323
14465.572472598516 12046.5229008208
32826.531489635025 31833.760836570975
12627.429706793066 15477.122633099474
34765.764655924235 37458.55711316174
13609.483907922444 16287.798684905214
10504.032875043757 13799.632241476582
18719.490670421565 16921.226492190217
27467.48483935142 26271.738979367165
21918.274973466778 24776.80871298804
27026.343596572588 28467.797052107842
16835.853077287175 19067.17412203497
13546.003875682303 10923.832889604271
18066.58001283032 20159.811358244402
10087.141480122105 13484.607854884027
11592.2321474339 8378.791917693146
32458.3709024344 33668.456587732086
23977.289008559746 29335.04295207355
22592.894669840338 22220.77032868123
22311.17173166842 20822.90183908093
11800.366138387402 15757.360216736812
42862.374609907 46523.45835167459
39046.17331211856 38509.124957599335
11761.432771563164 9834.574164649937
39044.9805480807 38505.33573415508
9995.71118030128 11415.862735684937
37872.760524917874 34722.7169731863
54113.21027106043 53727.34009794269
36024.29306565224 35827.97334486002
27247.619510702214 30958.573626703153
38821.55332772992 39509.30728322126
42861.43276839914 46521.16329156011
83327.06605766086 80490.75714018349
26256.606685556304 27687.028479054952
9996.351384380203 11416.199060983476
69198.71741817184 69573.21429975763
37874.94036665639 34723.70119961292
84566.45976295804 84319.99395161269
55427.38096825431 57544.826917803824
86083.87919095247 88590.767560734
70434.8441185185 73367.71879375834
11219.457428949048 7244.449530502646
26007.280230735392 27573.009429512767
52657.91551134549 50688.265170550076
11079.791985412001 13212.357889491186
84923.52111426165 84779.43751877574
53969.73273567324 54447.96944790503
11760.779814281022 9833.793266079982
69309.93393763984 69008.96082393939
23630.78130320705 20158.78094032474
24987.65316889301 24586.59150838115
55191.81158469072 58216.32267672014
84565.4653262193 84319.06945644028
11218.887021447359 7243.919519155358
67892.22018595193 65780.50483995999
40362.83126563073 42304.387302028146
55426.394885469505 57543.832632177015
38257.86962128424 39382.930528339304
82268.37448862108 80971.90269470021
36026.463239124656 35827.12627325837
26257.484145287035 27690.07910786822
52903.735690402806 49914.45355806272
25423.647629962543 25423.995004719458
41561.14612381376 43213.713402113455
70619.02838077316 72834.51842361559
69197.51143531103 69570.71385288496
85870.87311772251 88149.3089819767
26823.197191982912 28949.34614114799
41563.63546193355 43214.68196111132
54113.73578861471 53728.33354013504
52658.904821501936 50686.274917377785
70620.86332034685 72835.5148605404
81364.22445768163 79903.83530845062
84924.56976259056 84780.42944571582
84376.44119872033 87446.24781544374
38820.216351935895 39506.002404697945
26824.685962747077 28950.274627367526
24040.324598474126 22004.21782295385
84375.38877210845 87444.54376346189
52903.90775841716 49915.44595613666
24041.75569711996 22005.090342918385
11799.606857857596 15756.629144585462
81362.94339046492 79902.06651895808
11079.098855051343 13211.776640558226
68083.03513928986 65186.09717570151
55192.80185857572 58217.30547697995

24701.101632113496 23843.908446393598
68081.5191516758 65185.10162606176
25424.90119941472 25424.90119941472
38256.28989233706 39380.41434520465
23629.860473561836 20157.828504082478
53969.158001955155 54446.989136223136
86082.80107547616 88589.77495174034
40360.138806060175 42303.39790135067
85871.8315734431 88150.30655079993
83326.10905352536 80489.76005679232
69311.4362699259 69009.95685406563
27245.837557730214 30957.70537362225
24702.034346182907 23844.874690381577
82269.45591507519 80972.89384108734
12852.233502391715 13054.647065317393
67890.67731286823 65779.51828646968
26006.345110376427 27572.03456402882
70436.39183767942 73369.51402319632
24989.357114579798 24587.372389094366
12852.93059967259 13055.529441581448
40492.12374030288 39521.616173937015
45617.48500524861 46668.65862653436
38359.33182502662 37936.668079840645
26626.306712359208 26028.79578466895
42577.8952880042 42487.19687152825
29386.160637279587 28029.655099554828
55301.992887661276 55693.64683695978
51380.170424165844 52127.660546009545
58024.69558539517 60841.69613020334
29477.8382095805 30526.68467095633
53738.262234795286 53459.71531910734
48808.77688570084 48502.4358666655
51535.47308120034 51522.97196396963
30431.294789410455 29125.30202418509
47717.855078379725 47379.15020343864
39903.36870738523 41029.76013822162
45670.00051894022 44815.264006809106
55291.587439682 58140.18167326277
39176.42839821946 39447.32271016628
60245.92798588133 62871.38685443482
36295.396532523584 36280.10117130326
70596.82267864468 74336.29899315677
50043.576697514334 53172.908261632634
65628.44134728075 65322.3107751096
39187.08911465611 43271.00559265985
57626.138460825656 57336.5104013141
62951.07678699369 63985.88869430509
34316.0233418734 33164.68551034368
69970.112028494 72234.10134417123
24452.213540201734 23814.661744396035
39382.76547983902 38381.935816214376
16704.907650148805 14180.623716889184
64796.311700589875 67619.32512233466
59350.14978650012 62067.489179118566
31411.94676214378 32292.935218093757
52618.666182080764 52309.44680456867
60394.27535058641 60438.39092828333
17061.52648667626 16655.972382301792
42524.59490665735 43923.52446013412
27742.645126231204 29027.136975595786
61506.58598251483 61543.543495642174
39358.880656879715 38967.513135944406
37352.16151677582 38368.96997574993
52297.255337182556 52666.03460485705
34955.61467954755 34517.15967457346
21855.429048779846 21863.549505969975
18507.40851068161 18514.21254064023
55023.43979977988 54303.23715028414
71608.13977086994 77750.35920817344
65516.372052182494 67938.63882210181
56174.56462457008 55477.59253067854
50744.38853745309 53835.50954528061
44000.013176844615 43654.55606234016
56982.4018773871 57718.31599241267
41280.72414596945 41271.06619654985
68506.56944421917 68545.54739733282
44537.194568135965 43653.68002814883
42948.611325775135 42574.62711521969
14252.050091565774 11666.669447618717
27322.019749702344 26756.51285201418
19147.821079123467 19141.524808645732
62721.18008520926 62435.87662554278
57938.81601693673 58578.04120999609
25928.565100218137 25935.241082357417
43498.400772385896 43403.45342251006
45234.783805061175 45246.63015076371
21240.539957355133 19325.60876143362
30894.43591186769 30395.621082649388
67368.5474437441 70296.49078723631
47696.52603718247 48024.318849932686
46372.29874073529 46364.81373843747
36976.56981533903 38028.61475257809
60844.78602263817 60871.56327875932
49753.934223938515 48964.24986661186
35218.69674463587 35235.06953306606
48462.04730653282 48753.64947365479
27527.790058048613 28850.789555920303
35287.60940312839 35898.05978043939
60803.338432688055 63617.067851324304
37300.3368439679 36758.63805964524
46577.69140711384 47657.90407686851
25669.521152526395 24106.066726033925
22779.6429052101 21858.67319852694
66361.44196383921 69622.6815915618
35397.882034381655 34277.63343639698
39368.655003256485 40528.18279913374
62199.296676981096 65076.70935134935
22696.613294305607 22688.515619140886
54513.5287491096 57399.540877954765
31989.002463538072 32873.48560770519
34561.46683513185 35174.008500596006
64546.222341822606 66938.24943184576
52866.35964642946 53468.65130148693
56749.477533112586 56737.45282439105
62956.276821298765 66186.30003255961
24680.184830750357 23044.99566066351
43376.97129906605 46954.27912341963
38340.09907261533 38618.18038178392
30058.235083126554 29525.959848919392
40170.61378669736 40184.40937726969
61939.887939641194 62939.77747021354
40548.74400866197 44353.76679606818
56371.6472564725 56769.15508442943
29095.17057407799 30131.421556242578
50378.32066676226 50389.59738874681
31468.918660173644 31458.341850771474
58847.86268778161 61992.63882107294
50902.989155844276 50134.19579488635
60340.6050987227 59665.2571937807
46122.783097727304 49500.76618598949
26888.918565844648 26878.972673820703
46724.2755650636 50063.2081273264
34024.69442023874 33547.72126389511
23956.487568936835 23292.060900658835
30438.60292149592 30449.50101397394
37161.85516886686 36606.3713033674
39082.76978516236 43141.022577124895
50368.52232621611 51088.99827751568
20354.561306007065 18340.325951301955
17401.231309306822 15002.924114985051
55585.26775664686 55591.86383815531
43188.04052564141 44553.578722701954
40868.722613265025 44647.51558597634
58758.023592793266 58504.895872055014
42902.39412993172 46514.62493667986
16652.141878415787 16337.443680086551
13828.623993821655 11191.420329877705
63089.460251396195 66421.27178848656
67077.64530833735 73272.25126198867
22475.167382889253 21610.858428114327
7987.794751995071 7284.93905259337
8481.84136847654 11747.160380279141
8481.84136847654 11747.160380279141
7987.794751995071 7284.93905259337
9215.0 1919.0
31990.613979381167 32072.62159537321
17488.197023675395 17912.684220964762
9996.479430279442 5997.631615896395
31568.573420500896 35598.950335648944
17037.386622366706 16035.35297397597
13676.688455909201 12406.491244505838
9997.119585160517 5998.27175109631
13677.301628610814 12407.419715637898
18676.976217391293 21296.390703591067
10645.431923599906 8955.48463233565
8871.073046706357 9983.615427288854
10029.974149518033 11996.54350219262
27525.097235169862 28722.50936112651
31990.899232351134 32072.62159537321
32907.40245834599 34865.846669771265
18326.368622531005 19745.21876303223
31591.183530219314 31065.655441339073
32908.04968055351 34864.85544212108
10029.208465277805 11995.903342391519
33178.59673889931 35766.73226617159
29472.9136878253 28416.0
17487.599296040862 17913.0272706765
18326.508308397915 19745.21876303223
31591.572111561654 31062.688631218
19550.06538352238 22372.858221514747
30424.607591735854 27271.125847679996
27524.477200101166 28721.640360536512
30425.897748099032 27272.111469411386
13202.726133643762 14752.017387462638
17037.653473410006 16036.310797686605
29471.71256582318 28415.054055904944
8871.79440699569 9984.0
33179.808336547096 35761.26509227547
18677.31032563308 21296.390703591067
31568.573598244468 35599.86719076351
19550.438029335528 22373.630550270558
10646.153288394828 8956.342110482381
13203.34735739388 14752.798243045283
7306.098274729132 9062.725417886168
7301.6918630205155 7306.098274729132
7300.501542892637 2715.2900397563426
7306.098274729132 8839.779239324927
7300.501542892637 11910.191937999993
9579.6490312798 8800.725651899393
10808.06505578126 3512.194897781158
10072.247106667795 13306.36313949082
10066.528039884346 13319.340261439378
9575.1544243422 8820.334290717105
39723.1249526016 40451.442891447026
30724.266370411515 28416.0
51658.74485505818 51428.76891390654
25212.62245163896 22691.768375338226
12143.146215046576 9984.0
25456.196111054072 23346.938857160698
46701.26382420264 47741.25461275604
53347.75713373525 54067.6909068623
17701.52535800234 19280.471363532582
36628.80527672176 39011.09751083658
35446.69191938477 35446.75691794667
31908.89815960432 31945.93833337816
36653.482237177835 39168.0
15207.779062045845 11996.54350219262
26338.157870283943 26247.179505615455
49624.984262365266 50397.71423388168
32808.97438201932 32072.62159537321
48722.288287805204 45450.09465336679
35495.487037086845 35825.368441929524
28396.389629669473 28532.517869967243
54148.69010419366 52274.7988231423
28627.393873700763 29885.46456055184
41564.10143456129 40985.5920049961
35716.35815701259 33546.74636980463
12354.486796301982 13956.696457256638
15513.367655025777 16830.418176622945
33324.278236745056 33337.30451011299
36065.3486881799 36865.99994574947
25540.891451259096 27742.505222131615
54522.41677308314 57758.81440092066
54888.99673684861 56707.640975445276
37889.7296902472 37253.937671070424
49866.86156396851 49189.48570578879
23883.578961286352 25241.976467780805
13854.780546800444 14976.0
16291.740238538056 14752.798243045283
43412.14355525997 44079.78802126888
20767.975346672578 22129.197364567925
44236.91851835975 44734.60943162464
53572.82903114227 52943.28195342635
13854.780546800444 11996.54350219262
35475.979931653914 35767.6985001831
13106.499981306984 13956.696457256638
55395.98368213269 56058.739479228396
12354.486796301982 9216.0
48308.93648177323 46755.055341641935
56377.13465581591 58862.092937645364
14995.679377740777 16830.418176622945
21728.353458097095 21297.292222252105
16190.861620062102 18827.75143239362
25738.87174061831 26540.4843964838
14976.0 14976.0
55326.68419544497 58287.10183222357
19200.0 17912.684220964762
55286.5658622418 55137.105038258946
16640.0 19968.0

33931.26894178878 35013.34791190354
19212.823354468233 19215.777918158816
9977.645576487472 9975.65140730168
34937.92496700398 34937.92496700398
34937.92496700398 36372.99274186824
15158.778084001362 18239.242089516767
21021.757918880143 21020.37535345171
27791.537416990806 27791.127091213843
17664.364643258472 17664.367863017345
33259.866085118265 33259.866085118265
33024.198495194396 33024.19676540219
12525.349027073058 12528.332410979523
25616.21041938093 25616.283122264245
12661.95190324146 15327.11303540233
19306.27255583014 21150.49845748322
18052.596662253327 18052.493484280778
33233.47598807564 33233.419941378284
33931.26894178878 33931.26894178878
12659.180670564743 12661.95190324146
21020.37535345171 23325.388335459713
26448.675429971914 26448.38945947371
26514.780783555423 27886.704574043884
10653.743121551222 10651.5757519721
25650.42972349586 25650.27563204731
33879.40083590618 33879.40083590618
15165.361131539203 15158.778084001362
18100.914479660965 18100.696119210443
25344.25414665028 25344.256390748575
27791.127091213843 29575.80702195631
10731.007280306914 10729.348955085765
26515.074674607273 26514.780783555423
19306.47436094949 19306.27255583014
8146.577256737949 11196.285142849838
8145.1630431809035 8145.1630431809035
8146.577256737949 8146.577256737949
6071.256953877014 6071.256953877014
8145.1630431809035 11194.570157000224
6071.889409401328 6071.889409401328
18005.92690532759 16730.20504955035
32539.8195617479 32710.771329945735
28331.51708688478 29775.98522299472
19645.32618239005 22247.229063413717
32174.2341702867 36455.14087203614
12135.483627775202 10146.450857319518
18005.37694912273 16730.601423738477
32125.04085974055 31427.723811946675
11436.999302264558 13613.228860193309
10376.71547263391 11877.84492237544
28330.6135027896 29775.146968570953
11624.168204411208 7662.985384300299
32124.026095120767 31426.53531651238
30094.765218597404 29134.485425351173
10376.361136951838 11877.521669102523
19262.3896117682 20313.13427317409
19261.933743930163 20312.189074543392
32540.873504631745 32711.710441369465
14865.54074361239 13292.622916490183
14865.97711958417 13292.124021389509
30997.029983173838 27685.087411817938
18473.69777473428 19032.511158541325
33734.252993063295 36341.865664822435
30998.084069825993 27686.05829655063
14301.329556373421 16094.252421283816
19645.88335059027 22248.092053027827
33733.14870049933 36340.9146967987
11436.596418515432 13613.490441470181
14301.12587735665 16093.554051234301
32173.180152280736 36454.24552778455
18473.361524849173 19031.330090143463
33439.01338257455 35190.58146720511
20512.583918847908 23710.885601343532
30095.790818651036 29135.40801155872
33437.95968323692 35189.41093567779
11624.44045965224 7663.486412854139
12135.708450683875 10147.207694730605
20511.98370194577 23710.15683204141
23557.30920542497 26003.524703393578
6296.269629709325 4684.8599765628005
15212.247730036479 15293.606638069386
18779.10996399989 18757.910437999217
5347.531872275284 7546.337124724816
16145.303452165277 15301.441631428066
22344.817746204848 22344.708903899376
5349.32680343985 7548.984170072156
8606.677627155428 8133.982603866325
22303.50646074389 22590.82149900707
21465.35816146565 22589.971602461123
10655.08779879359 12068.993827158914
18757.900114203734 18756.21115790713
4993.750025031289 2688.000186011898
6299.363921262209 4687.317356441742
18840.981337971167 19432.03790136279
7625.268163317274 9297.514990576783
23558.26003761738 26004.484536325654
22508.480201915012 23195.27678213821
19838.474141173258 19387.246942255624
22343.763716079706 22343.763716079706
23483.1493841861 25932.61916968666
17609.161302508925 15593.42630726166
19837.380497434635 19386.256601004745
7620.557644457524 9289.378020082937
23484.0759664927 25933.507591531077
17611.24509447807 15592.441277747368
22509.446905688288 23196.270044987836
8614.532224354636 8135.870266910602
10649.80023286822 12054.81982445196
7547.932284922658 12540.10223243814
9417.519937742514 7880.289588587465
9417.995593543246 7882.481906100387
7548.525750105116 12541.480016329811
7684.00012753774 11140.000044883303
8836.000110909912 5380.0000929368025
42701.8883664704 43624.044218756244
37041.35116926007 37041.57232083973
24497.20702447526 27347.70249947882
38174.43083764023 40551.56361966823
23452.594627839746 24443.643590921547
15947.134051121677 16587.31768550901
62626.31644568883 63441.571741248656
23120.304511282815 23119.861591281206
56190.57288927565 55830.74780083104
50532.032981565266 51037.09343213032
37450.357555035436 36903.000216784545
73495.13229535076 71835.7165760877
77025.6684553922 76387.03974497244
79420.36413918032 81950.49432431754
59973.04674862284 59636.5827324135
40046.6835500769 40682.862632808916
38191.81568084974 37655.50286478724
36272.56816107732 36412.3583553716
74007.08295231688 73395.2491105521
54302.20328517987 54771.88426556092
23866.294245232126 26747.24361499704
72733.95511038843 71071.17154655606
75161.06226630915 74889.83525819775
17921.06668452275 15146.465759377665
78660.71426703421 81190.27016213212
10245.723839729431 8017.006922786084
22834.92064799 23893.845253537573
47567.27103797316 47320.7061866156
50814.549097674775 48989.73214868602
61867.00213411427 62279.076695146985
22904.490389441107 22834.281595881224
55055.45075762254 55516.00008105771
13065.702728050173 14694.97958487864
36984.691319517595 37095.274523852764
60726.76652432599 60391.32554431969
56942.7604073819 56587.311121840736
24213.66225914618 26451.440792516387
9991.276573216257 12293.936228889428
51283.934342296714 51783.31716875619
35115.18146044528 32729.301382705988
35949.54686779793 33905.26472393336
22228.417150125646 22111.59480905889
11506.718578484679 9374.634712883484
19731.451207653226 19974.768709549557
63377.69469616262 64202.0052724212
48315.32693669784 48061.65641132232
50064.2993958769 48230.86889119871
36317.01486906654 36317.01486906654
35836.57126456157 33443.291704017414
52416.32239221863 52025.43141579895
77396.68706734158 77396.68706734158
22472.186564729298 22472.186564729298
19108.556646696266 19371.256257661764
43338.669303521536 44358.78753978742
75923.44776813024 75654.82202741607
77801.53294762257 78710.57505189502
12646.695488457757 14293.850006208964
58082.11899113186 58519.45483341416
10839.31575619513 12992.109336054711
78563.22600300983 79475.94111427684
53168.51400617663 52785.39438140062
73838.99437722591 73607.91784176482
35216.49796615217 33156.7101051959
40863.18567012502 41422.19231281705
39952.1217865835 39951.66040354268
19624.507153047183 18558.648253577092
76665.67253340963 77137.17982918484
20290.936734475814 19261.34200932012
10565.971278708834 12765.022248315903
38932.96147225382 39853.780761679314
79042.25421886702 80888.30343133672
40123.29809474789 40666.77544384359
74366.34766105193 74366.89855036311
23554.277085064616 25772.930935382574
78285.22211120052 80136.42767805413
65904.20789887226 66797.96335218613
18542.06059506632 15814.087896556033
65148.15314940077 66047.5756557347
78156.1333770066 78156.02855826286
41053.56201354518 43362.18445835034
71526.10311802258 70582.57065310104
11799.094221356334 9832.700544611333
10101.729112508412 7832.290150396626
70203.09555852933 69824.21821975525
62620.77727130589 63027.45487484006
16521.24305923202 17112.073661599286
58833.73736641248 59266.84895453781
42630.91835745508 43002.8568353313
38829.59695902083 39237.58524680131
43374.06118868742 44294.95033296685
17306.64612222715 13876.981840443548
20045.388497108255 20824.699181500797
20045.31666156711 20824.699181500797
24563.33006739925 25198.125644579202
21891.30238388068 21400.734216376783
43582.30833721408 46780.27892178498
27039.829585261814 28063.54389595156
17372.574251132475 17348.13234904553
18214.64026717245 17622.211438976665
34542.45480564461 32822.34947410072
35036.629978495366 35488.33182892653
38829.55987469469 39237.58524680131
40729.31524175799 40467.84323385668
34542.39181225167 32822.34947410072
3953.5219741390083 3953.5219741390083
17372.574251132475 17348.13234904553
42630.88457987354 43002.8568353313
43582.242258172075 46780.27892178498
24563.24148216418 25197.988510990315
35036.67107563873 35488.33182892653
18214.561214863235 17622.211438976665
27039.7491133167 28063.54389595156
17306.64612222715 13876.981840443548
23749.088403557726 24410.442355680487
23748.967140698984 24410.442355680487
36931.89840859119 36643.339585796486
32032.17182944533 31760.769763971402
43374.06118868742 44295.02834404782
40729.31524175799 40467.84323385668
3953.5219741390083 3953.5219741390083
32032.17182944533 31760.769763971402
36931.89840859119 36643.24528477247
21891.36816190345 21400.8956821905
11867.092882420699 9278.124810542267
10987.68809895876 13620.225585503347
11218.00000178285 8445.010005914735
13447.422966667049 17431.878154691192
12850.389422892988 15152.101669405469
13421.369300071021 17410.87303956927
14621.32169888284 14321.655281426096
10994.773565653819 13629.146451630784
13599.496021544328 11429.060591317206
12860.99433947469 15193.6653247332
10297.400629285043 13048.00061312077
13615.632710968668 11437.86431113781
11855.167649594838 9293.115570141157
14599.429627367108 14285.546891876418
14405.845430327927 11188.07119212244
17408.414866379993 14982.116572767682
12484.004846202199 9604.020824633815
19015.515770023172 19787.036564377195
14416.71135349529 11209.157684679076
13174.968387058847 16407.53058811715
17692.997233682912 23121.024631274453
16577.271785188295 19203.800066653475
16559.055152997105 19202.000416623265
13192.034284465 16408.58363784029
17420.718727997417 15013.607694355145
19003.96814995343 19751.199887601764
17714.50599869434 23124.761296065306
17485.356571841607 18741.577361577652
10221.766291840173 7289.017560686762
15804.712954052662 13631.776993481077
11338.542898560643 14362.061864509566
11332.072066153656 14344.27662867668
17491.75953921668 18778.07937463254
12496.66516765573 9284.680392991457
16315.429786282404 21722.71513876661
12503.068425890502 9307.018050911904
15029.492739277663 17471.3575030677
15782.312795024689 13641.182390100941
16309.818855864436 21687.78725458178
15007.406220929719 17475.591005742837
11293.880865318175 11194.570157000224
10138.69893033618 14129.947770604107
9538.671303698435 11860.565922417025
10288.333929261822 8145.870119269028
10138.004586702455 14129.268381625427
9538.067479316762 11860.080311701098
10287.77410521829 8145.1630431809035
8738.209850993508 6071.256953877014
7841.7310971494035 10544.09716381635
7841.975924472096 10544.279207228914
8738.429561425783 6071.573107523288
11294.504150249359 11195.427638102978
7142.006510778326 10487.276910618886
4640.096577658702 4639.889653860316
4639.6827747163925 4639.4759402329055
7142.812891291497 7142.812891291497
7142.006510778326 7142.006510778326
7142.812891291497 10488.192217918206
7549.492830647632 12546.380713177805
9421.394830679561 7879.558934356669
7686.800041629807 11146.000179436567
9418.974572637937 7886.625957911279
7547.287518631371 12554.435869444713
8841.600002262034 5372.000837676777
5929.412346748856 3953.036427861499
6922.103798701663 6716.399109642011
5929.5922288130405 3953.036427861499
5165.44838324806 9909.297502850543
6922.381111294003 6716.399109642011
5165.44838324806 9909.878707633106
13356.436652883882 12501.949967905006
13845.335391788496 17052.232258563687
13356.404315907781 12502.134217804574
13845.279933769647 17052.36734298203
14592.000008566338 7296.0
18490.871264251207 18972.08728632672
27940.851814343656 29095.44459189445
19406.02463798292 18471.956691157546
19406.1384119175 18471.956691157546
21133.8545481533 22195.7314815259
35252.324746036255 33286.20328304206
43153.46827312957 43683.2702072544
6804.49733632103 6804.49733632103
35252.23397334006 33286.20328304206
43153.41710759995 43683.2702072544
37533.854159445174 37059.48170171839
39402.53555372421 39982.127207040896
6804.49733632103 6804.49733632103
25551.82968225781 25799.289311917102
18556.578995062642 14941.061843122128
39402.59158989418 39982.127207040896
18556.578995062642 14941.061843122128
24674.62243378812 25590.078077254864
18490.871264251207 18972.08728632672
41275.92770686687 40845.038670565606
25551.954915426726 25799.54232152191
32796.39004694131 32676.121189639383
44093.484691618556 47406.506895151004
27940.966339767136 29095.44459189445
22892.32674937172 22105.863113662854
22892.230299001014 22105.567828038256
35670.56198393852 36309.83470080799
43941.488368055994 44639.8967740742
44093.58483952059 47406.506895151004
24674.801397377043 25590.078077254864
43941.488368055994 44639.750548138145
35670.6238810383 36309.83470080799
41275.92770686687 40845.038670565606
32796.39004694131 32676.121189639383
21133.959023334934 22195.7314815259
37533.854159445174 37059.305565539136

8073.109163141547 8289.420727650395
9621.265359146431 12816.629198037992
6559.330055560383 3953.036427861499
6559.232509304051 3953.5219741390083
8073.156715932127 8289.189164206593
9621.331860910826 12816.479430795338
15392.993907763506 19420.984552797523
11565.200003074357 8200.387307926376
13457.001521884435 13745.676847649227
15394.92679784841 19416.38771759567
13455.674793929882 13752.169319783698
11562.626926630663 8211.26549321114
18183.859657399473 19799.445472032796
19906.318594858265 20740.003085824264
13126.042634396705 11005.447060433302
19125.016732018823 22908.795712564202
11312.45840832133 8763.480187687994
12376.725537879558 14647.47841780284
10442.306143759626 13053.887696774475
15060.517090724343 16975.99670122494
15687.749208857209 13961.817396026923
10450.612998288667 13060.65086433291
18673.580755709387 17249.043103894197
13112.579389273491 10989.38615210149
19925.534798343557 20761.283799418572
18164.42168195839 19781.595082298092
11304.78486305688 8753.397511823623
19104.99536770423 22889.511659273117
10636.80610897839 7872.007685463728
15078.099085760115 16991.596776053746
12390.988339918653 14659.53208666634
18692.48927350234 17269.51142910534
9715.206688485841 12480.004847755468
15670.851228953708 13942.827833692849
6071.573107523288 6071.573107523288
8145.870119269028 11195.427638102978
8145.870119269028 8145.870119269028
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
6071.573107523288 6071.573107523288
20995.487938549508 20990.622310927327
26678.733439951757 27341.35512369495
18205.65261731153 18207.04437848164
23602.139571681022 23603.655331325273
22813.626963335362 22810.928345860895
24133.118986156762 26453.41512924182
23679.6828831056 24177.20209205358
7982.857414485116 6243.204385569961
20091.06960263136 20091.36901756573
17395.33774463721 16666.625723283043
13908.962290552088 12985.813836644971
23209.85735091881 22672.5706526631
12489.628056911863 12488.920689955557
15986.76330593532 15191.880594580778
21005.937547512607 20406.944920786158
22186.272131908758 22186.802743973723
18068.031990230702 20089.516171376552
15446.05966294029 15445.512616938293
9225.158181420102 9224.790783535418
24076.72337491591 24069.49947547726
15867.654146442414 15867.904114910702
17037.29680729898 19187.536605828274
18725.69532606051 18725.538176511778
14201.342475664445 14198.162733255314
14486.579996672783 15110.575501945648
25357.799769696107 26012.634853086296
23954.910983971535 25549.907416662
20214.246475258482 22050.31092751302
25735.137464418178 27196.10194494792
10974.941483012817 10972.074416444686
15965.762753858646 18242.96864548092
13613.284533049979 13613.651273629717
16724.87651507312 16726.399283766965
10668.19432940739 9437.101302836587
24794.600711534848 27202.67753365466
19840.629176991562 19837.10997096099
26494.059433201248 30182.904962909055
17209.672403105826 17209.72434410267
14971.857941558965 18080.736710654244
6568.1437636519495 4288.778963761131
18846.099079119795 20809.112451039327
8902.55321835009 8902.847185030192
26968.317315184868 28396.767791423023
19555.214528355347 18910.86343877508
22812.39762305795 24482.883510730513
12579.054058235062 11556.079092841135
12799.729229948578 13783.162626915493
21210.95087448934 22964.493484507773
27760.311151894533 31429.51900681905
13456.790674228383 13455.65030015272
10142.82748766065 10141.67875649786
24014.97354256298 25753.092319175965
7212.0447213325015 5220.9075839359575
9506.465497228715 8103.525405649075
12817.748155409758 16952.236961534014
12295.332177745793 13042.493358250178
15381.929693998445 20475.353623319916
12187.695434330479 10479.039841512198
12181.1598281937 10481.785391811836
11061.634362867802 7137.169256785213
10603.579527949774 14913.73799555296
15416.841152165742 20517.787794984135
11833.200853530712 10538.819858029645
12305.955071518109 13065.832388332556
11815.807495046625 10540.456963528668
10591.88198836994 14899.390860031828
12831.507723934385 17006.435605381863
13863.239993273979 17109.211203325536
13845.019032128486 17089.04728181182
11856.436996416756 14895.413555856716
11067.619436897892 7134.751292091407
11864.868109254312 14892.514764135707
10242.442716461732 7544.402958485184
10242.255269226596 7544.148527169915
10669.850863270978 12057.844583506623
11356.43887845129 13224.32667473093
11313.61423732978 17326.648175570484
11356.143051230027 13223.891144440051
10850.595559691643 9295.655759547037
10850.300687077755 9295.036148396626
11313.755644249073 17326.86976923414
10669.640939496407 12057.685391483723
9907.200008074937 12672.0
12256.208916300342 11135.310368373213
10625.140196722114 13240.75167805816
10828.800007387707 8064.0
10879.529447545054 14817.105824013
12256.626615835206 11136.0
10880.0 14817.6241010494
10625.357021766375 13241.0416508672
11489.495612950117 8931.61217250279
11489.295095870764 8931.182284557852
8756.371876778901 6250.32999128846
7216.78051488335 10914.697659578116
7217.259313617601 10915.330869927855
8756.634976468478 6251.067108902287
6439.786351269738 8756.28420050423
6439.965236707416 8756.54726476138
55065.436847808625 56870.710510771714
83429.70213155505 84629.82122750822
55149.531258762516 55568.12107674687
36852.13967096246 36870.22897948967
43978.71987819791 43871.42644136386
46461.90674123534 46457.22817818558
49539.014640766974 49546.01793282685
63669.20783088556 62848.23707949174
59762.959875871275 61487.46620247089
12409.37714633575 9343.765033432723
62749.506908978976 64414.209496042095
24806.918476127783 26128.8874811003
87970.70919891461 89177.05158839913
44608.90089047532 44624.608558507265
38426.931183741435 37543.459150696275
29218.75408689811 29191.827246679848
69286.09378511678 68811.22248587072
29698.544027075215 29958.459806872583
15424.49009205815 13096.344871757157
85268.60057571383 85257.58181534355
74525.18334093517 74532.7662843665
13337.157295399278 14543.144948737876
41748.45911264271 44110.94415221692
88586.77443253028 89752.59695964234
64983.056261698795 63828.39073641133
46934.03483613997 49315.602166048826
32360.29274869512 32356.796581243947
67274.35980104623 67996.8611407909
89535.56702227333 93756.99660825319
80060.8130483322 79649.45281042425
39273.891291838205 40088.62463342937
87891.44616025285 87889.58439428417
90010.18549393764 90660.43847787192
21780.745907366214 22798.5066616215
48942.28180132185 48273.29751529307
31966.950944373784 35212.4232622522
26661.749009583 30185.614123287272
87180.57073118772 87252.91246141873
81559.73425998887 82862.18583286347
89089.85336199909 89971.9133118775
95408.77109457903 100037.12895720269
93789.65985075326 94853.62180222746
53754.00293233984 53634.00414848774
11367.889774272091 7930.478989317102
39778.19407614156 40095.19329046812
25896.081064516307 24565.81339992633
87321.51225468123 90513.80010804982
32502.568062481616 32533.963207700348
29102.015614042954 27933.793870507456
75203.25786373887 76612.21469844088
51453.85168117276 51473.68702550848
73233.4457056337 74648.6538458665
49191.643078690206 49201.50783258578
21157.887617728866 20209.76390262885
18777.051638902205 16856.609297245992
23300.510286257682 21828.222694484313
81090.87334791828 81087.03060292688
57739.55354530472 58805.356830819415
85520.58829863394 85803.19637985522
68932.05405353884 70449.32548293135
12084.330155722328 9857.20147912175
81147.35125115376 80787.34089571211
73198.43850131812 74363.83640587675
72390.25587333042 72384.10645991287
43709.84898610101 45724.50625211824
77513.81205993226 77532.5907860688
50431.94361434031 52403.24895462112
29660.86752966347 29432.729825824856
91706.61078176493 91723.74965078564
79914.02950115275 80424.3195370654
28195.967650712042 26980.41174630217
93844.49041472813 97033.60222623913
86392.52197691216 86386.90585962667
53605.10549203779 52600.20429618121
53663.16993628974 54782.50888741771
23546.810284365507 23910.075554042065
61404.02522560105 61776.72002461769
24529.41050619134 24510.41790749395
39375.32793260267 38514.39062220769
28394.917024002727 31810.41944080587
28198.28543241814 28208.471653033597
34187.522510413066 33205.93942354289
68820.15172217 69714.84663255022
64282.38066379897 64369.24383585689
25347.526498654657 29282.844021713463
70556.70258934476 70551.30329767126
58747.38202630347 59041.554942260795
63915.70301702079 63397.634277629004
34127.05803317948 34125.142930103604
74671.74029336667 74212.89163615712
58562.66758029385 57979.2453383105
55436.90283581666 56529.988722800925
44058.42187505132 45265.53101422759
33254.60758210808 32251.0840127894
89995.34233009568 95549.60405988086
53782.6299104088 53771.0298301976
84925.93573908973 84526.07962634964
25774.719845663676 25334.917959211947
57521.118135537836 58543.8110136332
26056.60996906543 29843.69243240521
41583.3130594473 44011.15327959493
79526.4312603049 79100.19130823895
12313.368951852472 13684.385883188183
95225.7450014438 98373.35790751477
31948.483447966664 34494.400255693676
21100.730077803622 20947.61356336325
82684.70071272632 82686.90167735153
34259.449812469626 34729.203863607356
75808.58719550262 75823.61266122843
53928.84154504549 53964.476324708274
41578.000031003474 41577.70712773854

92233.05207360591 96030.22979249815
43665.03321835448 42887.13729080084
68403.44972619762 67307.70713670166
69175.72183678769 69162.76677519488
75180.060158317 75045.06596039476
78313.68663854359 79573.44374224356
14410.23005090481 14887.864386808473
39183.070588983326 39165.09013139125
69471.31053543041 69707.91188954092
37848.72502846034 40416.18672017438
44331.59145452174 44312.86929324257
79892.41417231833 79881.82837792335
66452.30195327238 65331.6105189517
17124.972974207783 17198.269942061033
29397.612777703187 30074.231494753112
85469.31505166051 85076.92724234932
34350.84561229898 37211.24347559485
88602.11442066437 91196.7815769833
22501.36879343399 23508.028692342537
93123.22056353615 93140.95617396248
40238.31742044049 40275.66217953468
68752.40130322722 68259.76023983676
24170.0789605661 22754.44193998174
36172.9094612339 36187.94741346903
45975.38213131023 48124.75376560383
19529.558055419482 17735.17053766329
34629.96829978977 35025.66163543524
36487.87413758165 39256.14726383627
74131.31785851375 73694.41640992892
12099.996548759838 8393.871633519302
14214.861241359731 14220.915301062727
10870.277532795564 14529.170107063926
13527.693114496647 13886.438996373405
9393.883033123204 13567.230557486668
11693.748990141888 18222.603985160848
10774.200475209285 6683.994090362438
12730.811394408449 9496.000421229983
11585.537663828985 15149.392892126074
12487.078178839294 18448.442806914627
7912.500063191153 10806.00004627059
9391.32369863269 5897.607141883901
6948.000071963154 12092.676296006604
6948.000071963154 12093.574161512386
9391.158757709296 5898.657643905094
11162.47428266292 14393.43853983474
10671.529236712047 9872.609381516115
11904.000010500673 4608.0
11162.405495431729 14393.598577145327
10671.569709396083 9872.376056451658
15147.608604661002 14087.189109258099
13057.411688386026 10488.192217918206
14745.088566705865 16081.385046071126
13056.602965549653 10487.276910618886
22341.84297680028 22891.404172745715
7739.705436901329 4639.4759402329055
6598.283432075345 9038.286563281781
8705.220560100703 10543.732972718914
14745.9999945748 16082.220742173638
18313.239932901004 19405.361759060303
22609.527324559444 21537.27784563314
22342.533858092283 22892.32674937172
7739.829471635664 4639.889653860316
18639.713784283278 17788.77668643912
12414.845307131298 13044.700993123606
18314.11720504158 19406.252188405673
12413.994723697928 13043.965079683401
22306.491667225484 27508.439577700512
22610.23107975679 21538.06233160263
15148.495814436495 14088.1430997843
6598.1379380852595 9038.074186462512
22362.2342913225 26199.78644951138
22305.894519442612 27507.49739616456
18638.861725974577 17787.80528901753
22363.115353467638 26200.189865724256
8705.88214944356 10544.279207228914
19116.17228840544 18632.905087505813
13600.835344035144 13575.036279877855
18049.468788859132 20451.306853108435
18271.246339877856 19016.930246493517
14873.098521323658 18158.472898346932
20997.802660172696 24986.570472956068
18044.53961729143 20435.359673859424
20981.6573493373 21892.508604543244
18515.400496763647 22499.937288801495
16059.432594273061 18949.28357484789
20349.573759663865 22496.508284620526
15621.097029338242 14614.931884890877
16332.556253079307 18955.26325324974
13406.568793153436 13575.74325773731
15993.721033580647 14615.459486447902
12623.650560332688 8275.999093765055
16673.229260691878 16508.327413763032
17495.121155625075 13708.85378140711
17122.78434409674 14644.130598980602
14023.48031539425 10406.428830295243
16861.5147629755 16511.81807070318
13903.30340973414 9748.609747035727
19433.05527303666 19007.737713889048
14172.329623358504 14178.54520040755
16161.470973515306 18637.748200895945
16171.77728499733 18654.169319484587
17872.801090274013 22790.932078350812
14198.809338836303 14138.018566970408
17730.92570376685 20137.19826589588
12539.514887945226 12537.688622708733
17089.30969934128 22784.06899568205
14730.004047860952 13658.785670768833
12665.478261794931 10608.009238306686
15756.758349355998 18258.62656390124
11927.774397519639 11943.020262898326
12672.989173829512 10643.077938265791
10789.097715749913 8252.196859018815
10788.100965415555 8311.003850317962
16482.605758551552 16594.13803124465
17718.018238857865 20127.466830180096
16479.67770204458 16553.848193093956
15748.691060529443 18225.601361820685
14714.684682741252 13652.840766668305
14294.576898950176 17008.976277248436
13771.246533266334 16539.003658020032
12526.919426279552 12504.68592168552
10086.243433508831 7325.039317300624
14292.385802237499 16943.02269372263
11937.53310529441 14167.008188040269
10067.81239793432 7297.065848681921
10792.296767602344 8276.367379472711
12679.371735224107 10637.932129883138
11954.556369853295 14243.083935721224
14700.549607412642 16549.50830085293
15535.659686311647 19432.472822572017
15329.98804565744 13660.834308342957
10772.438683974953 8257.641430820304
14748.98206114578 16544.027472172547
9944.271084398293 12499.452948029366
15290.119520788581 13620.998568386975
15561.333747465222 19485.06979715495
16461.819924365052 16986.806939504553
9148.033616029184 11896.008238060362
9916.284862790097 12525.178841038558
16488.498247094685 17035.81782598065
12655.534386188518 10602.864612924188
55142.84733711567 57217.18804694967
51615.52526130099 50419.90479959279
22522.721349783646 21585.862433546637
37254.22114338186 35610.10217620837
15342.487542768284 20595.807340330215
39755.90966133211 42966.85323595387
24170.68747139808 23236.347066610964
13192.744621216048 13197.952871563075
55756.075954902786 58998.26181337888
11787.692961776325 13161.145238922029
40099.7941876126 41997.3121163724
39759.20824161366 42991.282465169614
37620.80957395787 34434.89603585293
23132.7823013143 19587.47068919313
55669.18207159146 57931.08195951462
52625.2275286715 49596.86973993419
13798.982736509963 15551.63013963488
25477.293081836182 26940.061766818577
24925.900124168034 28425.90397858967
14794.156911429593 17288.982445476657
15176.469553592204 19147.227919466568
13961.573984014522 16138.877811049937
54201.759975525194 54189.2576808356
40110.218371105606 41998.299584626046
23827.68705602791 24944.84189166169
24176.411426843315 23237.305523661733
14060.607789139132 15550.938781951398
23829.796088091058 24963.615222959994
9578.549975074515 7305.310944785308
25470.367115532514 26939.092505130902
12700.09631634518 12629.900435078654
37257.4663658172 35611.051093726506
11918.954135931745 11648.12160822508
53821.21096222195 53416.38759781496
53720.92404268564 57261.98948691881
22529.659594508845 21593.25496538213
55384.60623675138 57932.06297034484
38577.72326304392 39273.593163855025
54165.694628986574 54179.350845132874
24932.85412418277 28426.82254491346
38572.75171153855 39266.58769233711
12697.684832720928 12630.751679927842
50819.92756232539 49944.66457991284
52664.06029656278 50418.92994699511
53267.41548597562 51641.58340910937
11662.651952279122 9581.063876209155
9580.987246886409 7304.8904851476045
37623.900701548744 34435.87733745141
38784.30972700172 38210.24136275509
38790.95396403651 38211.22620382654
54583.40971760558 55305.11419389711
55126.16454804178 57216.194779100784
12208.439527766233 16986.104909601847
23123.84226291124 19586.529682411838
53818.926687922714 53379.960518906344
11656.124199750104 9604.754291495436
52608.07077921705 49595.8787098283
11054.151165964757 11648.385295825341
11162.47428266292 14393.43853983474
10671.569709396083 9872.376056451658
11904.000010500673 4608.0
11162.405495431729 14393.598577145327
10671.529236712047 9872.609381516115
14762.092340857376 16494.60714900479
25702.514740779745 27852.576469691274
12869.130421768987 9382.230278563835
23831.326281021375 27852.576469691274
17539.261865249 20409.879960450526
13144.40894829433 15336.356835963357
22022.01540945888 22344.708903899376
21901.011242507604 25033.73723597817
19906.778842394368 18203.584701920663
24862.66148263295 30052.753617597173
12126.62787268167 8561.91386314999
11849.712087747112 13549.695236425061
11965.702107273104 14343.569430235975
10401.663929391298 12669.666767519973
17690.07827458972 17003.837713880945
22589.341206393976 22344.708903899376
13852.498981772205 11816.43622248265
15395.625690435578 13286.899412579294
15933.804680615362 17785.667937977476
12738.679192129772 10496.975564418544
22471.619555440244 25032.89358024757
23659.879460016273 30067.974258336726
11047.992999296297 12960.10327890947
16522.570117266863 14858.616893910415
19420.853387016752 20662.090504109212
36082.59491931132 33916.135628930366
54522.51616534219 55513.516858509334
49363.046907580574 48876.72918680218
19504.908153141863 18258.559006668627
54521.04261862774 52652.82761637783
82045.2009526456 81790.20135077306
47965.854521732435 47852.31680911594
86002.37987404768 86890.12979619722
106769.1819650221 106511.07733001295
31120.951717095315 28779.51271303946
79041.75164289931 79920.20785758756
41933.84504564899 41359.84835562142
104557.3827247029 104236.02018496294
46884.35747666806 44444.57870201944
78396.98760439998 78035.85642510756
83353.30517029604 83072.7889022633
75248.0347244291 73539.75969501125
44608.08339428081 45111.420460898815
12399.904417194335 14014.684869807099
33681.63796657032 33700.83455939927
84098.87684611358 83717.91896601349
90970.6115350584 91292.71918395245
13044.474913157677 13909.071572179071
52033.34400384259 52652.82761637783
87166.63225254261 87492.01920746829
25097.180109415567 28032.0
73356.56436959893 74248.9628883798
105866.44688474247 108056.26267829181
94775.08563864503 95090.21703624407
75468.85836431144 75252.24397983092
12479.179460204905 9842.692314605796
58994.67094577272 58651.52192398762

105684.9012957333 104088.79409427318
55659.06227956055 55508.92339074863
15238.823334660718 17051.741611929265
40093.26736264457 40807.303672259455
22259.12271406939 19584.0
60231.44693596527 62308.659301898
23662.11256476855 23658.887885951022
62512.43718753093 62966.122018113834
59522.20210980101 60229.270757664
21092.43144027023 22430.47435967416
22632.48497182755 20664.76653630522
95503.60248062781 96441.35345379595
33496.020899669726 35800.66412791808
36431.41517375492 37225.23032836735
38255.06403896091 37626.12198991546
86867.02812920447 89395.3319586655
70072.97233286526 70487.47302180722
17996.806912963755 19544.434706585915
85226.70549448948 84592.50690220736
80930.05653512035 79257.63720929359
106840.21179575834 109088.44587764554
28788.388650827805 28873.667328553885
12320.623360853135 9223.996530788592
24213.980006966594 25574.16909696188
12831.361580128587 18753.20132670686
32261.546245026755 32418.224889712885
32299.098399869374 32440.61454411738
56859.236716649655 56437.55005313395
24062.878522996787 23043.199777808637
26684.739661045558 26607.07154122753
59520.48463437702 59234.95624207044
98057.51749582714 98860.59306417295
66285.88271881502 66735.3426079465
15431.770036014808 12245.927976270315
89066.40041599581 88799.53297174485
24091.55868763995 25265.33245377943
104442.23984116771 104811.60241118347
16566.942477792938 15049.161704227914
99323.05142312132 97221.03476100221
86636.2884201662 84981.20413362003
107773.67656859031 110309.63954251686
62025.83835879295 60229.270757664
52031.56704347852 51793.65360736776
70830.4051669275 71635.30034836176
105676.84961239145 108611.6015902537
32290.593926482677 36155.185520198895
28986.705667330403 30223.741793497375
60481.0497263399 62976.0
106951.82100885945 107914.24862361782
48108.93239305982 48108.93239305982
49180.1586008016 51417.29887887928
76509.72038535003 77350.98354901507
85599.22552820077 85603.582728762
103128.01317294929 102708.16480202535
74885.05751631777 72372.54020690444
59235.65628909669 59235.65628909669
14035.572980426872 15123.484585240269
100631.33042467441 101014.62864357815
22054.49324337837 21639.913146775798
99524.75358422144 96600.23552766319
92877.2092603993 92619.65372425012
51189.658465748726 51798.73913523379
68181.80640482475 67829.01043064096
75604.19366357928 76139.50097682542
64398.221095869565 64026.746411167886
47072.16315403404 45111.420460898815
43781.11377209356 44451.57772228113
26071.78197515467 26889.78239034299
100750.82869257205 100417.28488661701
86494.76284723832 88344.20537873438
47072.92821899984 48108.07043521908
14107.899631057771 14832.543679355878
14357.388821710507 15655.948901296273
13209.606201548931 18440.997803806604
9802.23465134354 6785.50926607576
9802.043478785432 6785.50926607576
13209.405945932785 18440.373125292233
11976.922449444182 14400.0
12745.156105752492 10601.808147669906
12744.862048684561 10601.808147669906
11976.783943947557 14399.200012500694
8779.985970376036 11874.544201778863
8780.174904863798 11874.544201778863
14357.840506148548 15655.948901296273
3303.176728544811 3303.2929025443686
23573.844527622132 24168.560093642318
36819.478326695506 36577.90022677628
34405.52513930155 32750.49532449853
17986.138669820157 17487.290298957127
43266.17155597559 44240.734905740435
6360.1978349733745 6355.908196316243
40627.108986026804 40408.50287996327
21701.9460878512 21288.996829348253
34918.63640038797 35322.151746460746
23574.57752802794 24167.30487663033
34917.96558542608 35321.73857555712
24369.99248848651 25103.005915626916
38723.9932026967 39087.3483879375
9973.55324094678 9977.61745107518
14699.185332678966 13705.772579464465
6355.213391381913 6355.001966954849
17171.06684383808 17004.74098597212
40627.697358144724 40412.560547433764
38722.3767938191 39086.97501726118
36820.88627565882 36578.97102161295
31884.47146252301 31573.591243315987
19837.864407491044 20540.448315457965
26864.400286955555 27851.52893469226
14703.144350028595 13715.185817188187
24370.403967836795 25104.321221654252
19838.832229997814 20539.15833231732
17167.92307699967 17003.837713880945
43264.144981728234 44240.734905740435
21702.131879725548 21291.359397652373
3302.5954187577986 3302.711764595875
43486.47680601407 46653.036953664654
31883.99641234176 31573.77345202819
17989.020825214473 17488.95885980638
42533.21413392715 42864.4927299974
43486.97350069328 46654.02464954122
9968.526571163864 9967.987259221392
34404.9794926387 32749.498698453386
26864.289069733863 27851.87336607719
42534.543524205124 42865.478138007515
13931.92248264754 12879.572702539475
13931.891481417733 12879.751550398789
14976.000008346688 8448.0
14228.75961252811 17432.791199346135
14228.705648949395 17432.923334885632
20339.175425763948 21152.26626156167
4210.683584645135 4210.478476372964
22178.506402596187 21649.277955627065
18158.03692583535 17513.17130048125
40975.24716215877 40693.58357284352
17667.775072147597 17698.401283731815
7083.212830347539 7083.212830347539
6762.920153306558 6762.920153306558
43623.0779290045 44517.923401704174
18519.371108382704 17883.141670299432
24029.250222385217 24720.32621143985
39078.01427913143 39505.83713832679
43443.650686838 46658.17691466309
34805.23362944142 33055.79864411084
19975.354439909195 20799.873869809882
38697.84987567139 39129.82945273337
31924.248354503197 31674.38133571041
37183.118750314636 36872.499020272546
14891.27748045815 13792.338779191874
42874.507110869505 43264.80472624371
43824.81488837118 47036.865201669214
35290.93708021934 35764.09104115467
43242.98455241035 44134.37083498529
24482.951476486654 25062.91860498294
34911.88085738149 35390.10303743124
32300.223652476463 32045.59951069725
27320.80467336202 28359.511420333038
10518.025670248195 10518.025670248195
26948.505580087367 27992.225224158225
36803.46593732715 36489.614536193716
15249.074594872962 14162.521809338901
34427.986769487405 32673.43583096213
24850.60651171315 25443.44127668268
17303.328725999516 17361.065433895466
40594.640840879474 40310.3178975309
21810.274299054563 21276.393702881134
23658.70125345007 24358.861077644826
4382.72247010919 4382.4814888371175
42493.516505462336 42887.28148297581
10160.573261386387 10160.573261386387
17644.785153441542 23787.12368068069
18483.159154010984 21266.077870637077
13921.93845383968 12044.314218750687
15464.770762032724 18082.153024460335
10998.204080666988 9301.235240547354
16807.501673360024 20358.000392965907
15000.214406800991 15277.713997846668
7547.721841721514 7547.465799856267
18474.933296564293 21263.477725903635
13938.663538876315 12065.01127226991
17635.978031033923 23775.24174430199
13970.083289782377 14606.487360073948
10984.639401353956 9285.131393792983
13980.746297129182 14615.31587068853
7540.725843710273 7540.094495429086
15019.143159647956 15300.562636713723
15452.210072960077 18064.42692143872
12839.395040265721 11821.99242936655
10764.796791393695 14124.933451170664
11878.764327993043 8566.958912006057
11080.656478747096 16304.251838094258
10763.994173168248 14124.321859827465
11878.03698259944 8565.950501841578
12838.273559945668 11819.799829100322
11081.955829184666 16305.841437963267
11885.035371330527 13051.60442244554
10202.659484786307 15543.002026635653
10107.781020580134 8766.44568796271
7306.34212326676 8844.008141108872
7002.602239167952 4228.001892147164
7576.3181443891335 9648.098310029805
10203.343376682958 15522.557843345277
7584.389267600919 9626.094742937034
11219.197035661688 11714.857105402523
11220.270286962788 11696.657300271732
10106.567395510703 8767.462688828507
11898.931123798007 13053.301804524403
19906.318594858265 20740.003085824264
10636.80610897839 7872.007685463728
10450.612998288667 13060.65086433291
15670.851228953708 13942.827833692849
15687.749208857209 13961.817396026923
18183.859657399473 19799.445472032796
15060.517090724343 16975.99670122494
9715.206688485841 12480.004847755468
15078.099085760115 16991.596776053746
12376.725537879558 14647.47841780284
18692.48927350234 17269.51142910534
10442.306143759626 13053.887696774475
13112.579389273491 10989.38615210149
12390.988339918653 14659.53208666634
11312.45840832133 8763.480187687994
19925.534798343557 20761.283799418572
19104.99536770423 22889.511659273117
19125.016732018823 22908.795712564202
11304.78486305688 8753.397511823623
13126.042634396705 11005.447060433302
18673.580755709387 17249.043103894197
18164.42168195839 19781.595082298092
9913.151700644958 12508.03006072499
9139.200008753502 11904.0
10208.250829598575 14165.883558747757
11562.853670266695 10592.386747093406
11563.296415814999 10593.111724134698
10768.718430714027 8244.829652576213
10208.752323374292 14166.425660695078
9912.919297563156 12507.723094152669
10060.800007951653 7296.0
10768.504492268181 8244.363953635235
44093.58483952059 47406.506895151004
18490.871264251207 18972.08728632672
43941.488368055994 44639.8967740742
35670.56198393852 36309.83470080799
22892.230299001014 22105.567828038256
21133.959023334934 22195.7314815259
43941.488368055994 44639.750548138145
22892.32674937172 22105.863113662854
24674.62243378812 25590.078077254864
37533.854159445174 37059.305565539136
6804.49733632103 6804.49733632103
37533.854159445174 37059.48170171839
27940.851814343656 29095.44459189445
18490.871264251207 18972.08728632672
35252.23397334006 33286.20328304206
25551.954915426726 25799.54232152191
44093.484691618556 47406.506895151004
19406.02463798292 18471.956691157546
35252.324746036255 33286.20328304206
32796.39004694131 32676.121189639383
27940.966339767136 29095.44459189445
32796.39004694131 32676.121189639383
39402.53555372421 39982.127207040896
19406.1384119175 18471.956691157546
39402.59158989418 39982.127207040896
18556.578995062642 14941.061843122128
41275.92770686687 40845.038670565606
24674.801397377043 25590.078077254864
43153.41710759995 43683.2702072544
21133.8545481533 22195.7314815259
18556.578995062642 14941.061843122128
43153.46827312957 43683.2702072544
25551.82968225781 25799.289311917102

35670.6238810383 36309.83470080799
41275.92770686687 40845.038670565606
6804.49733632103 6804.49733632103
13476.19645597377 12274.086564791696
13021.230295175643 14545.74869162808
16523.527722614203 17715.339398385797
7190.162579524888 9637.013334015886
6994.801646937532 4244.000117813382
13479.879239815169 12275.964361303759
7977.409002928206 5715.340759744777
7189.095319996807 9611.214283325495
17609.13899403123 21145.886715860368
9787.741099967858 11718.118108297083
10394.405081581148 8772.868402067821
6076.601895796696 8835.000056593095
18166.206948311716 19660.341451765278
17605.175608957223 21136.121356578173
16517.47354167701 17713.605900550006
9799.364309994808 11705.080478151356
13019.461156284464 14532.580362757331
16878.248114066817 15923.731786236542
16884.795444422773 15925.66011190745
18170.583568565493 19666.38617031609
10387.55880657241 8761.940481423051
7983.530291794477 5716.680505328245
6372.501417222283 9268.004369873808
7850.2151324024235 4411.434460580821
5407.333990876547 10736.490301769942
5407.333990876547 10745.588304043664
7849.0696303765835 4410.819084931959
4608.000027126736 4608.0
6515.9890270011965 10302.90682283403
6516.696095415222 10303.801240319031
6516.342551615899 6515.9890270011965
6516.696095415222 6516.696095415222
10601.808147669906 9969.219829053825
9330.84004792709 9295.655759547037
11670.25351052838 15291.773507347014
10614.733837454427 12057.04843649556
9329.948392140226 9295.036148396626
11039.648039679527 9968.256868680703
10119.288512538815 6356.33101718279
10118.466336357502 6355.424848112044
9978.460001423065 12057.844583506623
12309.7620204454 13705.18387326489
10820.354153168924 15292.652353336225
19129.82162024054 22920.021051473752
11287.153201759953 8746.192142869948
12381.359435861637 14647.211509362456
9677.326087303249 12442.096487328814
10426.574979349643 13035.631361771473
19853.688221587443 20690.433924884223
15683.941322256978 13961.817396026923
12323.355867619828 14595.213736016338
13059.535268913669 10935.650689373724
11256.184682209154 8702.62351248174
10393.042480428916 13006.439328271208
15075.05728678999 16989.559293872222
15617.152795564241 13890.01281496889
18111.993259716062 19728.13888839999
18188.599463400147 19805.066144802444
19053.21495181325 22836.940775856998
10598.915123728464 7834.1532407784825
18620.705181061214 17197.896848161407
19932.821556975374 20761.283799418572
18698.290682305695 17269.51142910534
13119.288811517185 10978.298456500443
15006.96837605784 16922.300789195302
7099.797678807474 9790.117466098147
7270.129572435419 11195.427638102978
7990.93951172201 5348.501098438702
7099.635427259627 9790.117466098147
7990.843402294904 5348.142200802069
7269.836158936306 11195.427638102978
8675.59581687493 7621.426703708434
8675.718759849238 7622.182364651216
17265.869856132034 22165.428058126916
17921.81028802615 20512.632693050396
17931.90527771349 20517.731502288454
8700.591244277597 10539.911195071807
16388.71944967025 14906.36407713162
11572.11700251946 10494.59980180283
7738.840756211488 4636.584950154585
14772.73994746931 17103.467046186863
11560.353461724257 10480.870192879978
16377.658562810497 14897.410378988692
17256.709986424285 22157.24468430134
6599.306043062406 9039.776158733135
7740.701276370249 4642.790647875478
8711.264546551207 10548.104711273963
12831.063481352588 13052.560859846622
14762.11286066839 17090.362781404026
6597.123634585 9036.59050748677
12819.238081883026 13038.814670053409
9022.000665040987 9022.000665040987
8164.000015311122 8164.0
9021.787863278541 9021.575084207856
9021.575084207856 11207.940801057079
9022.000665040987 11208.625963961862
9859.473426608543 12124.72783199689
10383.987673336289 13765.208316622018
12124.791150549541 8955.827655778108
10383.65489603733 13764.706208270483
9859.590267855961 12124.917814154453
12124.981159206438 8956.342110482381
12630.934130142552 10387.870667273442
10736.823449129532 15512.246130074136
12100.000080991736 8644.00005784359
12630.579471179371 10386.207199935885
10948.000089514066 14404.00003471258
10737.240660430407 15513.359951989769
15275.687414974162 15309.582130156263
17639.09714242767 21052.893981588375
19271.846934064208 22476.834385651375
13086.785044463746 9714.525207131845
19841.71979063307 25213.68049293875
19997.856991437857 25429.20574850894
17422.299010336024 17454.533050184986
17580.844895510567 21000.99245273899
17283.58745634456 17284.923633039285
19405.868294152675 22622.04290067544
13911.400221081669 12519.279571924257
14029.734835539677 12753.291731941208
15341.375982331247 15373.58526824501
13013.545412377058 9609.73886221681
13845.316897781719 17052.36734298203
14592.0 7296.0
13845.316897781719 17052.36734298203
13356.425869221152 12502.134217804574
13356.425869221152 12502.134217804574
11904.0 4608.0
10671.55621266177 9872.609381516115
11162.45134367895 14393.598577145327
11162.45134367895 14393.598577145327
10671.55621266177 9872.609381516115
18183.859657399473 19799.445472032796
19104.99536770423 22889.511659273117
13112.579389273491 10989.38615210149
18692.48927350234 17269.51142910534
10636.80610897839 7872.007685463728
12376.725537879558 14647.47841780284
10450.612998288667 13060.65086433291
12390.988339918653 14659.53208666634
9715.206688485841 12480.004847755468
13126.042634396705 11005.447060433302
11312.45840832133 8763.480187687994
15687.749208857209 13961.817396026923
15060.517090724343 16975.99670122494
19906.318594858265 20740.003085824264
15670.851228953708 13942.827833692849
11304.78486305688 8753.397511823623
19925.534798343557 20761.283799418572
18673.580755709387 17249.043103894197
18164.42168195839 19781.595082298092
10442.306143759626 13053.887696774475
15078.099085760115 16991.596776053746
19125.016732018823 22908.795712564202
8764.962977674235 8764.962977674235
5708.570398970306 5708.570398970306
5708.234074562815 5707.897774137165
8764.08677501541 8764.08677501541
8764.962977674235 12269.986797058911
8764.08677501541 12269.04792557271
4224.000029592803 4224.0
9095.335123017732 13043.965079683401
6363.569140034545 9038.074186462512
10138.004586702455 10487.276910618886
9055.90450700536 7142.006510778326
9056.540478571274 7142.812891291497
8365.225450637898 10543.732972718914
9096.109058273212 13044.700993123606
7247.845307399987 4639.889653860316
7247.580410040306 4639.4759402329055
10138.69893033618 10488.192217918206
8365.913927360238 10544.279207228914
6363.870834641445 9038.286563281781
10794.727613515775 7544.148527169915
14270.68607320615 15292.024620696895
23364.399696974884 24242.883017496082
10794.816545453656 7544.402958485184
16787.686488614207 15291.773507347014
16788.48702653101 15292.652353336225
23365.554726562776 24245.71846739131
23458.552615464152 26824.099108823768
15070.471260050232 12057.844583506623
23379.109702895017 28686.832170875892
23377.891154090437 28684.214352148465
23456.7118592952 26823.648409565765
9647.930360963433 12057.844583506623
16252.955935459864 17953.796701533633
14271.425997425766 15292.652353336225
15069.770568923735 12057.04843649556
11194.913175188096 13223.891144440051
11195.427638102978 13224.32667473093
19547.09230652989 20982.58937786278
23741.517007133305 22345.035444142843
19548.443826555605 20983.41287779469
16252.129018685522 17953.048125596946
23740.102646787356 22343.763716079706
19995.95507196393 18757.132403435233
19994.587708677565 18756.21115790713
9647.830857244544 12057.685391483723
12589.183929071813 11748.140959317776
12589.183929071813 11748.140959317776
13824.0 6528.0
13078.568729031476 16291.740238538056
13078.568729031476 16291.740238538056
8135.870266910602 8135.870266910602
46157.335115883805 49991.3182962802
4686.907749252166 4686.498159607022
30837.375763835676 30837.375763835676
27013.070632566007 27013.070632566007
23195.27678213821 23195.27678213821
15593.42630726166 15593.42630726166
30836.37957024138 30836.37957024138
11829.443942975511 11829.443942975511
23196.270044987836 23196.270044987836
38493.965033495835 38493.965033495835
34663.37873029691 34663.37873029691
2688.0000465029757 2688.0
46158.33341878799 46158.33341878799
46158.33341878799 49992.31684969201
42325.440860078466 42325.440860078466
34664.375719173135 34664.375719173135
4687.317356441742 4687.317356441742
38492.96747459203 38492.96747459203
27014.065669572952 27014.065669572952
15592.441277747368 15592.441277747368
19387.246942255624 19387.246942255624
42324.4428787905 42324.4428787905
8136.814118560163 8136.814118560163
11828.470103948355 11828.470103948355
46157.335115883805 46157.335115883805
19386.256601004745 19386.256601004745
12085.170582163912 16695.469684917523
8928.721423025807 8928.560242278707
8929.689034339326 8929.527703075903
12087.31504512065 12087.31504512065
12087.31504512065 16698.056922887765
12085.170582163912 12085.170582163912
8665.372430606265 7761.000257698746
8161.234589679295 13227.116276800472
9126.627804397416 4401.060099566921
8521.548565841775 7595.991047914683
10031.385628366601 12343.245035240936
9193.53584046965 9606.420405124898
9606.223769573095 13559.736317495262
7573.1568714770465 7142.006510778326
6588.879554049973 4639.4759402329055
6589.365177651368 4639.889653860316
5707.897774137165 10543.732972718914
5708.570398970306 10544.279207228914
7573.663842553352 7142.812891291497
8365.983149785803 10231.638187504483
6261.471188502303 4275.4093371278495
9103.762481111862 6924.327548578273
9873.239528026137 10332.646369638322
8365.824264530065 10240.562728678537
6252.065863021243 4278.522759084028
9868.412120385821 10326.146425458048
9099.498011566353 6934.323326756548
8861.058878285623 12776.184093852124
8860.39433534297 12793.998358605491
8857.277064651416 14012.294922674158
4419.627727535431 4409.858274366649
4415.504982445383 4422.916345580143
8859.77067987654 8857.277064651416
8861.611591578589 14009.114889956467
8853.999802349219 8861.611591578589
24773.029260064257 28372.574380905233
24892.087404635233 28531.035820663783
30437.124304348585 30673.866417522262
24192.90416630463 27935.80442729366
21339.0430113589 21716.196927639056

26284.154410626044 40925.19734833297
26051.146659024434 30134.87099690324
26441.35706199665 29959.098551191422
26697.691925312363 34884.5531718553
14904.19261745248 14538.787879324742
26215.389388022162 26021.77503553514
33691.829837514015 37970.48792154244
24706.662004406826 23163.2679257483
35246.47264088989 38856.86400110024
22219.00865125275 23545.657710074698
15809.186187348481 15395.748796339853
29111.649012723414 32253.561121215746
17385.673506232255 18306.20992996639
21974.200349856306 21669.924434570603
13345.447878583918 10117.454274668109
12049.90315811708 8404.093347887088
25471.548552846172 26380.73624825509
20146.8138225378 18149.450928333892
23856.500883210534 24240.327658676564
32181.910408730484 35464.52967402782
16086.228507639693 13590.55885532306
15981.0363644305 15575.462272433522
33998.121176479915 34642.136842290776
20507.208153232365 18561.631501567957
35223.75805564335 41278.30153967094
16415.32657731792 13946.27785468223
21622.601316536307 22034.402646770344
32416.85588332095 35336.54178042894
23370.20167273894 24471.373520912144
22113.33560497206 22474.71299038099
28689.448174590252 28278.35543308698
21987.530250831947 22284.199806140674
24829.453039145676 30891.586832016255
18324.377658258956 18040.256594627474
26772.7355963581 27032.14212747484
30344.87900088127 30635.03380118912
13154.325203521465 9841.03780096388
6594.776805253618 10546.992462308865
7972.676429182639 7142.546954693403
7976.543396456611 7114.491478665218
6367.3575115584645 9023.804574568312
7250.401544742194 4651.762354205124
6583.186293716575 10568.036809171323
6368.507545728434 9035.745126994232
7245.218652325131 4658.927988282283
19446.633534882072 21735.892528258417
17444.62094056503 19961.617018668603
29857.732824922332 29515.904136583722
18307.007028089836 17994.176446839683
21926.807701988906 19148.08982640305
33992.17888435695 33687.10993837257
15666.000250223411 18430.00043407487
31614.520308119496 33681.6853794462
17338.508355680427 15814.087896556033
28850.636636173214 28415.054055904944
32078.012034898784 35824.51095269829
14940.469916523061 14344.159403743393
35495.487037086845 39168.0
28872.61268399519 26869.028862242118
34484.48282691796 35825.368441929524
19445.690601261762 21730.912406063395
17126.846898785672 15812.146786568863
19991.678994021488 23997.44188450094
33885.64479067795 35065.10881203707
31753.87749551226 29516.838855134876
17027.026591862716 14347.424019662903
23183.376113068607 23658.887885951022
23600.385081604072 26615.38322098707
16130.529424665514 18827.75143239362
14672.309065942232 8993.03202485124
31113.17640614664 32602.568564455163
16126.89761237418 18824.774235034
18452.763814891343 13943.483639320555
15259.461884352279 11949.670497549294
17448.310973845004 19968.0
19791.38002073125 20661.12448537107
20719.013450629038 20664.76653630522
26041.200536606506 24068.25494297416
30253.321933301802 30226.4350527812
27195.49703903203 26869.026331447145
28396.81135659816 24813.910957364216
31612.437046200663 32592.530187145643
30052.847562795992 30227.19953948761
21940.618857270183 23993.08700438524
15268.600173231336 13822.000578787429
19065.609667671266 17994.815253288933
35720.837616159006 37222.25914691369
19087.167311028206 16464.198279904187
8887.908710714799 11693.0
8756.706750320642 12567.843808704816
10272.435013720511 8451.13448005651
9667.44191862563 10458.823308575396
10031.3098471735 7085.0
9300.718831239754 12564.020733825617
8813.361422436958 8061.045341641492
10040.07003212627 2744.2494420150656
9306.90849733561 12550.262626734151
8808.475818778184 8082.448700734202
11904.000010500673 4608.0
10671.529236712047 9872.609381516115
11162.405495431729 14393.598577145327
11162.47428266292 14393.43853983474
10671.569709396083 9872.376056451658
6999.000140020002 4217.052288032483
13028.033404931075 14535.032886099707
10397.847902330559 8804.23903582814
14744.342240707489 15917.513781994976
10400.703533896156 8785.612613813564
6071.60277027409 8854.01270611241
14045.09778455735 17729.38930138317
9805.38715808815 11727.592165487338
13482.804944075991 12284.02311948329
7995.947886273396 5700.16227839173
9807.198378742014 11717.46307867023
7994.929205440158 5706.82573765837
14044.181745081802 17711.431901458447
13486.86291766918 12289.482373151443
13035.399532043502 14522.414434246119
7194.818438292937 9657.465506021754
14747.068654105089 15929.855052699004
7195.3366286783275 9651.327836106284
22416.498638279798 24230.695780352657
40859.92015361753 40024.80202324554
29927.73943885505 28833.378227325356
14000.675505131885 11315.035307059365
27715.06219007996 29180.228511785168
34897.005283803046 39800.75758072954
40549.90973948031 41571.40911732485
19656.6947628537 17915.204994640724
15245.738397335826 12838.92522760375
14387.856697924122 17086.73602535019
24166.051127149425 25786.41745182917
28156.942824106452 26986.32618568152
35500.40115109812 38165.831747781944
29501.358775486933 30956.027942874065
18123.512438818256 16172.585476663897
19006.743221288594 21132.90978545075
22977.70488190672 21440.10552679254
11205.738831509505 7873.140415361586
35359.19036403407 34424.60650465013
33550.34769953957 32539.12183818119
11705.00829047122 8783.390063067904
24674.14853242154 23259.54361117174
42317.500779491005 47057.443970109554
10570.673887695146 14265.781611955232
10005.487314468995 13753.855641237478
35009.768008371604 36163.42440920107
42807.078760410644 45710.99260571794
17406.2906812451 19723.053845690327
13054.868831206233 15999.396051101428
33171.962962718986 34426.451240289054
13356.425869221152 12502.134217804574
13356.425869221152 12502.134217804574
13845.316897781719 17052.36734298203
14592.0 7296.0
13845.316897781719 17052.36734298203
10671.394707347301 9872.376056451658
11904.000010500673 4608.018337637123
10671.704997913876 9872.609381516115
11162.405495431729 14393.598577145327
11162.47428266292 14393.43853983474
5708.570398970306 8764.962977674235
5708.570398970306 5708.570398970306
5708.234074562815 5707.897774137165
4224.000029592803 4224.0
5707.897774137165 8764.08677501541
9187.158497054463 9186.715245396474
5044.028746944252 5044.028746944252
9187.601754538558 14226.943803923596
9188.04501784792 9187.601754538558
5044.028746944252 5043.490557143931
9186.715245396474 14224.080884190726
13055.300543372328 15946.268403610922
8558.074608228186 7143.734667525104
11352.306003845133 11886.072395875772
11835.177789644733 10471.240661927315
14989.75103566137 21212.56281074967
11363.365705656657 11893.998528669827
4628.059744644617 4628.059744644617
4636.345220106026 4635.513455918341
13104.793207067405 14092.425802536623
8545.240085047997 7125.98631769666
15738.019506913823 18347.768174903453
14980.374364851872 21201.555886302307
13086.832093749808 14071.4349303829
13733.252330111029 17286.001417331885
13068.455153961815 15962.437940364875
15729.575681657785 18342.74494180192
11851.304949245041 10491.382416059383
9374.363018360234 13687.661012751594
9371.373565278465 9374.363018360234
9378.733603211043 13674.686285249838
7394.500828318299 7387.003316636591
9360.360262831768 9378.733603211043
9579.060946930027 8801.372449794408
9574.708615018004 8820.599752851276
10074.507718880252 13298.784493328703
10064.62443964558 13323.9814244842
10807.827767988349 3512.205574848944
75443.22659825438 74805.13180257088
22915.75761590943 23899.999686192466
80879.81959055053 83412.79096757283
77396.43403647548 77145.78158266335
37157.432863425856 34742.042786802274
10339.423702508762 12506.495952104251
40943.96248609189 41798.6763546407
80489.0332964684 82312.17689382295
44811.39786441057 45743.077126489865
23962.87797823959 26808.590861886045
49734.713459402665 49459.15786788125
62189.398624283225 61871.68347475281
77396.5580759248 77144.78606490526
37158.38015845147 34742.98225541382
23962.87797823959 26807.80306179527
10340.074322750297 12503.916226526791
80033.40743089725 80968.38850440337
38276.20045145547 38301.05253122948
52719.056246887616 53178.70124401309
52235.8182455083 50450.496617971956
11293.446673968836 9296.275436969367
72425.00519234438 72028.81035391324
79614.14708890906 79614.97105444428
37308.56932395023 35320.760141876905
15979.229323649428 16568.27667562321
9790.019624597287 7546.1874479766275
64836.21845508539 65686.45230182553
72976.1554593348 72024.86532441418
22384.846325137012 22343.763716079706
19194.743332485592 19429.84451816329
18006.735483639943 15291.773507347014
37309.529935393184 35321.73857555712
12530.465775682704 14164.257552021567
11292.105703641913 9299.37481769608
22590.67984872916 22589.971602461123
60291.428346511246 60708.53412824263
42254.41378654358 42864.4927299974
18002.536281189816 15292.652353336225
22590.30872471153 22588.271846248
52723.171476709365 53189.34293634393
9599.00032555474 11906.0006719301
62184.265576691505 61865.72534125822
23687.436691208273 25932.61916968666
52240.991828469545 50449.36250340533
67360.91846579555 68246.03584824543
19766.17723062555 18757.132403435233
80490.01925704826 82313.15656685752
54603.83330923297 54252.96129244928
64081.81273380147 64468.926127243656
78101.95430053271 78554.98802749574
15978.027753414652 16561.994596062395
43111.17790601927 45351.728357362525
74959.11723140228 73322.89749457533
42253.12121541372 42865.478138007515
76059.94154323287 75818.69585399106
12532.821979816747 14160.84195943165
56504.057426214975 56941.212711005726
39582.29907736538 39086.97501726118
58397.7671838787 58060.12926268766
38277.13677902254 38301.95483261918
19767.828410386912 18756.21115790713
54610.944040549235 54252.77771690589
41418.94680843539 42042.46543674621
58390.78031354779 58054.288833814855
39581.571470350944 39085.99259325519
64085.55786310204 64474.39418870099
80034.3990044281 80969.38443634112
38372.635252872584 38372.15992096353
9789.873048844913 7544.657513764293
67364.03663099637 68246.09792508287
80880.80870021021 83413.780731963
22913.402281440245 23900.72266689859
44738.69425030443 45738.24941993298
79613.88261757145 79613.9822958254
75819.38370323839 75815.37338165658
60283.824995806295 60699.70906849554
42040.86697620675 42042.46543674621
38373.427474114316 38373.110585408635
79227.06609977286 78554.01036866292
56497.63482770761 56928.56788994432
64832.448203897955 65686.45230182553
19196.005984579187 19435.99012142165
39478.82335857767 41799.595021961635
49729.94085502661 49454.31250154025
23687.436691208273 25933.507591531077
22384.846325137012 22344.708903899376
74956.99070504069 73323.89253169802

16787.887777799802 14777.349187185095
16039.626480688383 18471.270692618848
18497.53629540972 19793.390437214137
17355.678753652937 22684.710643955765
12892.931088003224 10137.284892908949
16039.626480688383 18471.270692618848
10412.728750908667 6705.355546128781
12892.931088003224 10137.284892908949
10412.728750908667 6705.355546128781
9157.584923985145 12952.975912893531
17355.678753652937 22684.710643955765
16787.887777799802 14777.349187185095
18497.53629540972 19793.390437214137
11902.273465183029 15019.398689694604
9157.584923985145 12952.975912893531
11902.273465183029 15019.398689694604
6071.731239934785 6071.573107523288
8145.1630431809035 8145.1630431809035
6071.415012169733 6071.256953877014
8145.1630431809035 11194.570157000224
8145.870119269028 8145.870119269028
8145.870119269028 11195.427638102978
21456.192142363005 25258.02021141008
10368.00090556409 11904.000672042992
12918.192307749563 14168.59456685807
14516.770233078707 16568.322787777888
15304.31593538241 13631.831901839165
15310.312096753612 13639.43517892145
13795.881577485363 10596.012080023314
10060.80096215008 7296.001096491145
21466.252700459856 25269.177825960225
13790.167837992401 10589.48728692754
18034.496422135 20425.257819670234
22788.330215265883 23120.673389847452
10337.846015974508 12506.495952104251
18043.291380454953 20431.242350870394
10341.002659316939 12509.258651095195
12912.13479638437 14163.71564950384
22796.81699272949 23134.68884597327
14510.408066281252 16562.0180231758
12133.697869981765 13224.32667473093
12914.810141848777 15292.024620696895
13906.102855940624 12057.844583506623
13575.743110415724 17953.048125596946
12133.01219813118 13223.891144440051
15028.966165375448 15292.652353336225
13293.525642206434 9295.655759547037
13254.620954218193 15292.652353336225
14013.515761578177 17953.796701533633
13292.899796507909 9295.036148396626
13792.672873667381 12057.04843649556
13845.279933769647 17052.36734298203
13845.335391788496 17052.232258563687
14592.000008566338 7296.0
13356.404315907781 12502.134217804574
13356.436652883882 12501.949967905006
10956.893720393567 16217.41264813842
10924.123741518128 9365.625286119448
12628.248092625077 13429.302029517394
10937.499450971414 9362.317715181429
8134.207710650128 5376.01339284046
12634.210897400755 13443.228332510014
8448.009002783503 9984.007211535856
8584.050329681204 10701.315806946359
8581.364241774148 10692.342353291911
10965.61992376628 16228.946607836258
11922.87585117366 12602.600525288422
11914.038662435169 12589.432751319657
4454.40001795977 7680.0
8509.834310960467 9499.63536142309
8509.11235088596 9498.665222019355
6408.5734855738365 8955.827655778108
7384.16901215025 11996.54350219262
7383.336982692853 11995.77529799554
5529.600014467593 2304.0
7197.926101315573 5151.900620159516
6409.0048650317 8956.342110482381
7197.5420054349115 5151.006212382198
27824.68746005964 29999.98433332924
20390.03406351032 20225.069443638506
23228.873446878802 24338.391442328313
17869.477556017133 20961.977960106724
21315.25367108025 24170.26464480685
16948.490808754756 18785.184720944322
28722.82196812319 31421.413462796354
16588.914144090322 13360.72789933243
16592.152014732746 13384.844040929278
19020.85657902924 16275.130291337147
15696.80004586922 12245.036749638606
29830.504730895856 33664.02455144067
23739.774185694252 24337.508048278072
16957.104853128672 18771.20741987579
26542.680260290217 28696.006586283045
17602.756633865934 16314.7168531973
27823.962127993203 30006.791897835396
17172.14406044432 17998.0006945216
27162.89893402396 31421.75623672235
20253.758860003833 20967.619154305525
14254.262717205373 14213.188241911103
25852.356178886286 24427.048614189967
15135.069492097227 15971.358395578005
34275.414611583015 33495.52962710099
32411.636187124685 32027.76395566821
20182.844199963492 23124.64451618662
22265.7922383193 26427.738155203522
12837.575300655493 10202.794960205758
22515.152097198898 21122.599863653148
34101.4918148752 37262.842403659975
16614.264842297416 20174.435555920765
20604.755791430525 20645.376455758804
22132.564085527913 24048.97469747931
30380.286629218448 30064.13625900468
31060.1171923095 29884.231025743327
25321.103332990842 24605.060963143336
27764.91433302109 29443.129062652293
14356.368065774854 12057.239526525133
33967.45359899679 34997.760842659634
17330.432963271414 20914.784818400596
30976.488674476972 32501.779182069404
26577.62051356865 27007.24169551567
16640.200971142145 14701.980308788337
16416.84971728742 19127.885324834002
12245.958085833874 9602.680927740961
16384.008173826085 18818.000425124876
15083.929256081425 15438.996858604512
35317.53255034168 39010.19353963782
14619.891306987374 14622.048043964292
33908.15850204785 31817.797299624624
19421.08323343474 17787.93481548659
24731.257617840627 26603.48114439161
26639.036518858207 26741.658306844023
21187.11118407912 22346.358629539624
20935.925104948194 19148.08982640305
18321.669792898243 18321.669792898243
32980.43638280124 35437.39584111677
17538.205591432292 18051.467779657145
23575.43923537004 23579.33775575557
34319.553937077915 35699.7125058452
34893.599602219314 37008.62311678185
34058.57885891437 35497.7552107172
16572.169441566784 14246.865760580466
34616.48717013325 39844.51058803458
12550.862097437326 10278.726769400964
17004.28184311234 17486.828900632612
6303.2361579192 8244.829652576213
4993.5016020824505 7296.0
16999.87875773759 17487.817016426034
15807.54969064536 13705.18387326489
9098.480611862864 10611.862089190568
15805.851254800828 13706.164452537405
18163.701103513507 20539.513528805885
7303.99392265781 6356.33101718279
9095.572946341656 10587.141115523114
16988.101390090655 16987.896514871994
7292.70823798981 6355.424848112044
13454.104309755361 13645.7017774829
16989.11266995719 20983.41287779469
5348.5908482982695 3303.2929025443686
5348.466906506947 3302.711764595875
13454.294981322671 13641.944472838173
16985.56368802637 17003.837713880945
18168.32234962821 20538.57874829707
16990.125841941255 20982.58937786278
6295.706399007184 8243.168626201941
13845.335391788496 17052.232258563687
13845.279933769647 17052.36734298203
14592.000008566338 7296.070175101114
13356.093892396086 12501.949967905006
13356.751410803452 12502.134217804574
68083.00890089979 65185.19587298945
38819.82542929722 39507.09113564298
84925.84589739975 84791.46745398383
70621.80477334493 72837.03520188064
28080.901780614167 27573.23223708095
12852.950517293684 13055.117655540298
84379.486508702 87446.42794305552
25424.500995902064 25415.35647989223
70621.55422390532 72834.60277230872
11079.819711529606 13212.590397041755
52908.67321568785 49915.56903412
53971.5091243519 54452.9113271274
26011.42738831873 27579.181750008465
9996.479430279442 11416.804500384509
39046.54230428093 38501.38698800343
81366.24802213753 79904.03243892013
84924.46856537349 84778.29668612126
38258.05751200441 39383.33048384811
37873.73699250944 34723.87812442613
11757.949236155087 9835.198828696855
11216.44604042554 7245.297509419472
69199.6597089899 69575.72439436043
11761.53724816616 9834.417979728134
83326.69903324971 80489.83638323536
11800.2576666783 15757.311477533216
24704.998420562588 23852.172773145845
26260.82881403403 27701.456315508036
86085.62653290328 88602.17172281952
41560.76707665536 43220.90827365848
24699.662064894736 23850.034989492153
83330.12064807193 80490.83346568105
24984.197587897655 24587.99707174214
42862.84790631626 46521.501792182076
69312.41758992395 69011.5614734227
11219.708418671138 7244.7675601084675
11078.49463420008 13201.781849432295
53969.83888840136 54450.744026137974
55192.785950701924 58216.507358308605
54116.50294725261 53728.44788377941
85878.65771670062 88148.98452052638
55194.054752300995 58217.49015545071
67891.92238403624 65779.68173379984
24048.647520390827 22009.10543388804
23630.266020978735 20164.88455211187
26252.664021009372 27682.31610613534
25430.39458041548 25428.225301817663
52660.218001827525 50698.16707732144
86084.49190185187 88588.68318809124
70438.09425855996 73368.26824315809
54114.56071151276 53727.45444370131
81363.20961933595 79902.26360373027
55427.559110969334 57543.93939417078
69198.2042486653 69575.51112999459
82269.17030432785 80970.70821599623
27239.270354479846 30951.63040939847
11797.980410976184 15748.493388257812
52658.93676290853 50692.298478171215
41562.10873575233 43214.70872284112
70436.04421743174 73371.53500506855
23636.625388954697 20158.133271709463
68085.62682387524 65185.34375916108
82271.74484938617 80973.02661998007
38820.159619569946 39513.7752182704
24042.29287734429 22005.578928989802
84570.58252915135 84318.6847145993
52906.00163497521 49914.57663849309
40363.298532756766 42296.61735883852
36025.144952935305 35820.1756835446
39044.159283559944 38508.137763335166
84565.6338790173 84321.55331823531
27251.689213698293 30958.20151429989
40361.64520652965 42303.39790135067
85871.44561364842 88151.68491866732
37871.86535029812 34722.7169731863
24995.37321185663 24600.34068869779
69311.47738751498 69009.04984855247
55428.8779608608 57544.93367795292
12846.957270541188 13056.0
67893.02922244668 65784.5954004431
9993.534999077043 11417.140797940612
26831.55122537644 28949.71752884646
84376.22263871368 87444.72384884064
38256.01501218136 39380.81422469576
42865.808278860204 46523.79692157552
37839.46474251453 35827.42636584437
26822.189442325543 28940.433047900304
10450.612998288667 13060.65086433291
19125.016732018823 22908.795712564202
19925.534798343557 20761.283799418572
9715.206688485841 12480.004847755468
15078.099085760115 16991.596776053746
15687.749208857209 13961.817396026923
18183.859657399473 19799.445472032796
13112.579389273491 10989.38615210149
19906.318594858265 20740.003085824264
19104.99536770423 22889.511659273117
11304.78486305688 8753.397511823623
10636.80610897839 7872.007685463728
12376.725537879558 14647.47841780284
13126.042634396705 11005.447060433302
12390.988339918653 14659.53208666634
15670.851228953708 13942.827833692849
15060.517090724343 16975.99670122494
11312.45840832133 8763.480187687994
18164.42168195839 19781.595082298092
10442.306143759626 13053.887696774475
18673.580755709387 17249.043103894197
18692.48927350234 17269.51142910534
5402.333590423884 10742.288815704034
7853.090637608864 4652.546936893813
6553.675094937191 10731.164568675666
6367.5030673333795 9263.003454603695
7853.854316512371 4650.550505047762
29998.18661186039 27014.065669572952
31199.198528808396 30836.37957024138
32759.17955321836 35320.760141876905
31581.89526365453 31574.515293191755
26878.64138638294 27823.43071944939
17921.10052598612 20538.57874829707
28999.740757461954 27852.576469691274
8610.319390127175 4687.317356441742
17922.124985614846 20539.513528805885
31105.8072623818 34878.30180785756
31106.78454042533 34879.23760634685
12379.102287322776 13636.055734705693
16298.084143849546 15592.441277747368
32760.16123281447 35321.73857555712
9418.886762245313 8136.814118560163
31580.91242260813 31573.542357486593
16299.160341563611 15593.42630726166
26879.593779999315 27824.32777265248
28998.764197806773 27851.611389648537
12378.098480784518 13634.675867067761
7668.2576899840815 8244.829652576213
12745.329648149553 11829.443942975511
32514.267637454177 34664.375719173135
16727.130908928895 17004.74098597212
18793.415070178173 21207.438718525158
9417.955604057603 8135.870266910602
16726.135468016644 17003.40865826614
18794.468453362664 21208.25348773444
8916.109128986702 10592.386747093406
12744.254656903242 11828.470103948355
32513.283454612825 34663.37873029691
8917.072021689632 10593.111724134698
29997.20521982006 27013.070632566007
31200.183137924047 30837.375763835676
17607.671087089035 19386.256601004745
8609.576121970233 4686.498159607022
17608.725110012932 19387.246942255624
7667.4231003642935 8244.363953635235
5153.490467634533 8931.61217250279
5153.40768596642 8931.182284557852
5299.200015096618 8064.0
6220.8000128600825 3456.0
6652.242537504009 5165.44838324806
6652.306667615377 5166.191634076305
25272.50017311307 25264.420535606987
8145.870119269028 8145.870119269028
25273.437122797524 25265.33245377943
27684.596222448323 25615.02061291382
18167.097193675287 18531.73019445297
28984.369856872858 32422.427793118764
18274.90697650743 18213.77064201699
28902.502037020946 29370.35239829444
6071.415012169733 6071.256953877014
18274.493894800784 18212.191081800123
6071.731239934785 6071.573107523288
15856.831685778565 14619.134858123445
18168.32234962821 18530.901354224516
20553.36237699321 21819.647682765182
28981.96857099255 32421.480302416792
28061.86770445795 28809.30518079185
11194.570157000224 11194.570157000224
15857.17052314189 14621.365223535044
28901.549871935935 29366.430086069366
20553.119644256225 21820.527582989373
28063.54389595156 28810.238180202537
8145.1630431809035 8145.1630431809035
27686.491724304833 25615.99500312256
11193.370180602444 11195.427638102978

12695.251395699102 15911.692304717308
12695.251395699102 15911.692304717308
12205.598715343709 11371.847343329931
12205.598715343709 11371.847343329931
13440.0 6144.0
9603.000013016766 3825.1887535126943
9002.466945849405 11787.298927235195
9002.559345973665 11787.087214405432
8659.545084038768 8081.126901614651
8660.967851516365 8080.818089772842
13356.404315907781 12502.134217804574
13845.335391788496 17052.232258563687
13845.279933769647 17052.36734298203
13356.436652883882 12501.949967905006
14592.000008566338 7296.0
16088.277696509344 14306.396122014796
19410.66889339182 23213.745970868207
12856.706914291855 15179.63085848928
18502.98021400877 20156.767424366437
20238.95953627832 20990.447541679525
16080.536952477676 14280.251853521351
13616.6055050442 11401.064730980173
11870.978476941147 9294.517308607263
11859.554839874892 9319.884655938613
10306.602802087602 13111.003089008866
19403.183075063855 23251.22175284559
19025.595472415574 17515.22155155338
12858.358602869965 15100.189402785649
18491.738710029407 20174.098443301005
11002.126692599028 13598.218449488153
11237.20376606209 8458.00005911563
11003.47945151896 13622.040118866189
20254.41164838471 20955.33996383738
15446.076195590904 17437.082611492096
19028.352077886302 17546.576446703213
15457.863930051913 17447.03438983256
13591.946983416321 11453.12904843039
11904.0 4608.0
10671.55621266177 9872.609381516115
11162.45134367895 14393.598577145327
10671.55621266177 9872.609381516115
11162.45134367895 14393.598577145327
12213.02005147694 11443.865824099827
17479.500967204414 20694.430965841995
18241.211150852894 23821.21493543098
12103.498153656055 11173.912519793594
15641.448412613343 15772.392906594738
15652.849997364698 19067.00023600986
15702.634703768663 19103.59652002732
15508.701999021208 15627.714932132592
13434.064353817128 13439.23796202746
18110.210027771627 23645.03383376729
13366.895552188811 13397.247478493484
17587.91861619788 20819.69925335138
11120.792004169487 7782.451156287459
11197.199792805342 7911.178546841172
6451.800375089112 9219.0
7786.593928027838 5997.631615896395
7374.000097640357 4608.002712672813
6277.508582232285 9986.76929742547
6276.488588374873 9983.615427288854
7788.182935989912 6000.833275470999
14094.867847021482 14505.273661672158
10085.63845586882 11695.861148286602
16941.290719717905 20520.164960350587
17232.316238973795 15923.539619067113
16956.530624290455 20528.16302059198
7136.464237456809 9642.396019662332
14660.855792296028 12272.897498146067
14076.496030617847 14515.697330820865
16866.92278173467 22163.532660656783
16866.55340370403 17715.6013163539
6998.800285763268 4222.011842711955
14646.658407295501 12268.359507285397
8204.178356179247 5721.217003400588
16880.394006435396 22164.80530029533
6073.6011887512 8848.020400066898
16870.180698498756 17757.103930540026
8215.58640633765 5707.2930536288395
7145.010724274667 9644.274259891203
10079.192567487735 11716.962106279938
17222.58629590806 15910.332648942322
12101.322448393812 12084.518401657551
12082.373442333257 12082.373442333257
12084.518401657551 16721.07786597503
8925.903105568646 8925.741705875203
8924.935083797529 8924.773834669426
12082.373442333257 16693.445060861464
14369.064148370971 16951.500494056567
10060.80096215008 7296.001096491145
12256.539811010647 12355.315617174658
10427.455502182687 8242.50210797668
14014.664641010859 18059.21274585357
11904.000803957677 11904.000672042992
13747.200704143374 16512.00048449612
10429.733313944322 8246.693397962605
14012.382187283503 18051.383464986833
12253.817931113914 12351.741941928676
14371.32427135718 16953.538863611928
12522.720136306045 12509.258651095195
12520.117835397752 12506.495952104251

In [16]:
dataout2[dataout2['Symbol Name']=='82675-60070'].head()

,Symbol Name,Pin Name,Pin CenterY,Pin CenterX,Pin Width,Pin Height,distance_to_center,neighbors,internal_pin
7299,82675-60070,1,3990.0,10153.0,0.0,0.0,10908.872948,NaN,False

In [17]:
len(dataout2),len(dataout)

(7341, 7341)

In [18]:
dataout2.head(10)

,Symbol Name,Pin Name,Pin CenterY,Pin CenterX,Pin Width,Pin Height,distance_to_center,neighbors,internal_pin
0,90980-12A87,8,-5759.0,10368.0,0.0,0.0,11860.080312,"[7, 9, 20, 21, 19]",False
1,90980-12A87,10,-13439.0,10368.0,0.0,0.0,16973.571958,"[11, 9, 22, 23, 21]",True
2,90980-12A87,23,-17279.0,5760.0,0.0,0.0,18213.770642,"[22, 24, 11, 10, 12]",False
3,90980-12A87,6,1920.0,10368.0,0.0,0.0,10544.279207,"[7, 5, 18, 19, 17]",False
4,90980-12A87,15,13440.0,5760.0,0.0,0.0,14622.284363,"[14, 16, 3, 4, 2]",False
5,90980-12A87,20,-5759.0,5760.0,0.0,0.0,8145.163043,"[21, 19, 8, 7, 9]",False
6,90980-12A87,18,1920.0,5760.0,0.0,0.0,6071.573108,"[19, 17, 6, 7, 5]",False
7,90980-12A87,22,-13439.0,5760.0,0.0,0.0,14621.365224,"[23, 21, 10, 11, 9]",False
8,90980-12A87,21,-9599.0,5760.0,0.0,0.0,11194.570157,"[20, 22, 9, 8, 10]",False
9,90980-12A87,17,5760.0,5760.0,0.0,0.0,8145.870119,"[18, 16, 5, 6, 4]",False

In [20]:
dataout2.to_pickle('data/symbols_distances.pkl')

In [39]:
data1 = dataout2[dataout2['Symbol Name']=="90980-12745"] #90980-12379 #90980-12745
data1

,Symbol Name,Pin Name,Pin CenterY,Pin CenterX,Pin Width,Pin Height,distance_to_center,neighbors,internal_pin
5406,90980-12745,2,-8637.0,14587.0,0.0,0.0,16952.236962,"[1, 3, 8, 9, 7, 14, 15]",False
5407,90980-12745,8,-9597.0,8832.0,0.0,0.0,13042.493358,"[9, 14, 7, 2, 15, 13]",True
5408,90980-12745,1,-14391.0,14565.0,0.0,0.0,20475.353623,"[7, 2, 8]",False
5409,90980-12745,17,9590.0,4224.0,0.0,0.0,10479.039842,"[16, 11, 18, 10, 12]",False
5410,90980-12745,14,-9593.0,4224.0,0.0,0.0,10481.785392,"[15, 8, 13, 9, 7]",False
5411,90980-12745,15,-5753.0,4224.0,0.0,0.0,7137.169257,"[14, 9, 8]",False
5412,90980-12745,4,2875.0,14634.0,0.0,0.0,14913.737996,"[3, 5, 10, 11, 9, 16]",False
5413,90980-12745,6,14420.0,14596.0,0.0,0.0,20517.787795,"[12, 5, 11]",False
5414,90980-12745,10,5750.0,8832.0,0.0,0.0,10538.819858,"[11, 16, 17, 4, 5]",False
5415,90980-12745,11,9590.0,8874.0,0.0,0.0,13065.832388,"[10, 17, 12, 5, 16, 18]",True
5416,90980-12745,9,-5753.0,8832.0,0.0,0.0,10540.456964,"[8, 15, 14, 2, 3]",False
5417,90980-12745,3,-2882.0,14618.0,0.0,0.0,14899.390860,"[2, 4, 9, 8, 10, 15]",False
5418,90980-12745,5,8664.0,14634.0,0.0,0.0,17006.435605,"[6, 4, 11, 10, 12, 17, 16]",False
5419,90980-12745,12,14388.0,9258.0,0.0,0.0,17109.211203,"[11, 6, 18, 17, 5, 10]",False
5420,90980-12745,7,-14391.0,9216.0,0.0,0.0,17089.047282,"[8, 1, 13, 14, 2, 9]",False
5421,90980-12745,13,-14393.0,3836.0,0.0,0.0,14895.413556,"[14, 7, 8, 15]",False
5422,90980-12745,16,5750.0,4224.0,0.0,0.0,7134.751292,"[17, 10, 11]",False
5423,90980-12745,18,14390.0,3836.0,0.0,0.0,14892.514764,"[17, 12, 11, 16]",False

In [ ]:
data_json= data1.to_json(orient="records")
dicc_json1=eval(data_json)
dicc_json2=eval(data_json)

In [ ]:
ndistances=[]
xs=[]
ys=[]
for ele in dicc_json1:
    pin=ele['Pin Name']
    print(pin)
    distance_to_center=ele['distance_to_center']
    neighbors=ele["neighbors"]
    xs=[]
    ys=[]
    for ele2 in dicc_json2:
        pin2=ele2['Pin Name']
        
        if pin2 in neighbors:
            ndistances.append(ele2['distance_to_center'])
            xs.append(ele2['Pin CenterX'])
            ys.append(ele2['Pin CenterY'])
            
            
        ndistances=sorted(ndistances)

    nave= np.mean(ndistances)
    xg=0-(np.sum(xs)/len(xs))
    yg=0-(np.sum(ys)/len(ys))
    centroide_distance=sqrt((xg*xg)+(yg*yg))
    print(f"{centroide_distance} {distance_to_center}")
    print((centroide_distance*1.1> distance_to_center>centroide_distance*0.90) and (distance_to_center>centroide_distance))
    #print(nave*1.05> distance_to_center>nave*0.95)
    ndistances=[]

In [ ]:
print(centroide_distance*1.1> distance_to_center>centroide_distance*0.90)

In [ ]:
distances={}
for ele in dicc_json1:
    pin=ele['Pin Name']
    distances[pin]={}
    x1=ele['Pin CenterX']
    y1=ele['Pin CenterY']
    for ele2 in dicc_json2:
        pin2=ele2['Pin Name']
        if ele2 != ele:

            x2=ele2['Pin CenterX']
            y2=ele2['Pin CenterY'] 
            distance=sqrt(((x1-x2)*(x1-x2))+((y1-y2)*(y1-y2)))
            distances[pin][pin2]=distance

In [ ]:
 data1['neighbors']= data1.apply(lambda row: get_neighbors(row, distances), axis=1)

In [ ]:
data1

In [ ]:
distances['2']

In [ ]:
distances_sorted=sorted(distances['2'], key=distances['2'].get, reverse=False)
distances_sorted

In [ ]:
distances["2"][distances_sorted[0]]*1.9

In [ ]:
distances["2"][distances_sorted[0]]

In [ ]:
distances_sorted=sorted(distances['2'], key=distances['2'].get, reverse=False)
ts=distances["2"][distances_sorted[0]]*2
ts

In [ ]:
[x for x in  distances_sorted if distances["2"][x] < ts]

In [ ]:
def get_neighbors(row, distances):
    pin_row=row["Pin Name"]
    distances_sorted=sorted(distances[pin_row], key=distances[pin_row].get, reverse=False)
    ts=distances[pin_row][distances_sorted[0]]*1.95
    return [x for x in  distances_sorted if distances[pin_row][x] < ts]

In [ ]:
data1['neighbors']= data1.apply(lambda row: get_neighbors(row, distances), axis=1)

In [ ]:
data1.columns

In [ ]:
data1[["Pin Name",'neighbors']]

In [ ]:
a=17114.971721
b=17110.687304

c= sqrt((a*a)+(b*b))
c

In [ ]:
x1=16896.0 # (pin 2 and 3)
x2=16896.0 
y1=2729.0
y2=-2702.0

distance=sqrt((x1-x2)**2+(y1-y2)**2)
distance

In [ ]:
x1=16896.0 # (pin 2 and 1)
x2=16896.0 
y1=2729.0
y2=8160.0

distance=sqrt((x1-x2)**2+(y1-y2)**2)
distance

In [ ]:
x1=16896.0 # (pin 2 and 6)
x2=11466.0	 
y1=2729.0
y2=2729.0	

distance=sqrt((x1-x2)**2+(y1-y2)**2)
distance

In [ ]:
x1=16896.0 # (pin 2 and 5)
x2=11466.0 
y1=2729.0
y2=-2702.0

distance=sqrt((x1-x2)**2+(y1-y2)**2)
distance

In [ ]:
x1=16896.0 # (pin 2 and 5)
x2=11466.0 
y1=2729.0
y2=8160.0

distance=sqrt((x1-x2)**2+(y1-y2)**2)
distance

In [ ]:
data["Signal Name"].fillna("na", inplace=True)
data["Pin PreferredSignal"].fillna("na", inplace=True)

In [ ]:
def signal_equal(row):
    if (row["Pin PreferredSignal"]== "na" and row["Signal Name"]== "na") :
        return 2
    elif row["Pin PreferredSignal"]==row["Signal Name"]:
        return 1
    else:
        return 0

In [ ]:
data['check_signal']=data.apply(lambda row:signal_equal(row),axis=1)

In [ ]:
connector_view=data.groupby(["Connector Name",'Pin Name']).agg({ "Pin PreferredSignal":['nunique','count'] })
connector_view.head(10)

In [ ]:
levels=connector_view.index.nlevels
for i in reversed(range(0,levels)):
    connector_view.reset_index(level=i, inplace=True)

In [ ]:
connector_view.columns=['Connector Name','Pin Name','Pin Name nunique',"Pin Name count"]
connector_view.tail(10)

In [ ]:
groupped= pd.merge(connector_view,data, on=['Connector Name','Pin Name'], how='inner')
len(connector_view),len(data),len(groupped)

In [ ]:
connector_view2=data.groupby(["Connector Name"]).agg({ 'Pin Name':['nunique','count'] })
connector_view2.head()

In [ ]:
levels=connector_view2.index.nlevels
for i in reversed(range(0,levels)):
    connector_view2.reset_index(level=i, inplace=True)

In [ ]:
connector_view2.columns=['Connector Name','Num_Pin_unique','Num_Pins']

In [ ]:
connector_view2['more_signal_in_pin']=connector_view2["Num_Pin_unique"]!=connector_view2["Num_Pins"]
connector_view2.head(25)

In [ ]:
groupped2= pd.merge(groupped,connector_view2, on=['Connector Name'], how='inner')
len(groupped2),len(groupped)

In [ ]:
groupped2.head(15)

In [ ]:
def category_signal(row):
    if row["Signal Name"][:5]=='BATT_':
        return 1
    elif row["Signal Name"][:4]=='CAN_':
        return 2
    elif row["Signal Name"][:6]=='CANFD_':
        return 3
    elif row["Signal Name"][:4]=='GND_':
        return 4
    elif row["Signal Name"][:9]=='GNDR_GND_':
        return 5
    else:
        return 6

In [ ]:
groupped2["signal_cat"]= groupped2.apply(lambda row:category_signal(row), axis=1 )

In [ ]:
def category_signal2(row):
    if row["Signal Name"][-3:]=='_HI' or row["Signal Name"][-3:]=='_LO':
        return 1
    else:
        return 0

In [ ]:
groupped2["signal_multicore"]= groupped2.apply(lambda row:category_signal2(row), axis=1 )

In [ ]:
groupped2[["Signal Name","signal_cat","signal_multicore"]].tail(25)

In [ ]:
groupped2['Cat_Signal Name'] = groupped2["Signal Name"].astype('category').cat.codes
c = groupped2["Signal Name"].astype('category')
d = dict(enumerate(c.cat.categories))

In [ ]:
def get_key(x,d):
    key_list=list(d.keys())
    val_list=list(d.values())
    ind=val_list.index(x["Pin PreferredSignal"])
    return key_list[ind]

In [ ]:
groupped2['Cat_PreferredSignal']= groupped2.apply(lambda row: get_key(row,d),axis=1)

In [ ]:
max_categories = groupped2['Cat_Signal Name'].max()

In [ ]:
connectors={}
conn_to_save=""
for i, row in groupped2.iterrows():
    connector=groupped2.loc[i,"Connector Name"]
    pin=groupped2.loc[i,'Pin Name']
    
    if conn_to_save=="" or groupped2.loc[i-1,"Connector Name"]==connector:
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
            
        
        conn_to_save="NO"
    else:
        conn_to_save=""
        try:
        
            connectors[connector][pin]={}
        except:
            connectors[connector]={}
            connectors[connector][pin]={}
    
    #Part Number at level of PIN
    PartNumber =groupped2.loc[i,'Connector PartNumber']
    connectors[connector]["PartNumber"]=PartNumber
    #prefered Signal
    PreferredSignal=groupped2.loc[i,'Pin PreferredSignal']
    connectors[connector][pin]['PreferredSignal']=PreferredSignal
    Cat_PreferredSignal=groupped2.loc[i,'Cat_PreferredSignal']
    connectors[connector][pin]['Cat_PreferredSignal']=Cat_PreferredSignal
    
    # Signal in that pin
    Signal =groupped2.loc[i,'Signal Name']
    connectors[connector][pin]['Signal']=Signal
    Cat_Signal =groupped2.loc[i,'Cat_Signal Name']
    connectors[connector][pin]['Cat_Signal']=Cat_Signal
    #Check Signal 1 preferred = Signal, 0 1 preferred != Signal, 2 both NaN 
    check_signal=groupped2.loc[i,'check_signal']
    connectors[connector][pin]['check_signal']=check_signal
    #Number of pins connector
    Num_Pins =groupped2.loc[i,'Num_Pins']
    connectors[connector][pin]['Num_Pins']=Num_Pins
    #Number of unique Pins in this connector
    Num_Pin_unique=groupped2.loc[i,'Num_Pin_unique']
    connectors[connector][pin]['Num_Pin_unique']=Num_Pin_unique
    #True if number of Pins is not the same of number of unique Pins
    more_signal_in_pin =groupped2.loc[i,'more_signal_in_pin']
    connectors[connector][pin]['more_signal_in_pin']=more_signal_in_pin

In [ ]:
len(connectors['TO_111_LH_(121)'].keys())-1

In [ ]:
connectors['TO_111_LH_(121)'][1]['Cat_Signal']

In [ ]:
Cat_PreferredSignals=[]
for key in connectors['TO_111_LH_(121)'].keys():
    if key != 'PartNumber':
        Cat_PreferredSignals.append(connectors['TO_111_LH_(121)'][key]['Cat_PreferredSignal'])

In [ ]:
Cat_PreferredSignals

In [ ]:
import random

print(random.randint(0, max_categories ))

In [ ]:
for i in range(10):
    print(random.random())

In [ ]:
len(connectors.keys())

In [ ]:
len(data['Signal Name'].unique()),len(data['Pin PreferredSignal'].unique())

In [ ]:
signal_view=data.groupby(["Pin PreferredSignal"]).agg({"Pin Name":[ "count", 'nunique'], "Connector Name":'nunique' })
signal_view.head(10)

In [ ]:
groupped.to_csv("data/connectors.csv", index=False)

In [ ]:
groupped['Connector PartNumber'].fillna("NOPARTNUMBER", inplace=True)
groupped.head(20)